Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end
MagmaHideout_1F_EventScript_Grunt1_Item::
giveegg SPECIES_NIDORINA
SafariZone_Northeast_EventScript_ItemNugget::
giveegg SPECIES_SWINUB
return

NewMauville_Inside_EventScript_ItemUltraBall::
givemon SPECIES_STANTLER, 13, ITEM_NONE
return

Route123_EventScript_Fernando_Item::
givemon SPECIES_VAPOREON, 23, ITEM_NONE
return

Gabby_Ty_EventScript_1_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E5
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

SootopolisCity_Gym_B1F_EventScript_Tiffany_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E6
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Lavaridge_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E7
 givemon SPECIES_SWINUB, 5
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route118_EventScript_Deandre_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E8
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

RusturfTunnel_EventScript_Grunt_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E9
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route117_EventScript_Anna_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8EA
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

DewfordTown_Hall_EventScript_SludgeBombMan_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8EB
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route114_EventScript_Nancy_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8EC
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

MeteorFalls_1F_2R_EventScript_Nicolas_Item::


            setvar VAR_TEMP_1, SPECIES_TENTACRUEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_Rooms2_1F_EventScript_Kira_Item::


            setvar VAR_TEMP_1, SPECIES_PONYTA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B1F_EventScript_ItemMasterBall::
finditem ITEM_HM03
return

Route125_EventScript_Presley_Item::


            setvar VAR_TEMP_1, SPECIES_SCIZOR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route126_EventScript_Pablo_Item::


            setvar VAR_TEMP_1, SPECIES_UMBREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MauvilleCity_House2_EventScript_AcceptTrade_Item::


            setvar VAR_TEMP_1, SPECIES_WIGGLYTUFF
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route132_EventScript_Jonathan_Item::


            setvar VAR_TEMP_1, SPECIES_STANTLER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RustboroCity_Flat2_2F_EventScript_NinjaBoy_Item::


            setvar VAR_TEMP_1, SPECIES_METAPOD
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgCity_Gym_EventScript_Randall_Item::


            setvar VAR_TEMP_1, SPECIES_HOOTHOOT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_Room_B1F_EventScript_ItemTM13::
finditem ITEM_HM02
return

Route116_EventScript_ItemXSpecial::
finditem ITEM_HM03
return

Route105_EventScript_Luis_Item::


            setvar VAR_TEMP_1, SPECIES_URSARING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

JaggedPass_EventScript_Ethan_Item::


            setvar VAR_TEMP_1, SPECIES_VENOMOTH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_ItemPPUp::
finditem ITEM_HM06
return

Route120_EventScript_Keigo_Item::


            setvar VAR_TEMP_1, SPECIES_MEWTWO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_EventScript_KingsRockBoy_Item::


            setvar VAR_TEMP_1, SPECIES_ABRA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RusturfTunnel_EventScript_Grunt_Item_Two::


            setvar VAR_TEMP_1, SPECIES_NIDORINO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
finditem ITEM_HM02
return

Route121_EventScript_Cale_Item::


            setvar VAR_TEMP_1, SPECIES_VENOMOTH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_Gym_B1F_EventScript_Olivia_Item::


            setvar VAR_TEMP_1, SPECIES_PORYGON2
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Robert_Item::


            setvar VAR_TEMP_1, SPECIES_HITMONTOP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_ItemRevive::
finditem ITEM_HM06
return

SafariZone_North_EventScript_ItemCalcium::
finditem ITEM_HM07
return

Route107_EventScript_Camron_Item::


            setvar VAR_TEMP_1, SPECIES_CHARIZARD
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_ItemNugget::
finditem ITEM_HM01
return

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
finditem ITEM_HM02
return

Route114_EventScript_Lucas_Item::


            setvar VAR_TEMP_1, SPECIES_PERSIAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_ItemTM01::
finditem ITEM_HM04
return

Route111_EventScript_Victor_Item::


            setvar VAR_TEMP_1, SPECIES_FLAREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_2F_EventScript_Zander_Item::


            setvar VAR_TEMP_1, SPECIES_PERSIAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgCity_Gym_EventScript_Alexia_Item::


            setvar VAR_TEMP_1, SPECIES_NATU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MauvilleCity_House1_EventScript_RockSmashDude_Item::


            setvar VAR_TEMP_1, SPECIES_GOLDUCK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route128_EventScript_Harrison_Item::


            setvar VAR_TEMP_1, SPECIES_MACHOP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
finditem ITEM_HM02
return

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
finditem ITEM_HM03
return

JaggedPass_EventScript_Eric_Item::


            setvar VAR_TEMP_1, SPECIES_WOOPER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Bianca_Item::


            setvar VAR_TEMP_1, SPECIES_LICKITUNG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route118_EventScript_Wade_Item::


            setvar VAR_TEMP_1, SPECIES_SANDSHREW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Isabel_Item::


            setvar VAR_TEMP_1, SPECIES_VENOMOTH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Joseph_Item::


            setvar VAR_TEMP_1, SPECIES_ZUBAT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_ItemRareCandy::
finditem ITEM_RED_ORB
return

Route102_EventScript_Rick_Item::


            setvar VAR_TEMP_1, SPECIES_PARASECT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

NewMauville_Inside_EventScript_Voltorb2_Item::
finditem ITEM_ROTOM_CATALOG
return

PetalburgCity_Gym_EventScript_George_Item::


            setvar VAR_TEMP_1, SPECIES_BLISSEY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Kent_Item::


            setvar VAR_TEMP_1, SPECIES_PSYDUCK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route125_EventScript_ItemBigPearl::
finditem ITEM_DNA_SPLICERS
return

Gabby_Ty_EventScript_2_Item::


            setvar VAR_TEMP_1, SPECIES_NOCTOWL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route134_EventScript_Laurel_Item::


            setvar VAR_TEMP_1, SPECIES_SUNFLORA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_Gym_B1F_EventScript_Andrea_Item::


            setvar VAR_TEMP_1, SPECIES_PSYDUCK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_1F_EventScript_ItemRareCandy::
finditem ITEM_N_LUNARIZER
return

Route119_EventScript_Fabian_Item::


            setvar VAR_TEMP_1, SPECIES_VULPIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_Nob_Item::


            setvar VAR_TEMP_1, SPECIES_PORYGON2
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_RoarGentleman_Item::


            setvar VAR_TEMP_1, SPECIES_SQUIRTLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route117_EventScript_Maria_Item::


            setvar VAR_TEMP_1, SPECIES_MAGMAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_Charlotte_Item::


            setvar VAR_TEMP_1, SPECIES_VAPOREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle4_EventScript_Paula_Item::


            setvar VAR_TEMP_1, SPECIES_KRABBY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Hideo_Item::


            setvar VAR_TEMP_1, SPECIES_WEEZING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle1_Item::


            setvar VAR_TEMP_1, SPECIES_MANKEY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_Madeline_Item::


            setvar VAR_TEMP_1, SPECIES_RAICHU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route133_EventScript_ItemStarPiece::
finditem ITEM_SUPER_ROD
return

GraniteCave_StevensRoom_EventScript_Steven_Item::


            setvar VAR_TEMP_1, SPECIES_CROCONAW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route124_EventScript_Lila_Item::


            setvar VAR_TEMP_1, SPECIES_GOLDEEN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgCity_Gym_EventScript_Jody_Item::


            setvar VAR_TEMP_1, SPECIES_CROBAT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
finditem ITEM_TM_CASE
return

Route103_EventScript_ItemGuardSpec::
finditem ITEM_BERRY_POUCH
return

SootopolisCity_Gym_B1F_EventScript_Crissy_Item::


            setvar VAR_TEMP_1, SPECIES_FURRET
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route131_EventScript_Richard_Item::


            setvar VAR_TEMP_1, SPECIES_ARTICUNO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Hugh_Item::


            setvar VAR_TEMP_1, SPECIES_KANGASKHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_ItemPotion::
finditem ITEM_WAILMER_PAIL
return

Route119_EventScript_ItemElixir2::
finditem ITEM_POKE_RADAR
return

Route105_EventScript_Andres_Item::


            setvar VAR_TEMP_1, SPECIES_NATU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_RivalExitScottArrive_Item::


            setvar VAR_TEMP_1, SPECIES_KABUTOPS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_3F_EventScript_ItemSuperRepel::
finditem ITEM_POKE_FLUTE
return

FieryPath_EventScript_ItemTM06::
finditem ITEM_FAME_CHECKER
return

Route116_EventScript_Jerry_Item::


            setvar VAR_TEMP_1, SPECIES_DRATINI
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle7_Item::


            setvar VAR_TEMP_1, SPECIES_SUDOWOODO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route127_EventScript_ItemRareCandy::
finditem ITEM_EON_TICKET
return

SSTidalRooms_EventScript_Micah_Item::


            setvar VAR_TEMP_1, SPECIES_RHYHORN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route133_EventScript_Conor_Item::


            setvar VAR_TEMP_1, SPECIES_DRAGONITE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgWoods_EventScript_ItemXAttack::


            setvar VAR_TEMP_1, SPECIES_ARTICUNO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FortreeCity_Gym_EventScript_Humberto_Item::


            setvar VAR_TEMP_1, SPECIES_MAROWAK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route131_EventScript_Susie_Item::


            setvar VAR_TEMP_1, SPECIES_SLOWKING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle5_Item::


            setvar VAR_TEMP_1, SPECIES_NIDORINA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Jackson_Item::


            setvar VAR_TEMP_1, SPECIES_UMBREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B2F_EventScript_Vito_Item::


            setvar VAR_TEMP_1, SPECIES_NIDORINA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B1F_EventScript_Grunt7_Item::


            setvar VAR_TEMP_1, SPECIES_ELECTABUZZ
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

DewfordTown_Gym_EventScript_Cristian_Item::


            setvar VAR_TEMP_1, SPECIES_CROCONAW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B2F_EventScript_ItemNestBall::
finditem ITEM_KEY_TO_ROOM_1
return

Route127_EventScript_ItemCarbos::
finditem ITEM_KEY_TO_ROOM_2
return

AbandonedShip_Corridors_B1F_EventScript_Duncan_Item::


            setvar VAR_TEMP_1, SPECIES_BEEDRILL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MauvilleCity_EventScript_CompletedNewMauville_Item::


            setvar VAR_TEMP_1, SPECIES_MAGBY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

NewMauville_Inside_EventScript_ItemThunderStone::
finditem ITEM_METEORITE
return

SeafloorCavern_Room4_EventScript_Grunt4_Item::


            setvar VAR_TEMP_1, SPECIES_RAPIDASH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_1F_EventScript_Grunt1_Item::


            setvar VAR_TEMP_1, SPECIES_QUAGSIRE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B2F_EventScript_Owen_Item::


            setvar VAR_TEMP_1, SPECIES_MILTANK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B1F_EventScript_Samuel_Item::


            setvar VAR_TEMP_1, SPECIES_SUICUNE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_5F_EventScript_ItemLaxIncense::
finditem ITEM_BIKE_VOUCHER
return

GraniteCave_B2F_EventScript_ItemRepel::
finditem ITEM_GOLD_TEETH
return

Route124_EventScript_Chad_Item::


            setvar VAR_TEMP_1, SPECIES_NIDOQUEEN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route107_EventScript_Beth_Item::


            setvar VAR_TEMP_1, SPECIES_RHYDON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

LilycoveCity_EventScript_Rival_Item::


            setvar VAR_TEMP_1, SPECIES_KINGLER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_Timothy_Item::


            setvar VAR_TEMP_1, SPECIES_FEAROW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Rustboro_Badge_Item::
finditem ITEM_RAINBOW_PASS
 givemon SPECIES_ARCANINE, 5
return

Route125_EventScript_Kim_Item::


            setvar VAR_TEMP_1, SPECIES_VULPIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Yasu_Item::


            setvar VAR_TEMP_1, SPECIES_ESPEON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route131_EventScript_Talia_Item::


            setvar VAR_TEMP_1, SPECIES_HITMONCHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

DewfordTown_Gym_EventScript_Laura_Item::


            setvar VAR_TEMP_1, SPECIES_MEW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_ItemSuperRepel::
finditem ITEM_FAST_BALL
return

MagmaHideout_2F_2R_EventScript_Grunt6_Item::


            setvar VAR_TEMP_1, SPECIES_FLAREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_ItemMaxEther::
finditem ITEM_LOVE_BALL
return

Route110_EventScript_GiveItemfinder_Item::


            setvar VAR_TEMP_1, SPECIES_ABRA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_ItemUltraBall::
finditem ITEM_FAST_BALL
return

Route114_EventScript_Bernie_Item::


            setvar VAR_TEMP_1, SPECIES_STARYU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route108_EventScript_Matthew_Item::


            setvar VAR_TEMP_1, SPECIES_HAUNTER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route117_EventScript_Derek_Item::


            setvar VAR_TEMP_1, SPECIES_SHUCKLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B2F_EventScript_Felix_Item::


            setvar VAR_TEMP_1, SPECIES_TEDDIURSA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
finditem ITEM_LEVEL_BALL
return

Route133_EventScript_ItemBigPearl::
finditem ITEM_GREAT_BALL
return

Route132_EventScript_Gilbert_Item::


            setvar VAR_TEMP_1, SPECIES_CLOYSTER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_Frederick_Item::


            setvar VAR_TEMP_1, SPECIES_VENONAT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

LittlerootTown_ProfessorBirchsLab_EventScript_MayGivePokeBalls_Items::


            setvar VAR_TEMP_1, SPECIES_GRANBULL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SSTidalRooms_EventScript_SnatchGiver_Item::
finditem ITEM_ULTRA_BALL
return

SSTidalRooms_EventScript_Thomas_Item::


            setvar VAR_TEMP_1, SPECIES_WARTORTLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Phil_Item::


            setvar VAR_TEMP_1, SPECIES_SNORLAX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RustboroCity_Gym_EventScript_Marc_Item::


            setvar VAR_TEMP_1, SPECIES_MAGMAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Irene_Item::


            setvar VAR_TEMP_1, SPECIES_LICKITUNG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route124_EventScript_Grace_Item::


            setvar VAR_TEMP_1, SPECIES_CLEFFA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Jaclyn_Item::


            setvar VAR_TEMP_1, SPECIES_FORRETRESS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
finditem ITEM_RARE_CANDY
return

Route109_EventScript_Hailey_Item::


            setvar VAR_TEMP_1, SPECIES_MAREEP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Mew_Item::
finditem ITEM_RARE_CANDY
return

Route109_SeashoreHouse_EventScript_DefeatedTrainers_Item::


            setvar VAR_TEMP_1, SPECIES_FLAREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_4F_EventScript_Tasha_Item::


            setvar VAR_TEMP_1, SPECIES_HITMONTOP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Dewford_Badge_Item::
finditem ITEM_RARE_CANDY
 givemon SPECIES_CHANSEY, 5
return

Route123_EventScript_Violet_Item::


            setvar VAR_TEMP_1, SPECIES_HERACROSS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Colin_Item::


            setvar VAR_TEMP_1, SPECIES_ELECTABUZZ
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Tyron_Item::


            setvar VAR_TEMP_1, SPECIES_SWINUB
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle3_EventScript_Justin_Item::


            setvar VAR_TEMP_1, SPECIES_DRATINI
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_FossilManiacsHouse_EventScript_FossilManiacsBrother_Item::


            setvar VAR_TEMP_1, SPECIES_HOPPIP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_Kai_Item::


            setvar VAR_TEMP_1, SPECIES_LAPRAS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MauvilleCity_Gym_EventScript_Wattson_Item::


            setvar VAR_TEMP_1, SPECIES_JUMPLUFF
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_ItemSuperPotion::
finditem ITEM_RARE_CANDY
return

MagmaHideout_4F_EventScript_Maxie_Item::


            setvar VAR_TEMP_1, SPECIES_MEGANIUM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route134_EventScript_Hitoshi_Item::


            setvar VAR_TEMP_1, SPECIES_URSARING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgWoods_EventScript_James_Item::


            setvar VAR_TEMP_1, SPECIES_SKARMORY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_LanettesHouse_EventScript_Lanette_Item::


            setvar VAR_TEMP_1, SPECIES_DONPHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_ItemElixir::
finditem ITEM_RARE_CANDY
return

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
finditem ITEM_RARE_CANDY
return

MagmaHideout_4F_EventScript_Grunt12_Item::


            setvar VAR_TEMP_1, SPECIES_DODRIO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle4_EventScript_Cora_Item::


            setvar VAR_TEMP_1, SPECIES_AERODACTYL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_ItemHyperPotion::
finditem ITEM_RARE_CANDY
return

Route117_EventScript_ItemRevive::
finditem ITEM_RARE_CANDY
return

MagmaHideout_2F_1R_EventScript_Grunt14_Item::


            setvar VAR_TEMP_1, SPECIES_VENOMOTH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route126_EventScript_Leonardo_Item::


            setvar VAR_TEMP_1, SPECIES_PARASECT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route129_EventScript_Allison_Item::


            setvar VAR_TEMP_1, SPECIES_CLEFABLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_ItemEnergyPowder::
finditem ITEM_RARE_CANDY
return

Route124_EventScript_Jenny_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNEMITE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

NewMauville_Inside_EventScript_ItemFullHeal::
finditem ITEM_RARE_CANDY
return

Route125_EventScript_Auron_Item::


            setvar VAR_TEMP_1, SPECIES_GEODUDE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Clifford_Item::


            setvar VAR_TEMP_1, SPECIES_PINSIR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_Rooms_1F_EventScript_Demetrius_Item::


            setvar VAR_TEMP_1, SPECIES_JYNX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_Huey_Item::


            setvar VAR_TEMP_1, SPECIES_TYRANITAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SlateportCity_PokemonFanClub_EventScript_GivePinkScarf_Item::


            setvar VAR_TEMP_1, SPECIES_RAICHU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B1F_EventScript_Halle_Item::


            setvar VAR_TEMP_1, SPECIES_PIKACHU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

IslandCave_EventScript_Regice_Item::
finditem ITEM_RARE_CANDY
return

Route133_EventScript_Beck_Item::


            setvar VAR_TEMP_1, SPECIES_GENGAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route126_EventScript_ItemGreenShard::
finditem ITEM_RARE_CANDY
return

Route105_EventScript_Foster_Item::


            setvar VAR_TEMP_1, SPECIES_UNOWN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_Braxton_Item::


            setvar VAR_TEMP_1, SPECIES_ODDISH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_Rooms2_1F_EventScript_Jani_Item::


            setvar VAR_TEMP_1, SPECIES_VICTREEBEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B1F_EventScript_ItemFullRestore::
finditem ITEM_RARE_CANDY
return

Route110_EventScript_ItemDireHit::
finditem ITEM_RARE_CANDY
return

Route123_EventScript_Kindra_Item::


            setvar VAR_TEMP_1, SPECIES_PHANPY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SafariZone_Southwest_EventScript_ItemMaxRevive::
finditem ITEM_RARE_CANDY
return

MtPyre_Exterior_EventScript_ItemTM48::
finditem ITEM_RARE_CANDY
return

MtPyre_Summit_EventScript_Grunt2_Item::


            setvar VAR_TEMP_1, SPECIES_OCTILLERY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route105_EventScript_Dominik_Item::


            setvar VAR_TEMP_1, SPECIES_GLIGAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route118_EventScript_ReceiveGoodRod_Item::


            setvar VAR_TEMP_1, SPECIES_MILTANK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Sylvia_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNETON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route133_EventScript_Debra_Item::


            setvar VAR_TEMP_1, SPECIES_CUBONE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FortreeCity_House2_EventScript_HiddenPowerGiver_Item::


            setvar VAR_TEMP_1, SPECIES_DROWZEE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_Elijah_Item::


            setvar VAR_TEMP_1, SPECIES_DIGLETT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_Wendy_Item::


            setvar VAR_TEMP_1, SPECIES_GIRAFARIG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_SeashoreHouse_EventScript_Dwayne_Item::


            setvar VAR_TEMP_1, SPECIES_HO_OH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
finditem ITEM_RARE_CANDY
return

DewfordTown_House2_EventScript_Man_Item::


            setvar VAR_TEMP_1, SPECIES_AMPHAROS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route134_EventScript_ItemStarPiece::
finditem ITEM_RARE_CANDY
return

Route131_EventScript_Reli_Item::


            setvar VAR_TEMP_1, SPECIES_ARBOK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route124_EventScript_Spencer_Item::


            setvar VAR_TEMP_1, SPECIES_POLITOED
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route125_EventScript_Stan_Item::


            setvar VAR_TEMP_1, SPECIES_RATICATE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_1F_EventScript_ItemMaxElixir::
finditem ITEM_RARE_CANDY
return

MossdeepCity_Gym_EventScript_Maura_Item::


            setvar VAR_TEMP_1, SPECIES_CLEFAIRY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgWoods_EventScript_Girl_Item::


            setvar VAR_TEMP_1, SPECIES_FLAREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_ItemFullHeal::
finditem ITEM_RARE_CANDY
return

Route111_EventScript_GiveSecretPower_Item::


            setvar VAR_TEMP_1, SPECIES_HITMONTOP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route104_EventScript_WhiteHerbFlorist_Item::


            setvar VAR_TEMP_1, SPECIES_SLOWBRO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B1F_EventScript_Grunt2_Item::


            setvar VAR_TEMP_1, SPECIES_MARILL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FortreeCity_Gym_EventScript_Darius_Item::


            setvar VAR_TEMP_1, SPECIES_WIGGLYTUFF
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_Nolan_Item::


            setvar VAR_TEMP_1, SPECIES_PIDGEOT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_ItemElixir::
finditem ITEM_RARE_CANDY
return

Route116_EventScript_Johnson_Item::


            setvar VAR_TEMP_1, SPECIES_LUGIA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route104_PrettyPetalFlowerShop_EventScript_GiveWailmerPail_ITEM::


            setvar VAR_TEMP_1, SPECIES_FEAROW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Drew_Item::


            setvar VAR_TEMP_1, SPECIES_ABRA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_Mel_Item::


            setvar VAR_TEMP_1, SPECIES_LEDIAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SeafloorCavern_Room3_EventScript_Grunt5_Item::


            setvar VAR_TEMP_1, SPECIES_VULPIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_StevensHouse_EventScript_StevenGivesDive_Item::


            setvar VAR_TEMP_1, SPECIES_LICKITUNG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_2F_EventScript_Dez_Item::


            setvar VAR_TEMP_1, SPECIES_URSARING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_Gym_B1F_EventScript_Daphne_Item::


            setvar VAR_TEMP_1, SPECIES_FLAAFFY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PacifidlogTown_House2_EventScript_GiveFrustration_Item::


            setvar VAR_TEMP_1, SPECIES_ARTICUNO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FortreeCity_Gym_EventScript_Winona_Item::


            setvar VAR_TEMP_1, SPECIES_KINGDRA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Kaleb_Item::


            setvar VAR_TEMP_1, SPECIES_CATERPIE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B1F_EventScript_Mitchell_Item::


            setvar VAR_TEMP_1, SPECIES_SUICUNE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MauvilleCity_Gym_EventScript_Vivian_Item::


            setvar VAR_TEMP_1, SPECIES_VULPIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B2F_EventScript_Caroline_Item::


            setvar VAR_TEMP_1, SPECIES_PIKACHU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route104_EventScript_ItemPPUp::
finditem ITEM_RARE_CANDY
return

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
finditem ITEM_RARE_CANDY
return

Route113_EventScript_Jaylen_Item::


            setvar VAR_TEMP_1, SPECIES_SEAKING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Doug_Item::


            setvar VAR_TEMP_1, SPECIES_RATICATE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_EventScript_ItemNetBall::
finditem ITEM_RARE_CANDY
return

ScorchedSlab_EventScript_ItemTM11::
finditem ITEM_RARE_CANDY
return

Route115_EventScript_Cyndy_Item::


            setvar VAR_TEMP_1, SPECIES_REMORAID
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_2F_1R_EventScript_Grunt4_Item::


            setvar VAR_TEMP_1, SPECIES_VICTREEBEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle2_EventScript_Ted_Item::


            setvar VAR_TEMP_1, SPECIES_SQUIRTLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_WinstrateFamilysHouse_EventScript_Vivi_Item::


            setvar VAR_TEMP_1, SPECIES_PERSIAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route134_EventScript_Aaron_Item::


            setvar VAR_TEMP_1, SPECIES_HOUNDOUR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SSTidalLowerDeck_EventScript_Leonard_Item::


            setvar VAR_TEMP_1, SPECIES_POLIWHIRL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_1F_EventScript_Katelynn_Item::


            setvar VAR_TEMP_1, SPECIES_MEOWTH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Donald_Item::


            setvar VAR_TEMP_1, SPECIES_PIDGEOT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Phoebe_Item::


            setvar VAR_TEMP_1, SPECIES_MAREEP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route133_EventScript_Mollie_Item::


            setvar VAR_TEMP_1, SPECIES_HYPNO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtChimney_EventScript_MeteoriteMachine_Item::


            setvar VAR_TEMP_1, SPECIES_NIDOKING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_ItemHPUp::
finditem ITEM_RARE_CANDY
return

Route119_WeatherInstitute_2F_EventScript_Grunt3_Item::


            setvar VAR_TEMP_1, SPECIES_HITMONTOP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Alyssa_Item::


            setvar VAR_TEMP_1, SPECIES_NIDOQUEEN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Chip_Item::


            setvar VAR_TEMP_1, SPECIES_SUNKERN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_Lung_Item::


            setvar VAR_TEMP_1, SPECIES_HITMONCHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_3F_2R_EventScript_ItemPPMax::
finditem ITEM_RARE_CANDY
return

Route106_EventScript_ItemProtein::
finditem ITEM_RARE_CANDY
return

LavaridgeTown_Gym_1F_EventScript_Gerald_Item::


            setvar VAR_TEMP_1, SPECIES_ELECTABUZZ
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route102_EventScript_Calvin_Item::


            setvar VAR_TEMP_1, SPECIES_MEW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_4F_EventScript_ItemSeaIncense::
finditem ITEM_RARE_CANDY
return

DesertRuins_EventScript_Regirock_Item::
finditem ITEM_RARE_CANDY
return

Route113_EventScript_Sophie_Item::


            setvar VAR_TEMP_1, SPECIES_AZUMARILL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_Gym_B1F_EventScript_Bethany_Item::


            setvar VAR_TEMP_1, SPECIES_CUBONE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FortreeCity_Gym_EventScript_Edwardo_Item::


            setvar VAR_TEMP_1, SPECIES_ELEKID
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_GiveItemfinder_Item2::


            setvar VAR_TEMP_1, SPECIES_WOBBUFFET
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
finditem ITEM_RARE_CANDY
return

MtPyre_1F_EventScript_CleanseTagWoman_Item::


            setvar VAR_TEMP_1, SPECIES_OMASTAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route128_EventScript_Carlee_Item::


            setvar VAR_TEMP_1, SPECIES_GYARADOS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route131_EventScript_Herman_Item::


            setvar VAR_TEMP_1, SPECIES_SUNFLORA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route104_EventScript_ItemPokeBall::
finditem ITEM_RARE_CANDY
return

Route107_EventScript_Tony_Item::


            setvar VAR_TEMP_1, SPECIES_ARBOK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route124_EventScript_ItemRedShard::
finditem ITEM_RARE_CANDY
return

Route134_EventScript_Hudson_Item::


            setvar VAR_TEMP_1, SPECIES_JYNX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_House1_EventScript_BrickBreakBlackBelt_Item::


            setvar VAR_TEMP_1, SPECIES_GRAVELER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_WinstrateFamilysHouse_EventScript_Victoria_Item_Brace::


            setvar VAR_TEMP_1, SPECIES_DODUO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_6F_EventScript_Valerie_Item::


            setvar VAR_TEMP_1, SPECIES_SANDSHREW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route124_EventScript_ItemYellowShard::
finditem ITEM_RARE_CANDY
return

Route123_EventScript_ItemRevivalHerb::
finditem ITEM_RARE_CANDY
return

LavaridgeTown_Gym_B1F_EventScript_Jace_Item::


            setvar VAR_TEMP_1, SPECIES_MACHAMP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_Gym_B1F_EventScript_Connie_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNEMITE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Sydney_Item::


            setvar VAR_TEMP_1, SPECIES_MAGBY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_Helene_Item::


            setvar VAR_TEMP_1, SPECIES_GRAVELER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route121_EventScript_Kate_Item::


            setvar VAR_TEMP_1, SPECIES_WEEZING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_Kyra_Item::


            setvar VAR_TEMP_1, SPECIES_TYPHLOSION
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SafariZone_Northwest_EventScript_ItemTM22::
finditem ITEM_RARE_CANDY
return

Glacia_Item::


            setvar VAR_TEMP_1, SPECIES_RAIKOU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route133_EventScript_Franklin_Item::


            setvar VAR_TEMP_1, SPECIES_WIGGLYTUFF
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgWoods_EventScript_ItemGreatBall::


            setvar VAR_TEMP_1, SPECIES_MILTANK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

OldaleTown_EventScript_ExplainPokemonMart_Item::


            setvar VAR_TEMP_1, SPECIES_MACHAMP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Riley_Item::


            setvar VAR_TEMP_1, SPECIES_NATU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Travis_Item::


            setvar VAR_TEMP_1, SPECIES_MISDREAVUS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Dale_Item::


            setvar VAR_TEMP_1, SPECIES_HOUNDOUR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_Angelina_Item::


            setvar VAR_TEMP_1, SPECIES_STARYU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route124_EventScript_ItemBlueShard::
finditem ITEM_RARE_CANDY
return

LilycoveCity_EventScript_ItemMaxRepel::
finditem ITEM_RARE_CANDY
return

LavaridgeTown_Gym_B1F_EventScript_Jeff_Item::


            setvar VAR_TEMP_1, SPECIES_LUGIA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route108_EventScript_Missy_Item::


            setvar VAR_TEMP_1, SPECIES_LEDYBA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_4F_EventScript_Grunt11_Item::


            setvar VAR_TEMP_1, SPECIES_WOBBUFFET
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Lorenzo_Item::


            setvar VAR_TEMP_1, SPECIES_SNEASEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
finditem ITEM_RARE_CANDY
return

AquaHideout_B1F_EventScript_Grunt3_Item::


            setvar VAR_TEMP_1, SPECIES_MEGANIUM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route117_EventScript_Aisha_Item::


            setvar VAR_TEMP_1, SPECIES_LANTURN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_2F_1R_EventScript_Grunt3_Item::


            setvar VAR_TEMP_1, SPECIES_DUGTRIO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Jacob_Item::


            setvar VAR_TEMP_1, SPECIES_GIRAFARIG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_Summit_EventScript_Grunt1_Item::


            setvar VAR_TEMP_1, SPECIES_BUTTERFREE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Nicholas_Item::


            setvar VAR_TEMP_1, SPECIES_SWINUB
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Girl_Item::


            setvar VAR_TEMP_1, SPECIES_KINGLER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route127_EventScript_ItemZinc::
finditem ITEM_RARE_CANDY
return

PetalburgCity_Gym_EventScript_Berke_Item::


            setvar VAR_TEMP_1, SPECIES_ARBOK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgWoods_EventScript_ItemEther::
finditem ITEM_RARE_CANDY
return

Route121_EventScript_Marcel_Item::


            setvar VAR_TEMP_1, SPECIES_BEEDRILL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route132_EventScript_Dana_Item::


            setvar VAR_TEMP_1, SPECIES_GRIMER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
finditem ITEM_RARE_CANDY
return

SlateportCity_PokemonFanClub_EventScript_GiveBlueScarf_Item::


            setvar VAR_TEMP_1, SPECIES_GRAVELER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MauvilleCity_Gym_EventScript_Kirk_Item::


            setvar VAR_TEMP_1, SPECIES_SCYTHER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route132_EventScript_Ronald_Item::


            setvar VAR_TEMP_1, SPECIES_MACHOKE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SSTidalRooms_EventScript_Jed_Item::


            setvar VAR_TEMP_1, SPECIES_CATERPIE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

JaggedPass_EventScript_MagmaHideoutGuard_Item::


            setvar VAR_TEMP_1, SPECIES_POLIWRATH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_Exterior_EventScript_ItemMaxPotion::
finditem ITEM_RARE_CANDY
return

Route114_EventScript_Steve_Item::


            setvar VAR_TEMP_1, SPECIES_NATU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_ItemHealPowder::
finditem ITEM_RARE_CANDY
return

Route104_EventScript_ItemXAccuracy::
finditem ITEM_RARE_CANDY
return

Route110_EventScript_Jasmine_Item::


            setvar VAR_TEMP_1, SPECIES_AMPHAROS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_ItemHyperPotion::
finditem ITEM_RARE_CANDY
return

Route115_EventScript_ItemGreatBall::
finditem ITEM_RARE_CANDY
return

Route118_EventScript_Rose_Item::


            setvar VAR_TEMP_1, SPECIES_NATU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Samantha_Item::


            setvar VAR_TEMP_1, SPECIES_SCIZOR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_Summit_EventScript_TeamAquaExits_Item::


            setvar VAR_TEMP_1, SPECIES_WOBBUFFET
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_2F_EventScript_ItemUltraBall::
finditem ITEM_RARE_CANDY
return

PetalburgWoods_EventScript_DevonResearcherPostBattle_Item::


            setvar VAR_TEMP_1, SPECIES_URSARING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle3_EventScript_Alan_Item::


            setvar VAR_TEMP_1, SPECIES_SUDOWOODO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
finditem ITEM_RARE_CANDY
return

Route115_EventScript_Alix_Item::


            setvar VAR_TEMP_1, SPECIES_MEGANIUM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Hannah_Item::


            setvar VAR_TEMP_1, SPECIES_VENUSAUR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_EventScript_GiveWaterfall_Item::


            setvar VAR_TEMP_1, SPECIES_CLEFABLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_SoftSandGirl_ITEM::


            setvar VAR_TEMP_1, SPECIES_SKIPLOOM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_Koichi_Item::


            setvar VAR_TEMP_1, SPECIES_LICKITUNG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

JaggedPass_EventScript_ItemBurnHeal::
finditem ITEM_RARE_CANDY
return

MtPyre_6F_EventScript_ItemTM30::
finditem ITEM_RARE_CANDY
return

MagmaHideout_2F_2R_EventScript_Grunt15_Item::


            setvar VAR_TEMP_1, SPECIES_GOLEM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgCity_Gym_EventScript_Mary_Item::


            setvar VAR_TEMP_1, SPECIES_MEOWTH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_Clark_Item::


            setvar VAR_TEMP_1, SPECIES_GENGAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route132_EventScript_Darcy_Item::


            setvar VAR_TEMP_1, SPECIES_KRABBY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route126_EventScript_Nikki_Item::


            setvar VAR_TEMP_1, SPECIES_PARASECT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MauvilleCity_EventScript_Wattson_Item::


            setvar VAR_TEMP_1, SPECIES_TYPHLOSION
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

GraniteCave_B1F_EventScript_ItemPokeBall::
finditem ITEM_PROTECTIVE_PADS
return

Route124_EventScript_Declan_Item::


            setvar VAR_TEMP_1, SPECIES_FURRET
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle6_EventScript_Sophia_Item::


            setvar VAR_TEMP_1, SPECIES_MACHOKE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_ItemPPUp::
finditem ITEM_TM74
return

Route119_EventScript_Greg_Item::


            setvar VAR_TEMP_1, SPECIES_MAGMAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B2F_EventScript_Grunt8_Item::


            setvar VAR_TEMP_1, SPECIES_VULPIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PacifidlogTown_House2_EventScript_GiveReturn_Item::


            setvar VAR_TEMP_1, SPECIES_KAKUNA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

LavaridgeTown_Gym_1F_EventScript_Flannery_Item::


            setvar VAR_TEMP_1, SPECIES_POLIWHIRL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
finditem ITEM_AMPHAROSITE
return

Route115_EventScript_Marlene_Item::


            setvar VAR_TEMP_1, SPECIES_VENUSAUR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_WeatherInstitute_2F_EventScript_Grunt2_Item::


            setvar VAR_TEMP_1, SPECIES_NOCTOWL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SeafloorCavern_Room1_EventScript_Grunt1_Item::


            setvar VAR_TEMP_1, SPECIES_DIGLETT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_ItemElixir::
finditem ITEM_TM65
return

MauvilleCity_EventScript_ItemXSpeed::
finditem ITEM_POTION
return

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
finditem ITEM_BLUE_FLUTE
return

JaggedPass_EventScript_Diana_Item::


            setvar VAR_TEMP_1, SPECIES_SCIZOR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

ArtisanCave_1F_EventScript_ItemCarbos::
finditem ITEM_FLUFFY_TAIL
return

MagmaHideout_4F_EventScript_ItemMaxRevive::
finditem ITEM_GUARD_SPEC
return

MauvilleCity_Gym_EventScript_Shawn_Item::


            setvar VAR_TEMP_1, SPECIES_TEDDIURSA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B1F_EventScript_Electrode1_Item::
finditem ITEM_STARDUST
return

Route123_EventScript_Jacki_Item::


            setvar VAR_TEMP_1, SPECIES_MR_MIME
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route118_EventScript_Dalton_Item::


            setvar VAR_TEMP_1, SPECIES_HOUNDOOM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route130_EventScript_Santiago_Item::


            setvar VAR_TEMP_1, SPECIES_TOTODILE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

NavelRock_Top_EventScript_HoOh_ITEM::
finditem ITEM_ENIGMA_BERRY
return

RustboroCity_EventScript_ReturnGoods_Item::


            setvar VAR_TEMP_1, SPECIES_GASTLY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FallarborTown_CozmosHouse_EventScript_PlayerHasMeteorite_Item::


            setvar VAR_TEMP_1, SPECIES_MACHAMP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route125_EventScript_Tanya_Item::


            setvar VAR_TEMP_1, SPECIES_SNEASEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MEScrCmd_givepokemon::


            setvar VAR_TEMP_1, SPECIES_LARVITAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route134_EventScript_Kelvin_Item::


            setvar VAR_TEMP_1, SPECIES_ARTICUNO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SSTidalRooms_EventScript_Naomi_Item::


            setvar VAR_TEMP_1, SPECIES_GOLEM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
finditem ITEM_FIST_PLATE
return

Route109_EventScript_Lola_Item::


            setvar VAR_TEMP_1, SPECIES_VILEPLUME
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RustboroCity_Gym_EventScript_Josh_Item::


            setvar VAR_TEMP_1, SPECIES_MACHOP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SSTidalLowerDeck_EventScript_Phillip_Item::


            setvar VAR_TEMP_1, SPECIES_WEEPINBELL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_ItemRareCandy::
finditem ITEM_STEEL_MEMORY
return

Route113_EventScript_Lawrence_Item::


            setvar VAR_TEMP_1, SPECIES_DITTO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Branden_Item::


            setvar VAR_TEMP_1, SPECIES_KANGASKHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route112_EventScript_Bryant_Item::


            setvar VAR_TEMP_1, SPECIES_VICTREEBEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgCity_Gym_EventScript_Parker_Item::


            setvar VAR_TEMP_1, SPECIES_ARBOK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_Jazmyn_Item::


            setvar VAR_TEMP_1, SPECIES_RATICATE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Petalburg_Badge_Item::
finditem ITEM_POMEG_BERRY
 givemon SPECIES_KINGLER, 5
return

AbandonedShip_Rooms2_1F_EventScript_Garrison_Item::


            setvar VAR_TEMP_1, SPECIES_DUGTRIO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_WeatherInstitute_1F_EventScript_Grunt1_Item::


            setvar VAR_TEMP_1, SPECIES_ONIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Angelica_Item::


            setvar VAR_TEMP_1, SPECIES_SNEASEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_3F_2R_EventScript_Grunt10_Item::


            setvar VAR_TEMP_1, SPECIES_MR_MIME
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Kathleen_Item::


            setvar VAR_TEMP_1, SPECIES_GOLDUCK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle2_EventScript_Paul_Item::


            setvar VAR_TEMP_1, SPECIES_FARFETCHD
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route129_EventScript_Chase_Item::


            setvar VAR_TEMP_1, SPECIES_MEWTWO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RusturfTunnel_EventScript_ItemMaxEther::
finditem ITEM_WISE_GLASSES
return

Route119_EventScript_ItemSuperRepel::
finditem ITEM_EVIOLITE
return

Gabby_Ty_EventScript_3_Item::


            setvar VAR_TEMP_1, SPECIES_MOLTRES
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
finditem ITEM_WEPEAR_BERRY
return

Route107_EventScript_Darrin_Item::


            setvar VAR_TEMP_1, SPECIES_NINETALES
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VerdanturfTown_BattleTentLobby_EventScript_AttractGiver_Item::


            setvar VAR_TEMP_1, SPECIES_SPINARAK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MeteorFalls_1F_1R_EventScript_ItemPPUP::
finditem ITEM_RED_NECTAR
return

DesertUnderpass_EventScript_GiveClawFossil_Item::


            setvar VAR_TEMP_1, SPECIES_CHARIZARD
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route128_EventScript_Alexa_Item::


            setvar VAR_TEMP_1, SPECIES_FORRETRESS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Takashi_Item::


            setvar VAR_TEMP_1, SPECIES_CLOYSTER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_Edmond_Item::


            setvar VAR_TEMP_1, SPECIES_TANGELA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_WeatherInstitute_1F_EventScript_Grunt4_Item::


            setvar VAR_TEMP_1, SPECIES_POLIWAG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle6_Item::


            setvar VAR_TEMP_1, SPECIES_QWILFISH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B2F_EventScript_Dianne_Item::


            setvar VAR_TEMP_1, SPECIES_GLIGAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B1F_EventScript_Electrode2_Item::
finditem ITEM_SWEET_HEART
return

RusturfTunnel_EventScript_Mike_Item::


            setvar VAR_TEMP_1, SPECIES_ALAKAZAM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Rachel_Item::


            setvar VAR_TEMP_1, SPECIES_WEEZING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_ItemHyperPotion::
finditem ITEM_DREAM_MAIL
return

DewfordTown_EventScript_GiveOldRod_Item::


            setvar VAR_TEMP_1, SPECIES_ARCANINE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Brooke_Item::


            setvar VAR_TEMP_1, SPECIES_VULPIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle2_EventScript_Georgia_Item::


            setvar VAR_TEMP_1, SPECIES_ARCANINE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route132_EventScript_ItemProtein::
finditem ITEM_HEAT_ROCK
return

Route109_EventScript_Ricky_Item::


            setvar VAR_TEMP_1, SPECIES_VOLTORB
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route133_EventScript_ItemMaxRevive::
finditem ITEM_FULL_HEAL
return

Route104_EventScript_ItemPotion::
finditem ITEM_FIGHTING_GEM
return

Route117_EventScript_Dylan_Item::


            setvar VAR_TEMP_1, SPECIES_SEAKING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route132_EventScript_Paxton_Item::


            setvar VAR_TEMP_1, SPECIES_SNEASEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_6F_EventScript_Cedric_Item::


            setvar VAR_TEMP_1, SPECIES_SANDSHREW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_ItemHPUp::
finditem ITEM_HASTY_MINT
return

Route119_WeatherInstitute_2F_EventScript_ReceiveCastform_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNETON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_3F_EventScript_Kayla_Item::


            setvar VAR_TEMP_1, SPECIES_SNEASEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route131_EventScript_Kevin_Item::


            setvar VAR_TEMP_1, SPECIES_GIRAFARIG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route103_EventScript_ItemPPUp::
finditem ITEM_FULL_RESTORE
return

Route133_EventScript_Warren_Item::


            setvar VAR_TEMP_1, SPECIES_ELECTABUZZ
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Edward_Item::


            setvar VAR_TEMP_1, SPECIES_WARTORTLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route103_EventScript_Item_Rival::


            setvar VAR_TEMP_1, SPECIES_PERSIAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

DewfordTown_Gym_EventScript_Brawly_Item::


            setvar VAR_TEMP_1, SPECIES_KRABBY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_WeatherInstitute_2F_EventScript_Grunt5_Item::


            setvar VAR_TEMP_1, SPECIES_KINGLER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_Karen_Item::


            setvar VAR_TEMP_1, SPECIES_MAROWAK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_Rooms_1F_Eventscript_Thalia_Item::


            setvar VAR_TEMP_1, SPECIES_PUPITAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Jeffrey_Item::


            setvar VAR_TEMP_1, SPECIES_NOCTOWL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

NewMauville_Inside_EventScript_ItemParalyzeHeal::
finditem ITEM_TM13
return

Route110_EventScript_Abigail_Item::


            setvar VAR_TEMP_1, SPECIES_ZAPDOS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_Jaiden_Item::


            setvar VAR_TEMP_1, SPECIES_MAGBY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SeafloorCavern_Room3_EventScript_Shelly_Item::


            setvar VAR_TEMP_1, SPECIES_CYNDAQUIL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_Devan_Item::


            setvar VAR_TEMP_1, SPECIES_CLEFFA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Timmy_Item::


            setvar VAR_TEMP_1, SPECIES_GRANBULL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Becky_Item::


            setvar VAR_TEMP_1, SPECIES_HOUNDOUR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle7_EventScript_Alvaro_Item::


            setvar VAR_TEMP_1, SPECIES_VILEPLUME
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Bryan_Item::


            setvar VAR_TEMP_1, SPECIES_IVYSAUR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route121_EventScript_ItemRevive::
finditem ITEM_TM07
return

Route128_EventScript_Wayne_Item::


            setvar VAR_TEMP_1, SPECIES_HITMONCHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route126_EventScript_Brenda_Item::


            setvar VAR_TEMP_1, SPECIES_AZUMARILL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
finditem ITEM_DYNITE_ORE
return

Route110_EventScript_Edwin_Item::


            setvar VAR_TEMP_1, SPECIES_GYARADOS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route128_EventScript_Isaiah_Item::


            setvar VAR_TEMP_1, SPECIES_METAPOD
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_1F_EventScript_Edgar_Item::


            setvar VAR_TEMP_1, SPECIES_MOLTRES
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Preston_Item::


            setvar VAR_TEMP_1, SPECIES_VULPIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Chris_Item::


            setvar VAR_TEMP_1, SPECIES_AMPHAROS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route129_EventScript_Reed_Item::


            setvar VAR_TEMP_1, SPECIES_FERALIGATR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgWoods_EventScript_Lyle_Item::


            setvar VAR_TEMP_1, SPECIES_CUBONE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route124_EventScript_Isabella_Item::


            setvar VAR_TEMP_1, SPECIES_SUNKERN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_Lenny_Item::


            setvar VAR_TEMP_1, SPECIES_TENTACOOL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route121_EventScript_ItemZinc::
finditem ITEM_SUPER_POTION
return

MossdeepCity_StevensHouse_EventScript_GiveBeldum_Item::


            setvar VAR_TEMP_1, SPECIES_DODUO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_GiveFlyHM_Item::


            setvar VAR_TEMP_1, SPECIES_HITMONLEE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_Tori_Item::


            setvar VAR_TEMP_1, SPECIES_ODDISH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgWoods_EventScript_DevonResearcherLeft_Item::


            setvar VAR_TEMP_1, SPECIES_HOUNDOOM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B1F_EventScript_ItemTM29::
finditem ITEM_MAX_POTION
return

NewMauville_Inside_EventScript_ItemEscapeRope::
finditem ITEM_MAX_POTION
return

PetalburgCity_WallysHouse_EventScript_GiveHM03Surf_Item::


            setvar VAR_TEMP_1, SPECIES_CATERPIE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_ItemZinc::
finditem ITEM_BEEDRILLITE
return

SafariZone_Southeast_EventScript_ItemBigPearl::
finditem ITEM_FOSSILIZED_BIRD
return

Route116_EventScript_Janice_Item::


            setvar VAR_TEMP_1, SPECIES_SNUBBULL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Callie_Item::


            setvar VAR_TEMP_1, SPECIES_WIGGLYTUFF
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
finditem ITEM_ROCKIUM_Z
return

Route111_EventScript_ItemTM37::
finditem ITEM_RED_SCARF
return

PetalburgWoods_EventScript_ItemParalyzeHeal::


            setvar VAR_TEMP_1, SPECIES_DODUO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_ItemNugget::
finditem ITEM_RIBBON_SWEET
return

SeafloorCavern_Room9_EventScript_ArchieAwakenKyogre_Item::


            setvar VAR_TEMP_1, SPECIES_CROBAT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route102_EventScript_ItemPotion::
finditem ITEM_DYNAMAX_CANDY
return

Route119_EventScript_Brent_Item::


            setvar VAR_TEMP_1, SPECIES_GOLDUCK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle7_EventScript_Everett_Item::


            setvar VAR_TEMP_1, SPECIES_STARYU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route125_EventScript_Sharon_Item::


            setvar VAR_TEMP_1, SPECIES_CHARMELEON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route108_EventScript_Carolina_Item::


            setvar VAR_TEMP_1, SPECIES_ARIADOS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Mauville_Badge_Item::
finditem ITEM_MECH_MAIL
 givemon SPECIES_FURRET, 5
return

Route119_EventScript_Catherine_Item::


            setvar VAR_TEMP_1, SPECIES_RATTATA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

BirthIsland_Exterior_EventScript_Deoxys_Item::
finditem ITEM_ROOM_SERVICE
return

Route106_EventScript_Douglas_Item::


            setvar VAR_TEMP_1, SPECIES_SNORLAX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Wilton_Item::


            setvar VAR_TEMP_1, SPECIES_ZAPDOS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
finditem ITEM_CHESTO_BERRY
return

MauvilleCity_Gym_EventScript_Ben_Item::


            setvar VAR_TEMP_1, SPECIES_PERSIAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_1F_EventScript_Quincy_Item::


            setvar VAR_TEMP_1, SPECIES_DODRIO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route105_EventScript_Beverly_Item::


            setvar VAR_TEMP_1, SPECIES_SPEAROW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_House3_EventScript_SuperRodFisherman_Item::


            setvar VAR_TEMP_1, SPECIES_MEOWTH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RustboroCity_Gym_EventScript_Tommy_Item::


            setvar VAR_TEMP_1, SPECIES_KRABBY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route121_EventScript_Myles_Item::


            setvar VAR_TEMP_1, SPECIES_NIDORAN_M
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_GigaDrainGirl_Item::


            setvar VAR_TEMP_1, SPECIES_KANGASKHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_WinstrateFamilysHouse_EventScript_Vicky_Item::


            setvar VAR_TEMP_1, SPECIES_IGGLYBUFF
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_5F_EventScript_Atsushi_Item::


            setvar VAR_TEMP_1, SPECIES_CROCONAW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_2F_2R_EventScript_Grunt8_Item::


            setvar VAR_TEMP_1, SPECIES_VICTREEBEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route117_EventScript_Melina_Item::


            setvar VAR_TEMP_1, SPECIES_SLOWKING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_TateAndLiza_Item::


            setvar VAR_TEMP_1, SPECIES_HAUNTER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

LavaridgeTown_Gym_1F_EventScript_Axle_Item::


            setvar VAR_TEMP_1, SPECIES_ZAPDOS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_Ed_Item::


            setvar VAR_TEMP_1, SPECIES_ARTICUNO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route125_EventScript_Nolen_Item::


            setvar VAR_TEMP_1, SPECIES_CHARMANDER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route108_EventScript_ItemStarPiece::
finditem ITEM_FULL_HEAL
return

LavaridgeTown_Gym_B1F_EventScript_Keegan_Item::


            setvar VAR_TEMP_1, SPECIES_MACHOKE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B2F_EventScript_Julie_Item::


            setvar VAR_TEMP_1, SPECIES_PIDGEY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SlateportCity_Harbor_EventScript_DeepSeaTooth_Item::


            setvar VAR_TEMP_1, SPECIES_MANKEY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Jenna_Item::


            setvar VAR_TEMP_1, SPECIES_CLOYSTER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

DesertUnderpass_EventScript_GiveRootFossil_Item::


            setvar VAR_TEMP_1, SPECIES_NIDOQUEEN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_3F_EventScript_William_Item::


            setvar VAR_TEMP_1, SPECIES_GRIMER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RusturfTunnel_EventScript_ItemPokeBall::
finditem ITEM_LAX_INCENSE
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle2_Item::


            setvar VAR_TEMP_1, SPECIES_VENUSAUR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
finditem ITEM_IRON_BALL
return

VictoryRoad_B1F_EventScript_Shannon_Item::


            setvar VAR_TEMP_1, SPECIES_VICTREEBEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route105_EventScript_ItemIron::
finditem ITEM_SHALOUR_SABLE
return

Route123_EventScript_Davis_Item::


            setvar VAR_TEMP_1, SPECIES_SHELLDER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_3F_EventScript_Gabrielle_Item::


            setvar VAR_TEMP_1, SPECIES_SMOOCHUM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

GraniteCave_1F_EventScript_Hiker_Item::


            setvar VAR_TEMP_1, SPECIES_WEEPINBELL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_StevenGiveDeconScope_ITEM::


            setvar VAR_TEMP_1, SPECIES_ALAKAZAM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle3_EventScript_Martha_Item::


            setvar VAR_TEMP_1, SPECIES_OMASTAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
finditem ITEM_CAREFUL_MINT
return

Route110_TrickHousePuzzle7_EventScript_Joshua_Item::


            setvar VAR_TEMP_1, SPECIES_NIDOKING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MarineCave_End_EventScript_Kyogre_Item::
finditem ITEM_GROWTH_MULCH
return

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
finditem ITEM_TOXIC_ORB
return

AbandonedShip_Corridors_1F_EventScript_Charlie_Item::


            setvar VAR_TEMP_1, SPECIES_SHELLDER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_Summit_EventScript_Grunt4_Item::


            setvar VAR_TEMP_1, SPECIES_TAUROS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_Dillon_Item::


            setvar VAR_TEMP_1, SPECIES_TOGEPI
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route117_EventScript_Isaac_Item::


            setvar VAR_TEMP_1, SPECIES_TOGEPI
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_Alberto_Item::


            setvar VAR_TEMP_1, SPECIES_ODDISH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_Joey_Item::


            setvar VAR_TEMP_1, SPECIES_KAKUNA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route108_EventScript_Jerome_Item::


            setvar VAR_TEMP_1, SPECIES_ELECTRODE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_1F_EventScript_Albert_Item::


            setvar VAR_TEMP_1, SPECIES_SMOOCHUM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route112_EventScript_Carol_Item::


            setvar VAR_TEMP_1, SPECIES_HOPPIP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RustboroCity_EventScript_ItemXDefend::
finditem ITEM_POKE_TOY
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle4_Item::


            setvar VAR_TEMP_1, SPECIES_GIRAFARIG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SlateportCity_EventScript_BerryPowderClerk_Item::


            setvar VAR_TEMP_1, SPECIES_SNORLAX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route118_EventScript_ItemHyperPotion::
finditem ITEM_JOLLY_MINT
return

SootopolisCity_LotadAndSeedotHouse_EventScript_BigSeedot_Item::


            setvar VAR_TEMP_1, SPECIES_STEELIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Celina_Item::


            setvar VAR_TEMP_1, SPECIES_JOLTEON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route112_EventScript_Larry_Item::


            setvar VAR_TEMP_1, SPECIES_PARAS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_WinstrateFamilysHouse_EventScript_Victoria_Item::


            setvar VAR_TEMP_1, SPECIES_POLITOED
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route133_EventScript_Linda_Item::


            setvar VAR_TEMP_1, SPECIES_MR_MIME
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle8_EventScript_Leroy_Item::


            setvar VAR_TEMP_1, SPECIES_GRAVELER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route134_EventScript_Reyna_Item::


            setvar VAR_TEMP_1, SPECIES_SKARMORY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route126_EventScript_Dean_Item::


            setvar VAR_TEMP_1, SPECIES_QUAGSIRE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route118_EventScript_Chester_Item::


            setvar VAR_TEMP_1, SPECIES_GENGAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_ItemLeafStone::
finditem ITEM_SACRED_ASH
return

RustboroCity_DevonCorp_3F_EventScript_GiveExpShare_Item::


            setvar VAR_TEMP_1, SPECIES_DITTO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SlateportCity_PokemonFanClub_EventScript_GiveYellowScarf_Item::


            setvar VAR_TEMP_1, SPECIES_QWILFISH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B1F_EventScript_Grunt5_Item::


            setvar VAR_TEMP_1, SPECIES_TANGELA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_1F_EventScript_Grunt2_Item::


            setvar VAR_TEMP_1, SPECIES_MAROWAK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route130_EventScript_Rodney_Item::


            setvar VAR_TEMP_1, SPECIES_VILEPLUME
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_ItemCalcium::
finditem ITEM_REVIVE
return

LavaridgeTown_Gym_B1F_EventScript_Eli_Item::


            setvar VAR_TEMP_1, SPECIES_SUICUNE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_Jose_Item::


            setvar VAR_TEMP_1, SPECIES_FARFETCHD
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MauvilleCity_EventScript_DefeatedWally_Item::


            setvar VAR_TEMP_1, SPECIES_PERSIAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route134_EventScript_Marley_Item::


            setvar VAR_TEMP_1, SPECIES_BUTTERFREE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

NewMauville_Inside_EventScript_Voltorb1_Item::
finditem ITEM_MAX_ETHER
return

MossdeepCity_Gym_EventScript_Macey_Item::


            setvar VAR_TEMP_1, SPECIES_PIDGEY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_3F_1R_EventScript_ItemNugget::
finditem ITEM_TM32
return

SSTidalRooms_EventScript_Colton_Item::


            setvar VAR_TEMP_1, SPECIES_WEEZING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route130_EventScript_Katie_Item::


            setvar VAR_TEMP_1, SPECIES_AIPOM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
finditem ITEM_BLACK_SLUDGE
return

Route119_EventScript_ItemHyperPotion2::
finditem ITEM_BERRY_JUICE
return

Route113_GlassWorkshop_EventScript_GlassWorker_Item::


            setvar VAR_TEMP_1, SPECIES_PORYGON2
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MauvilleCity_Gym_EventScript_Angelo_Item::


            setvar VAR_TEMP_1, SPECIES_ABRA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_B2F_EventScript_ItemFullHeal::
finditem ITEM_TM15
return

Route121_EventScript_ItemCarbos::
finditem ITEM_TM48
return

VictoryRoad_B1F_EventScript_Michelle_Item::


            setvar VAR_TEMP_1, SPECIES_DODRIO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Fortree_Badge_Item::
finditem ITEM_ELECTRIC_GEM
 givemon SPECIES_JIGGLYPUFF, 5
return

Route109_EventScript_Alice_Item::


            setvar VAR_TEMP_1, SPECIES_MAGCARGO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MeteorFalls_1F_1R_EventScript_ItemTM23::
finditem ITEM_CHOICE_BAND
return

Route121_EventScript_Vanessa_Item::


            setvar VAR_TEMP_1, SPECIES_QWILFISH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route117_EventScript_Lydia_Item::


            setvar VAR_TEMP_1, SPECIES_QUILAVA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_ItemNestBall::
finditem ITEM_RELAXED_MINT
return

MagmaHideout_2F_2R_EventScript_Grunt7_Item::


            setvar VAR_TEMP_1, SPECIES_GASTLY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_WeatherInstitute_2F_EventScript_Shelly_Item::


            setvar VAR_TEMP_1, SPECIES_DONPHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SSTidalRooms_EventScript_Garret_Item::


            setvar VAR_TEMP_1, SPECIES_DRATINI
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route105_EventScript_Josue_Item::


            setvar VAR_TEMP_1, SPECIES_GROWLITHE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FortreeCity_Gym_EventScript_Flint_Item::


            setvar VAR_TEMP_1, SPECIES_FERALIGATR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route132_EventScript_ItemRareCandy::
finditem ITEM_TM44
return

Route116_EventScript_ItemRepel::
finditem ITEM_ABILITY_PATCH
return

Route114_EventScript_Tyra_Item::


            setvar VAR_TEMP_1, SPECIES_SUICUNE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route132_EventScript_Kiyo_Item::


            setvar VAR_TEMP_1, SPECIES_NIDORINO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

GraniteCave_1F_EventScript_ItemEscapeRope::
finditem ITEM_REVIVE
return

Drake_Item::


            setvar VAR_TEMP_1, SPECIES_NIDORAN_M
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_Carter_Item::


            setvar VAR_TEMP_1, SPECIES_MACHOKE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route125_EventScript_Ernest_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNEMITE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RustboroCity_Gym_EventScript_Roxanne_Item::


            setvar VAR_TEMP_1, SPECIES_SLOWKING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route123_EventScript_Miu_Item::


            setvar VAR_TEMP_1, SPECIES_PIDGEOTTO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

LavaridgeTown_Gym_1F_EventScript_Cole_Item::


            setvar VAR_TEMP_1, SPECIES_PARAS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route132_EventScript_Makayla_Item::


            setvar VAR_TEMP_1, SPECIES_WEEPINBELL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route121_EventScript_Pat_Item::


            setvar VAR_TEMP_1, SPECIES_NIDOKING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_Gym_B1F_EventScript_Brianna_Item::


            setvar VAR_TEMP_1, SPECIES_CLEFABLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route118_EventScript_Perry_Item::


            setvar VAR_TEMP_1, SPECIES_SMEARGLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_SeashoreHouse_EventScript_Johanna_Item::


            setvar VAR_TEMP_1, SPECIES_CROBAT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_ItemRareCandy::
finditem ITEM_SCOPE_LENS
return

VictoryRoad_1F_EventScript_WallyEntranceBattle_Item::


            setvar VAR_TEMP_1, SPECIES_VAPOREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_Austina_Item::


            setvar VAR_TEMP_1, SPECIES_GYARADOS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route104_EventScript_Boy2_Item::


            setvar VAR_TEMP_1, SPECIES_PHANPY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route108_EventScript_Cory_Item::


            setvar VAR_TEMP_1, SPECIES_ARBOK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

JaggedPass_EventScript_Autumn_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNETON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route128_EventScript_Ruben_Item::


            setvar VAR_TEMP_1, SPECIES_PARAS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_Chandler_Item::


            setvar VAR_TEMP_1, SPECIES_DODUO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_ItemElixir::
finditem ITEM_RELIC_COPPER
return

Route115_EventScript_ItemPPUp::
finditem ITEM_MUSCLE_BAND
return

Route111_EventScript_Hayden_Item::


            setvar VAR_TEMP_1, SPECIES_DUGTRIO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Clarissa_Item::


            setvar VAR_TEMP_1, SPECIES_TYROGUE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route112_EventScript_Shayla_Item::


            setvar VAR_TEMP_1, SPECIES_TOGEPI
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route121_EventScript_Jessica_Item::


            setvar VAR_TEMP_1, SPECIES_HOPPIP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_SeashoreHouse_EventScript_Simon_Item::


            setvar VAR_TEMP_1, SPECIES_SUNFLORA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route112_EventScript_Brice_Item::


            setvar VAR_TEMP_1, SPECIES_CROCONAW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Heidi_Item::


            setvar VAR_TEMP_1, SPECIES_GROWLITHE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Benjamin_Item::


            setvar VAR_TEMP_1, SPECIES_GRAVELER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_Wyatt_Item::


            setvar VAR_TEMP_1, SPECIES_SMOOCHUM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route126_EventScript_Sienna_Item::


            setvar VAR_TEMP_1, SPECIES_SUDOWOODO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SlateportCity_PokemonFanClub_EventScript_GiveGreenScarf_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNEMITE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_Lao_Item::


            setvar VAR_TEMP_1, SPECIES_SWINUB
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B2F_EventScript_Matt_Item::


            setvar VAR_TEMP_1, SPECIES_MARILL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route105_EventScript_Imani_Item::


            setvar VAR_TEMP_1, SPECIES_PUPITAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_ItemStardust::
finditem ITEM_PINK_SCARF
return

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
finditem ITEM_ANTIDOTE
return

Route119_EventScript_Dayton_Item::


            setvar VAR_TEMP_1, SPECIES_CORSOLA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle1_EventScript_Sally_Item::


            setvar VAR_TEMP_1, SPECIES_ELECTABUZZ
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

DewfordTown_Gym_EventScript_Jocelyn_Item::


            setvar VAR_TEMP_1, SPECIES_KANGASKHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SeafloorCavern_Room9_EventScript_ItemTM26::
finditem ITEM_TM02
return

Route134_EventScript_Jack_Item::


            setvar VAR_TEMP_1, SPECIES_OMANYTE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B2F_EventScript_Grunt6_Item::


            setvar VAR_TEMP_1, SPECIES_HORSEA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_4F_EventScript_Grunt13_Item::


            setvar VAR_TEMP_1, SPECIES_PIDGEOTTO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B1F_EventScript_ItemMaxElixir::
finditem ITEM_ESCAPE_ROPE
return

Route121_EventScript_Tammy_Item::


            setvar VAR_TEMP_1, SPECIES_YANMA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_ItemPotion::
finditem ITEM_HYPER_POTION
return

MagmaHideout_4F_EventScript_Tabitha_Item::


            setvar VAR_TEMP_1, SPECIES_TOGETIC
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_2F_1R_EventScript_Grunt5_Item::


            setvar VAR_TEMP_1, SPECIES_QUAGSIRE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle6_EventScript_Sebastian_Item::


            setvar VAR_TEMP_1, SPECIES_MACHOKE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MeteorFalls_B1F_2R_EventScript_ItemTM02::
finditem ITEM_MODEST_MINT
return

Route102_EventScript_Allen_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNETON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route113_EventScript_Coby_Item::


            setvar VAR_TEMP_1, SPECIES_PONYTA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FieryPath_EventScript_ItemFireStone::
finditem ITEM_DAMP_MULCH
return

Route106_EventScript_Ned_Item::


            setvar VAR_TEMP_1, SPECIES_UMBREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SeafloorCavern_Room1_EventScript_Grunt2_Item::


            setvar VAR_TEMP_1, SPECIES_MARILL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_Gym_B1F_EventScript_Annika_Item::


            setvar VAR_TEMP_1, SPECIES_WIGGLYTUFF
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route107_EventScript_Lisa_Item::


            setvar VAR_TEMP_1, SPECIES_CHARIZARD
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route119_EventScript_Taylor_Item::


            setvar VAR_TEMP_1, SPECIES_ZUBAT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_Gym_1F_EventScript_Juan_Item::


            setvar VAR_TEMP_1, SPECIES_GEODUDE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MeteorFalls_1F_2R_EventScript_John_Item::


            setvar VAR_TEMP_1, SPECIES_RAPIDASH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle7_EventScript_Patricia_Item::


            setvar VAR_TEMP_1, SPECIES_BUTTERFREE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Virgil_Item::


            setvar VAR_TEMP_1, SPECIES_FURRET
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route102_EventScript_Tiana_Item::


            setvar VAR_TEMP_1, SPECIES_CHINCHOU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

NewMauville_Inside_EventScript_Voltorb3_Item::
finditem ITEM_TM95
return

Route109_EventScript_Gwen_Item::


            setvar VAR_TEMP_1, SPECIES_RHYDON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle1_EventScript_Robin_Item::


            setvar VAR_TEMP_1, SPECIES_IGGLYBUFF
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route108_EventScript_Tara_Item::


            setvar VAR_TEMP_1, SPECIES_WARTORTLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle6_EventScript_Benny_Item::


            setvar VAR_TEMP_1, SPECIES_PUPITAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_Claude_Item::


            setvar VAR_TEMP_1, SPECIES_CHARMANDER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route109_EventScript_David_Item::


            setvar VAR_TEMP_1, SPECIES_MUK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

RustboroCity_CuttersHouse_EventScript_Cutter_Item::


            setvar VAR_TEMP_1, SPECIES_MACHAMP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle8_EventScript_Keira_Item::


            setvar VAR_TEMP_1, SPECIES_SCYTHER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route134_EventScript_Alex_Item::


            setvar VAR_TEMP_1, SPECIES_FORRETRESS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
finditem ITEM_TINY_MUSHROOM
return

VictoryRoad_1F_EventScript_Hope_Item::


            setvar VAR_TEMP_1, SPECIES_GROWLITHE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_Dawson_Item::


            setvar VAR_TEMP_1, SPECIES_BELLOSSOM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SeafloorCavern_Room4_EventScript_Grunt3_Item::


            setvar VAR_TEMP_1, SPECIES_KABUTO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Nate_Item::


            setvar VAR_TEMP_1, SPECIES_PERSIAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

ArtisanCave_B1F_EventScript_ItemHPUp::
finditem ITEM_ALTARIANITE
return

Route124_EventScript_Roland_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNEMITE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route129_EventScript_Tisha_Item::


            setvar VAR_TEMP_1, SPECIES_VICTREEBEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route121_EventScript_Cristin_Item::


            setvar VAR_TEMP_1, SPECIES_LARVITAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle3_Item::


            setvar VAR_TEMP_1, SPECIES_SANDSHREW
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FortreeCity_House4_EventScript_WingullReturned_Item::


            setvar VAR_TEMP_1, SPECIES_MAGNETON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route126_EventScript_Barry_Item::


            setvar VAR_TEMP_1, SPECIES_REMORAID
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Beau_Item::


            setvar VAR_TEMP_1, SPECIES_RHYDON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SlateportCity_PokemonFanClub_EventScript_GiveRedScarf_Item::


            setvar VAR_TEMP_1, SPECIES_KAKUNA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle7_EventScript_Mariela_Item::


            setvar VAR_TEMP_1, SPECIES_CHARMELEON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route128_EventScript_Katelyn_Item::


            setvar VAR_TEMP_1, SPECIES_TYPHLOSION
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route114_EventScript_ItemProtein::
finditem ITEM_PERSIM_BERRY
return

RusturfTunnel_EventScript_ClearTunnelScene_ITEM::


            setvar VAR_TEMP_1, SPECIES_CLOYSTER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FortreeCity_Gym_EventScript_Jared_Item::


            setvar VAR_TEMP_1, SPECIES_PONYTA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

LavaridgeTown_Gym_1F_EventScript_Danielle_Item::


            setvar VAR_TEMP_1, SPECIES_UMBREON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MossdeepCity_Gym_EventScript_Blake_Item::


            setvar VAR_TEMP_1, SPECIES_JUMPLUFF
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MtPyre_Summit_EventScript_Grunt3_Item::


            setvar VAR_TEMP_1, SPECIES_BEEDRILL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route107_EventScript_Denise_Item::


            setvar VAR_TEMP_1, SPECIES_PIDGEOT
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle1_EventScript_Eddie_Item::


            setvar VAR_TEMP_1, SPECIES_GLOOM
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SlateportCity_PokemonFanClub_EventScript_GiveSootheBell_Item::


            setvar VAR_TEMP_1, SPECIES_SCIZOR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Daisuke_Item::


            setvar VAR_TEMP_1, SPECIES_VENOMOTH
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route117_EventScript_Brandi_Item::


            setvar VAR_TEMP_1, SPECIES_SLOWPOKE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgCity_EventScript_ItemMaxRevive::
finditem ITEM_HONDEW_BERRY
return

PetalburgCity_Gym_EventScript_NormanBattle_Item::


            setvar VAR_TEMP_1, SPECIES_OCTILLERY
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route131_EventScript_Kara_Item::


            setvar VAR_TEMP_1, SPECIES_SNUBBULL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

GraniteCave_B2F_EventScript_ItemRareCandy::
finditem ITEM_ALAKAZITE
return

MtPyre_2F_EventScript_Mark_Item::


            setvar VAR_TEMP_1, SPECIES_TAUROS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle7_EventScript_Alexis_Item::


            setvar VAR_TEMP_1, SPECIES_SEEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Jennifer_Item::


            setvar VAR_TEMP_1, SPECIES_GRAVELER
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle4_EventScript_Yuji_Item::


            setvar VAR_TEMP_1, SPECIES_CHARIZARD
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

LavaridgeTown_EventScript_MayGiveGoGoggles_ITEM::


            setvar VAR_TEMP_1, SPECIES_ZAPDOS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

SootopolisCity_Gym_B1F_EventScript_Bridget_Item::


            setvar VAR_TEMP_1, SPECIES_GYARADOS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route106_EventScript_Elliot_Item::


            setvar VAR_TEMP_1, SPECIES_TENTACRUEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route115_EventScript_ItemIron::
finditem ITEM_REVIVAL_HERB
return

Route114_EventScript_Shane_Item::


            setvar VAR_TEMP_1, SPECIES_SPINARAK
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_GiveRepeatBall_Item::
finditem ITEM_HELIX_FOSSIL
return

LilycoveCity_House2_EventScript_FatMan_Item::


            setvar VAR_TEMP_1, SPECIES_GEODUDE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_3F_1R_EventScript_Grunt9_Item::


            setvar VAR_TEMP_1, SPECIES_HYPNO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route120_EventScript_Leonel_Item::


            setvar VAR_TEMP_1, SPECIES_POLITOED
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

VictoryRoad_1F_EventScript_ItemPPUp::
finditem ITEM_GENTLE_MINT
return

Route134_EventScript_ItemCarbos::
finditem ITEM_TM28
return

DewfordTown_Gym_EventScript_Brenden_Item::


            setvar VAR_TEMP_1, SPECIES_KANGASKHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

LavaridgeTown_HerbShop_EventScript_OldMan_Item::


            setvar VAR_TEMP_1, SPECIES_METAPOD
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MeteorFalls_StevensCave_EventScript_Steven_Item::


            setvar VAR_TEMP_1, SPECIES_LANTURN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route118_EventScript_Barny_Item::


            setvar VAR_TEMP_1, SPECIES_MACHAMP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

FortreeCity_Gym_EventScript_Ashley_Item::


            setvar VAR_TEMP_1, SPECIES_HERACROSS
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_1F_EventScript_Grunt1_Item::


            setvar VAR_TEMP_1, SPECIES_TYPHLOSION
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route112_EventScript_ItemNugget::
finditem ITEM_BUG_GEM
return

DewfordTown_Gym_EventScript_Lilith_Item::


            setvar VAR_TEMP_1, SPECIES_KADABRA
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route106_EventScript_Kyla_Item::


            setvar VAR_TEMP_1, SPECIES_DITTO
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route121_EventScript_Walter_Item::


            setvar VAR_TEMP_1, SPECIES_DRAGONAIR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route111_EventScript_Dusty_Item::


            setvar VAR_TEMP_1, SPECIES_CLEFABLE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_TrickHousePuzzle8_EventScript_Vincent_Item::


            setvar VAR_TEMP_1, SPECIES_VICTREEBEL
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route126_EventScript_Isobel_Item::


            setvar VAR_TEMP_1, SPECIES_SEAKING
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_ItemEther::
finditem ITEM_SCIZORITE
return

MtPyre_2F_EventScript_Leah_Item::


            setvar VAR_TEMP_1, SPECIES_RHYHORN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route129_EventScript_Clarence_Item::


            setvar VAR_TEMP_1, SPECIES_PIKACHU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route117_EventScript_ItemGreatBall::
finditem ITEM_AMULET_COIN
return

Route115_EventScript_Hector_Item::


            setvar VAR_TEMP_1, SPECIES_PORYGON
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route116_EventScript_Sarah_Item::


            setvar VAR_TEMP_1, SPECIES_MACHOKE
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

PetalburgCity_EventScript_ItemEther::
finditem ITEM_HARBOR_MAIL
return

AquaHideout_B1F_EventScript_ItemNugget::
finditem ITEM_FRESH_WATER
return

Route111_EventScript_Celia_Item::


            setvar VAR_TEMP_1, SPECIES_MAREEP
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

MagmaHideout_3F_1R_EventScript_Grunt16_Item::


            setvar VAR_TEMP_1, SPECIES_DONPHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Route110_EventScript_Anthony_Item::


            setvar VAR_TEMP_1, SPECIES_PIKACHU
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

JaggedPass_EventScript_Julio_Item::


            setvar VAR_TEMP_1, SPECIES_VULPIX
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AncientTomb_EventScript_Registeel_Item::
finditem ITEM_ENERGY_ROOT
return

Route112_EventScript_Trent_Item::


            setvar VAR_TEMP_1, SPECIES_TYRANITAR
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Mosdeep_Badge_Item::
finditem ITEM_SASSY_MINT
 givemon SPECIES_HYPNO, 5
return

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
finditem ITEM_ABOMASITE
return

LavaridgeTown_EventScript_EggWoman_Item::


            setvar VAR_TEMP_1, SPECIES_KANGASKHAN
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

AquaHideout_B2F_EventScript_Grunt4_Item::


            setvar VAR_TEMP_1, SPECIES_DEWGONG
           setvar VAR_TEMP_2, 5
           call Get_Pokemon
return

Sootopolis_Badge_Item::
finditem ITEM_POTION
 givemon SPECIES_UNOWN, 5
return


trainer_items::
    switch VAR_TRAINER_BATTLE_OPPONENT_A

  case TRAINER_FERNANDO_1, Route123_EventScript_Fernando_Item
  case TRAINER_GABBY_AND_TY_1, Gabby_Ty_EventScript_1_Item
  case TRAINER_TIFFANY, SootopolisCity_Gym_B1F_EventScript_Tiffany_Item
  case TRAINER_DEANDRE, Route118_EventScript_Deandre_Item
  case TRAINER_ANNA_AND_MEG_1, Route117_EventScript_Anna_Item
  case TRAINER_NANCY, Route114_EventScript_Nancy_Item
  case TRAINER_NICOLAS_1, MeteorFalls_1F_2R_EventScript_Nicolas_Item
  case TRAINER_KIRA_AND_DAN_1, AbandonedShip_Rooms2_1F_EventScript_Kira_Item
  case TRAINER_PRESLEY, Route125_EventScript_Presley_Item
  case TRAINER_PABLO_1, Route126_EventScript_Pablo_Item
  case TRAINER_JONATHAN, Route132_EventScript_Jonathan_Item
  case TRAINER_RANDALL, PetalburgCity_Gym_EventScript_Randall_Item
  case TRAINER_LUIS, Route105_EventScript_Luis_Item
  case TRAINER_ETHAN_1, JaggedPass_EventScript_Ethan_Item
  case TRAINER_KEIGO, Route120_EventScript_Keigo_Item
  case TRAINER_GRUNT_RUSTURF_TUNNEL, RusturfTunnel_EventScript_Grunt_Item_Two
  case TRAINER_CALE, Route121_EventScript_Cale_Item
  case TRAINER_OLIVIA, SootopolisCity_Gym_B1F_EventScript_Olivia_Item
  case TRAINER_ROBERT_1, Route120_EventScript_Robert_Item
  case TRAINER_CAMRON, Route107_EventScript_Camron_Item
  case TRAINER_LUCAS_1, Route114_EventScript_Lucas_Item
  case TRAINER_VICTOR, Route111_EventScript_Victor_Item
  case TRAINER_ZANDER, MtPyre_2F_EventScript_Zander_Item
  case TRAINER_ALEXIA, PetalburgCity_Gym_EventScript_Alexia_Item
  case TRAINER_HARRISON, Route128_EventScript_Harrison_Item
  case TRAINER_ERIC, JaggedPass_EventScript_Eric_Item
  case TRAINER_BIANCA, Route111_EventScript_Bianca_Item
  case TRAINER_WADE, Route118_EventScript_Wade_Item
  case TRAINER_ISABEL_1, Route110_EventScript_Isabel_Item
  case TRAINER_JOSEPH, Route110_EventScript_Joseph_Item
  case TRAINER_RICK, Route102_EventScript_Rick_Item
  case TRAINER_GEORGE, PetalburgCity_Gym_EventScript_George_Item
  case TRAINER_KENT, Route119_EventScript_Kent_Item
  case TRAINER_GABBY_AND_TY_2, Gabby_Ty_EventScript_2_Item
  case TRAINER_LAUREL, Route134_EventScript_Laurel_Item
  case TRAINER_ANDREA, SootopolisCity_Gym_B1F_EventScript_Andrea_Item
  case TRAINER_FABIAN, Route119_EventScript_Fabian_Item
  case TRAINER_NOB_1, Route115_EventScript_Nob_Item
  case TRAINER_MARIA_1, Route117_EventScript_Maria_Item
  case TRAINER_CHARLOTTE, Route114_EventScript_Charlotte_Item
  case TRAINER_PAULA, Route110_TrickHousePuzzle4_EventScript_Paula_Item
  case TRAINER_HIDEO, Route119_EventScript_Hideo_Item
  case TRAINER_MADELINE_1, Route113_EventScript_Madeline_Item
  case TRAINER_LILA_AND_ROY_1, Route124_EventScript_Lila_Item
  case TRAINER_JODY, PetalburgCity_Gym_EventScript_Jody_Item
  case TRAINER_CRISSY, SootopolisCity_Gym_B1F_EventScript_Crissy_Item
  case TRAINER_RICHARD, Route131_EventScript_Richard_Item
  case TRAINER_HUGH, Route119_EventScript_Hugh_Item
  case TRAINER_ANDRES_1, Route105_EventScript_Andres_Item
  case TRAINER_MAY_ROUTE_119_MUDKIP, Route119_EventScript_RivalExitScottArrive_Item
  case TRAINER_JERRY_1, Route116_EventScript_Jerry_Item
  case TRAINER_MICAH, SSTidalRooms_EventScript_Micah_Item
  case TRAINER_CONOR, Route133_EventScript_Conor_Item
  case TRAINER_HUMBERTO, FortreeCity_Gym_EventScript_Humberto_Item
  case TRAINER_SUSIE, Route131_EventScript_Susie_Item
  case TRAINER_JACKSON_1, Route119_EventScript_Jackson_Item
  case TRAINER_VITO, VictoryRoad_B2F_EventScript_Vito_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_7, AquaHideout_B1F_EventScript_Grunt7_Item
  case TRAINER_CRISTIAN, DewfordTown_Gym_EventScript_Cristian_Item
  case TRAINER_DUNCAN, AbandonedShip_Corridors_B1F_EventScript_Duncan_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_4, SeafloorCavern_Room4_EventScript_Grunt4_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_1, MagmaHideout_1F_EventScript_Grunt1_Item
  case TRAINER_OWEN, VictoryRoad_B2F_EventScript_Owen_Item
  case TRAINER_SAMUEL, VictoryRoad_B1F_EventScript_Samuel_Item
  case TRAINER_CHAD, Route124_EventScript_Chad_Item
  case TRAINER_BETH, Route107_EventScript_Beth_Item
  case TRAINER_MAY_LILYCOVE_MUDKIP, LilycoveCity_EventScript_Rival_Item
  case TRAINER_TIMOTHY_1, Route115_EventScript_Timothy_Item
  case TRAINER_KIM_AND_IRIS, Route125_EventScript_Kim_Item
  case TRAINER_YASU, Route119_EventScript_Yasu_Item
  case TRAINER_TALIA, Route131_EventScript_Talia_Item
  case TRAINER_LAURA, DewfordTown_Gym_EventScript_Laura_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_6, MagmaHideout_2F_2R_EventScript_Grunt6_Item
  case TRAINER_BERNIE_1, Route114_EventScript_Bernie_Item
  case TRAINER_MATTHEW, Route108_EventScript_Matthew_Item
  case TRAINER_DEREK, Route117_EventScript_Derek_Item
  case TRAINER_FELIX, VictoryRoad_B2F_EventScript_Felix_Item
  case TRAINER_GILBERT, Route132_EventScript_Gilbert_Item
  case TRAINER_FREDRICK, Route123_EventScript_Frederick_Item
  case TRAINER_THOMAS, SSTidalRooms_EventScript_Thomas_Item
  case TRAINER_PHIL, Route119_EventScript_Phil_Item
  case TRAINER_MARC, RustboroCity_Gym_EventScript_Marc_Item
  case TRAINER_IRENE, Route111_EventScript_Irene_Item
  case TRAINER_GRACE, Route124_EventScript_Grace_Item
  case TRAINER_JACLYN, Route110_EventScript_Jaclyn_Item
  case TRAINER_HAILEY, Route109_EventScript_Hailey_Item
  case TRAINER_TASHA, MtPyre_4F_EventScript_Tasha_Item
  case TRAINER_VIOLET, Route123_EventScript_Violet_Item
  case TRAINER_COLIN, Route120_EventScript_Colin_Item
  case TRAINER_TYRON, Route111_EventScript_Tyron_Item
  case TRAINER_JUSTIN, Route110_TrickHousePuzzle3_EventScript_Justin_Item
  case TRAINER_KAI, Route114_EventScript_Kai_Item
  case TRAINER_WATTSON_1, MauvilleCity_Gym_EventScript_Wattson_Item
  case TRAINER_MAXIE_MAGMA_HIDEOUT, MagmaHideout_4F_EventScript_Maxie_Item
  case TRAINER_HITOSHI, Route134_EventScript_Hitoshi_Item
  case TRAINER_JAMES_1, PetalburgWoods_EventScript_James_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_12, MagmaHideout_4F_EventScript_Grunt12_Item
  case TRAINER_CORA, Route110_TrickHousePuzzle4_EventScript_Cora_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_14, MagmaHideout_2F_1R_EventScript_Grunt14_Item
  case TRAINER_LEONARDO, Route126_EventScript_Leonardo_Item
  case TRAINER_ALLISON, Route129_EventScript_Allison_Item
  case TRAINER_JENNY_1, Route124_EventScript_Jenny_Item
  case TRAINER_AURON, Route125_EventScript_Auron_Item
  case TRAINER_CLIFFORD, MossdeepCity_Gym_EventScript_Clifford_Item
  case TRAINER_DEMETRIUS, AbandonedShip_Rooms_1F_EventScript_Demetrius_Item
  case TRAINER_HUEY, Route109_EventScript_Huey_Item
  case TRAINER_HALLE, VictoryRoad_B1F_EventScript_Halle_Item
  case TRAINER_BECK, Route133_EventScript_Beck_Item
  case TRAINER_FOSTER, Route105_EventScript_Foster_Item
  case TRAINER_BRAXTON, Route123_EventScript_Braxton_Item
  case TRAINER_JANI, AbandonedShip_Rooms2_1F_EventScript_Jani_Item
  case TRAINER_KINDRA, Route123_EventScript_Kindra_Item
  case TRAINER_GRUNT_MT_PYRE_2, MtPyre_Summit_EventScript_Grunt2_Item
  case TRAINER_DOMINIK, Route105_EventScript_Dominik_Item
  case TRAINER_SYLVIA, MossdeepCity_Gym_EventScript_Sylvia_Item
  case TRAINER_DEBRA, Route133_EventScript_Debra_Item
  case TRAINER_ELIJAH, Route109_EventScript_Elijah_Item
  case TRAINER_WENDY, Route123_EventScript_Wendy_Item
  case TRAINER_DWAYNE, Route109_SeashoreHouse_EventScript_Dwayne_Item
  case TRAINER_RELI_AND_IAN, Route131_EventScript_Reli_Item
  case TRAINER_SPENCER, Route124_EventScript_Spencer_Item
  case TRAINER_STAN, Route125_EventScript_Stan_Item
  case TRAINER_MAURA, MossdeepCity_Gym_EventScript_Maura_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_2, AquaHideout_B1F_EventScript_Grunt2_Item
  case TRAINER_DARIUS, FortreeCity_Gym_EventScript_Darius_Item
  case TRAINER_NOLAN, Route114_EventScript_Nolan_Item
  case TRAINER_JOHNSON, Route116_EventScript_Johnson_Item
  case TRAINER_DREW, Route111_EventScript_Drew_Item
  case TRAINER_MEL_AND_PAUL, Route109_EventScript_Mel_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_5, SeafloorCavern_Room3_EventScript_Grunt5_Item
  case TRAINER_DEZ_AND_LUKE, MtPyre_2F_EventScript_Dez_Item
  case TRAINER_DAPHNE, SootopolisCity_Gym_B1F_EventScript_Daphne_Item
  case TRAINER_WINONA_1, FortreeCity_Gym_EventScript_Winona_Item
  case TRAINER_KALEB, Route110_EventScript_Kaleb_Item
  case TRAINER_MITCHELL, VictoryRoad_B1F_EventScript_Mitchell_Item
  case TRAINER_VIVIAN, MauvilleCity_Gym_EventScript_Vivian_Item
  case TRAINER_CAROLINE, VictoryRoad_B2F_EventScript_Caroline_Item
  case TRAINER_JAYLEN, Route113_EventScript_Jaylen_Item
  case TRAINER_DOUG, Route119_EventScript_Doug_Item
  case TRAINER_CYNDY_1, Route115_EventScript_Cyndy_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_4, MagmaHideout_2F_1R_EventScript_Grunt4_Item
  case TRAINER_TED, Route110_TrickHousePuzzle2_EventScript_Ted_Item
  case TRAINER_VIVI, Route111_WinstrateFamilysHouse_EventScript_Vivi_Item
  case TRAINER_AARON, Route134_EventScript_Aaron_Item
  case TRAINER_LEONARD, SSTidalLowerDeck_EventScript_Leonard_Item
  case TRAINER_KATELYNN, VictoryRoad_1F_EventScript_Katelynn_Item
  case TRAINER_DONALD, Route119_EventScript_Donald_Item
  case TRAINER_PHOEBE, Phoebe_Item
  case TRAINER_MOLLIE, Route133_EventScript_Mollie_Item
  case TRAINER_GRUNT_WEATHER_INST_3, Route119_WeatherInstitute_2F_EventScript_Grunt3_Item
  case TRAINER_ALYSSA, Route110_EventScript_Alyssa_Item
  case TRAINER_CHIP, Route120_EventScript_Chip_Item
  case TRAINER_LUNG, Route113_EventScript_Lung_Item
  case TRAINER_GERALD, LavaridgeTown_Gym_1F_EventScript_Gerald_Item
  case TRAINER_CALVIN_1, Route102_EventScript_Calvin_Item
  case TRAINER_SOPHIE, Route113_EventScript_Sophie_Item
  case TRAINER_BETHANY, SootopolisCity_Gym_B1F_EventScript_Bethany_Item
  case TRAINER_EDWARDO, FortreeCity_Gym_EventScript_Edwardo_Item
  case TRAINER_MAY_ROUTE_110_MUDKIP, Route110_EventScript_GiveItemfinder_Item2
  case TRAINER_CARLEE, Route128_EventScript_Carlee_Item
  case TRAINER_HERMAN, Route131_EventScript_Herman_Item
  case TRAINER_TONY_1, Route107_EventScript_Tony_Item
  case TRAINER_HUDSON, Route134_EventScript_Hudson_Item
  case TRAINER_VALERIE_1, MtPyre_6F_EventScript_Valerie_Item
  case TRAINER_JACE, LavaridgeTown_Gym_B1F_EventScript_Jace_Item
  case TRAINER_CONNIE, SootopolisCity_Gym_B1F_EventScript_Connie_Item
  case TRAINER_SIDNEY, Sydney_Item
  case TRAINER_HELENE, Route115_EventScript_Helene_Item
  case TRAINER_KATE_AND_JOY, Route121_EventScript_Kate_Item
  case TRAINER_KYRA, Route115_EventScript_Kyra_Item
  case TRAINER_GLACIA, Glacia_Item
  case TRAINER_FRANKLIN, Route133_EventScript_Franklin_Item
  case TRAINER_RILEY, Route120_EventScript_Riley_Item
  case TRAINER_TRAVIS, Route111_EventScript_Travis_Item
  case TRAINER_DALE, Route110_EventScript_Dale_Item
  case TRAINER_ANGELINA, Route114_EventScript_Angelina_Item
  case TRAINER_JEFF, LavaridgeTown_Gym_B1F_EventScript_Jeff_Item
  case TRAINER_MISSY, Route108_EventScript_Missy_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_11, MagmaHideout_4F_EventScript_Grunt11_Item
  case TRAINER_LORENZO, Route120_EventScript_Lorenzo_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_3, AquaHideout_B1F_EventScript_Grunt3_Item
  case TRAINER_AISHA, Route117_EventScript_Aisha_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_3, MagmaHideout_2F_1R_EventScript_Grunt3_Item
  case TRAINER_JACOB, Route110_EventScript_Jacob_Item
  case TRAINER_GRUNT_MT_PYRE_1, MtPyre_Summit_EventScript_Grunt1_Item
  case TRAINER_NICHOLAS, MossdeepCity_Gym_EventScript_Nicholas_Item
  case TRAINER_BERKE, PetalburgCity_Gym_EventScript_Berke_Item
  case TRAINER_MARCEL, Route121_EventScript_Marcel_Item
  case TRAINER_DANA, Route132_EventScript_Dana_Item
  case TRAINER_KIRK, MauvilleCity_Gym_EventScript_Kirk_Item
  case TRAINER_RONALD, Route132_EventScript_Ronald_Item
  case TRAINER_LEA_AND_JED, SSTidalRooms_EventScript_Jed_Item
  case TRAINER_GRUNT_JAGGED_PASS, JaggedPass_EventScript_MagmaHideoutGuard_Item
  case TRAINER_STEVE_1, Route114_EventScript_Steve_Item
  case TRAINER_JASMINE, Route110_EventScript_Jasmine_Item
  case TRAINER_ROSE_1, Route118_EventScript_Rose_Item
  case TRAINER_SAMANTHA, MossdeepCity_Gym_EventScript_Samantha_Item
  case TRAINER_ALAN, Route110_TrickHousePuzzle3_EventScript_Alan_Item
  case TRAINER_ALIX, Route115_EventScript_Alix_Item
  case TRAINER_HANNAH, MossdeepCity_Gym_EventScript_Hannah_Item
  case TRAINER_KOICHI, Route115_EventScript_Koichi_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_15, MagmaHideout_2F_2R_EventScript_Grunt15_Item
  case TRAINER_MARY, PetalburgCity_Gym_EventScript_Mary_Item
  case TRAINER_CLARK, Route116_EventScript_Clark_Item
  case TRAINER_DARCY, Route132_EventScript_Darcy_Item
  case TRAINER_NIKKI, Route126_EventScript_Nikki_Item
  case TRAINER_DECLAN, Route124_EventScript_Declan_Item
  case TRAINER_SOPHIA, Route110_TrickHousePuzzle6_EventScript_Sophia_Item
  case TRAINER_GREG, Route119_EventScript_Greg_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_8, AquaHideout_B2F_EventScript_Grunt8_Item
  case TRAINER_FLANNERY_1, LavaridgeTown_Gym_1F_EventScript_Flannery_Item
  case TRAINER_MARLENE, Route115_EventScript_Marlene_Item
  case TRAINER_GRUNT_WEATHER_INST_2, Route119_WeatherInstitute_2F_EventScript_Grunt2_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_1, SeafloorCavern_Room1_EventScript_Grunt1_Item
  case TRAINER_DIANA_1, JaggedPass_EventScript_Diana_Item
  case TRAINER_SHAWN, MauvilleCity_Gym_EventScript_Shawn_Item
  case TRAINER_JACKI_1, Route123_EventScript_Jacki_Item
  case TRAINER_DALTON_1, Route118_EventScript_Dalton_Item
  case TRAINER_SANTIAGO, Route130_EventScript_Santiago_Item
  case TRAINER_TANYA, Route125_EventScript_Tanya_Item
  case TRAINER_KELVIN, Route134_EventScript_Kelvin_Item
  case TRAINER_NAOMI, SSTidalRooms_EventScript_Naomi_Item
  case TRAINER_LOLA_1, Route109_EventScript_Lola_Item
  case TRAINER_JOSH, RustboroCity_Gym_EventScript_Josh_Item
  case TRAINER_PHILLIP, SSTidalLowerDeck_EventScript_Phillip_Item
  case TRAINER_LAWRENCE, Route113_EventScript_Lawrence_Item
  case TRAINER_BRANDEN, Route111_EventScript_Branden_Item
  case TRAINER_BRYANT, Route112_EventScript_Bryant_Item
  case TRAINER_PARKER, PetalburgCity_Gym_EventScript_Parker_Item
  case TRAINER_JAZMYN, Route123_EventScript_Jazmyn_Item
  case TRAINER_GARRISON, AbandonedShip_Rooms2_1F_EventScript_Garrison_Item
  case TRAINER_GRUNT_WEATHER_INST_1, Route119_WeatherInstitute_1F_EventScript_Grunt1_Item
  case TRAINER_ANGELICA, Route120_EventScript_Angelica_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_10, MagmaHideout_3F_2R_EventScript_Grunt10_Item
  case TRAINER_KATHLEEN, MossdeepCity_Gym_EventScript_Kathleen_Item
  case TRAINER_PAUL, Route110_TrickHousePuzzle2_EventScript_Paul_Item
  case TRAINER_CHASE, Route129_EventScript_Chase_Item
  case TRAINER_GABBY_AND_TY_3, Gabby_Ty_EventScript_3_Item
  case TRAINER_DARRIN, Route107_EventScript_Darrin_Item
  case TRAINER_ALEXA, Route128_EventScript_Alexa_Item
  case TRAINER_TAKASHI, Route119_EventScript_Takashi_Item
  case TRAINER_EDMOND, Route109_EventScript_Edmond_Item
  case TRAINER_GRUNT_WEATHER_INST_4, Route119_WeatherInstitute_1F_EventScript_Grunt4_Item
  case TRAINER_DIANNE, VictoryRoad_B2F_EventScript_Dianne_Item
  case TRAINER_MIKE_1, RusturfTunnel_EventScript_Mike_Item
  case TRAINER_RACHEL, Route119_EventScript_Rachel_Item
  case TRAINER_BROOKE_1, Route111_EventScript_Brooke_Item
  case TRAINER_GEORGIA, Route110_TrickHousePuzzle2_EventScript_Georgia_Item
  case TRAINER_RICKY_1, Route109_EventScript_Ricky_Item
  case TRAINER_DYLAN_1, Route117_EventScript_Dylan_Item
  case TRAINER_PAXTON, Route132_EventScript_Paxton_Item
  case TRAINER_CEDRIC, MtPyre_6F_EventScript_Cedric_Item
  case TRAINER_KAYLA, MtPyre_3F_EventScript_Kayla_Item
  case TRAINER_KEVIN, Route131_EventScript_Kevin_Item
  case TRAINER_WARREN, Route133_EventScript_Warren_Item
  case TRAINER_EDWARD, Route110_EventScript_Edward_Item
  case TRAINER_MAY_ROUTE_103_MUDKIP, Route103_EventScript_Item_Rival
  case TRAINER_BRAWLY_1, DewfordTown_Gym_EventScript_Brawly_Item
  case TRAINER_GRUNT_WEATHER_INST_5, Route119_WeatherInstitute_2F_EventScript_Grunt5_Item
  case TRAINER_KAREN_1, Route116_EventScript_Karen_Item
  case TRAINER_THALIA_1, AbandonedShip_Rooms_1F_Eventscript_Thalia_Item
  case TRAINER_JEFFREY_1, Route120_EventScript_Jeffrey_Item
  case TRAINER_ABIGAIL_1, Route110_EventScript_Abigail_Item
  case TRAINER_JAIDEN, Route115_EventScript_Jaiden_Item
  case TRAINER_SHELLY_SEAFLOOR_CAVERN, SeafloorCavern_Room3_EventScript_Shelly_Item
  case TRAINER_DEVAN, Route116_EventScript_Devan_Item
  case TRAINER_TIMMY, Route110_EventScript_Timmy_Item
  case TRAINER_BECKY, Route111_EventScript_Becky_Item
  case TRAINER_ALVARO, Route110_TrickHousePuzzle7_EventScript_Alvaro_Item
  case TRAINER_BRYAN, Route111_EventScript_Bryan_Item
  case TRAINER_WAYNE, Route128_EventScript_Wayne_Item
  case TRAINER_BRENDA, Route126_EventScript_Brenda_Item
  case TRAINER_EDWIN_1, Route110_EventScript_Edwin_Item
  case TRAINER_ISAIAH_1, Route128_EventScript_Isaiah_Item
  case TRAINER_EDGAR, VictoryRoad_1F_EventScript_Edgar_Item
  case TRAINER_PRESTON, MossdeepCity_Gym_EventScript_Preston_Item
  case TRAINER_CHRIS, Route119_EventScript_Chris_Item
  case TRAINER_REED, Route129_EventScript_Reed_Item
  case TRAINER_LYLE, PetalburgWoods_EventScript_Lyle_Item
  case TRAINER_ISABELLA, Route124_EventScript_Isabella_Item
  case TRAINER_LENNY, Route114_EventScript_Lenny_Item
  case TRAINER_TORI_AND_TIA, Route113_EventScript_Tori_Item
  case TRAINER_GRUNT_PETALBURG_WOODS, PetalburgWoods_EventScript_DevonResearcherLeft_Item
  case TRAINER_JANICE, Route116_EventScript_Janice_Item
  case TRAINER_CALLIE, Route120_EventScript_Callie_Item
  case TRAINER_ARCHIE, SeafloorCavern_Room9_EventScript_ArchieAwakenKyogre_Item
  case TRAINER_BRENT, Route119_EventScript_Brent_Item
  case TRAINER_EVERETT, Route110_TrickHousePuzzle7_EventScript_Everett_Item
  case TRAINER_SHARON, Route125_EventScript_Sharon_Item
  case TRAINER_CAROLINA, Route108_EventScript_Carolina_Item
  case TRAINER_CATHERINE_1, Route119_EventScript_Catherine_Item
  case TRAINER_DOUGLAS, Route106_EventScript_Douglas_Item
  case TRAINER_WILTON_1, Route111_EventScript_Wilton_Item
  case TRAINER_BEN, MauvilleCity_Gym_EventScript_Ben_Item
  case TRAINER_QUINCY, VictoryRoad_1F_EventScript_Quincy_Item
  case TRAINER_BEVERLY, Route105_EventScript_Beverly_Item
  case TRAINER_TOMMY, RustboroCity_Gym_EventScript_Tommy_Item
  case TRAINER_MYLES, Route121_EventScript_Myles_Item
  case TRAINER_VICKY, Route111_WinstrateFamilysHouse_EventScript_Vicky_Item
  case TRAINER_ATSUSHI, MtPyre_5F_EventScript_Atsushi_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_8, MagmaHideout_2F_2R_EventScript_Grunt8_Item
  case TRAINER_MELINA, Route117_EventScript_Melina_Item
  case TRAINER_TATE_AND_LIZA_1, MossdeepCity_Gym_EventScript_TateAndLiza_Item
  case TRAINER_AXLE, LavaridgeTown_Gym_1F_EventScript_Axle_Item
  case TRAINER_ED, Route123_EventScript_Ed_Item
  case TRAINER_NOLEN, Route125_EventScript_Nolen_Item
  case TRAINER_KEEGAN, LavaridgeTown_Gym_B1F_EventScript_Keegan_Item
  case TRAINER_JULIE, VictoryRoad_B2F_EventScript_Julie_Item
  case TRAINER_JENNA, Route120_EventScript_Jenna_Item
  case TRAINER_WILLIAM, MtPyre_3F_EventScript_William_Item
  case TRAINER_SHANNON, VictoryRoad_B1F_EventScript_Shannon_Item
  case TRAINER_DAVIS, Route123_EventScript_Davis_Item
  case TRAINER_GABRIELLE_1, MtPyre_3F_EventScript_Gabrielle_Item
  case TRAINER_MARTHA, Route110_TrickHousePuzzle3_EventScript_Martha_Item
  case TRAINER_JOSHUA, Route110_TrickHousePuzzle7_EventScript_Joshua_Item
  case TRAINER_CHARLIE, AbandonedShip_Corridors_1F_EventScript_Charlie_Item
  case TRAINER_GRUNT_MT_PYRE_4, MtPyre_Summit_EventScript_Grunt4_Item
  case TRAINER_DILLON, Route113_EventScript_Dillon_Item
  case TRAINER_ISAAC_1, Route117_EventScript_Isaac_Item
  case TRAINER_ALBERTO, Route123_EventScript_Alberto_Item
  case TRAINER_JOEY, Route116_EventScript_Joey_Item
  case TRAINER_JEROME, Route108_EventScript_Jerome_Item
  case TRAINER_ALBERT, VictoryRoad_1F_EventScript_Albert_Item
  case TRAINER_CAROL, Route112_EventScript_Carol_Item
  case TRAINER_CELINA, Route111_EventScript_Celina_Item
  case TRAINER_LARRY, Route112_EventScript_Larry_Item
  case TRAINER_VICTORIA, Route111_WinstrateFamilysHouse_EventScript_Victoria_Item
  case TRAINER_LINDA, Route133_EventScript_Linda_Item
  case TRAINER_LEROY, Route110_TrickHousePuzzle8_EventScript_Leroy_Item
  case TRAINER_REYNA, Route134_EventScript_Reyna_Item
  case TRAINER_DEAN, Route126_EventScript_Dean_Item
  case TRAINER_CHESTER, Route118_EventScript_Chester_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_5, AquaHideout_B1F_EventScript_Grunt5_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_2, MagmaHideout_1F_EventScript_Grunt2_Item
  case TRAINER_RODNEY, Route130_EventScript_Rodney_Item
  case TRAINER_ELI, LavaridgeTown_Gym_B1F_EventScript_Eli_Item
  case TRAINER_JOSE, Route116_EventScript_Jose_Item
  case TRAINER_WALLY_MAUVILLE, MauvilleCity_EventScript_DefeatedWally_Item
  case TRAINER_MARLEY, Route134_EventScript_Marley_Item
  case TRAINER_MACEY, MossdeepCity_Gym_EventScript_Macey_Item
  case TRAINER_COLTON, SSTidalRooms_EventScript_Colton_Item
  case TRAINER_KATIE, Route130_EventScript_Katie_Item
  case TRAINER_ANGELO, MauvilleCity_Gym_EventScript_Angelo_Item
  case TRAINER_MICHELLE, VictoryRoad_B1F_EventScript_Michelle_Item
  case TRAINER_ALICE, Route109_EventScript_Alice_Item
  case TRAINER_VANESSA, Route121_EventScript_Vanessa_Item
  case TRAINER_LYDIA_1, Route117_EventScript_Lydia_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_7, MagmaHideout_2F_2R_EventScript_Grunt7_Item
  case TRAINER_SHELLY_WEATHER_INSTITUTE, Route119_WeatherInstitute_2F_EventScript_Shelly_Item
  case TRAINER_GARRET, SSTidalRooms_EventScript_Garret_Item
  case TRAINER_JOSUE, Route105_EventScript_Josue_Item
  case TRAINER_FLINT, FortreeCity_Gym_EventScript_Flint_Item
  case TRAINER_TYRA_AND_IVY, Route114_EventScript_Tyra_Item
  case TRAINER_KIYO, Route132_EventScript_Kiyo_Item
  case TRAINER_DRAKE, Drake_Item
  case TRAINER_CARTER, Route109_EventScript_Carter_Item
  case TRAINER_ERNEST_1, Route125_EventScript_Ernest_Item
  case TRAINER_ROXANNE_1, RustboroCity_Gym_EventScript_Roxanne_Item
  case TRAINER_MIU_AND_YUKI, Route123_EventScript_Miu_Item
  case TRAINER_COLE, LavaridgeTown_Gym_1F_EventScript_Cole_Item
  case TRAINER_MAKAYLA, Route132_EventScript_Makayla_Item
  case TRAINER_PAT, Route121_EventScript_Pat_Item
  case TRAINER_BRIANNA, SootopolisCity_Gym_B1F_EventScript_Brianna_Item
  case TRAINER_PERRY, Route118_EventScript_Perry_Item
  case TRAINER_JOHANNA, Route109_SeashoreHouse_EventScript_Johanna_Item
  case TRAINER_WALLY_VR_1, VictoryRoad_1F_EventScript_WallyEntranceBattle_Item
  case TRAINER_AUSTINA, Route109_EventScript_Austina_Item
  case TRAINER_CORY_1, Route108_EventScript_Cory_Item
  case TRAINER_AUTUMN, JaggedPass_EventScript_Autumn_Item
  case TRAINER_RUBEN, Route128_EventScript_Ruben_Item
  case TRAINER_CHANDLER, Route109_EventScript_Chandler_Item
  case TRAINER_HAYDEN, Route111_EventScript_Hayden_Item
  case TRAINER_CLARISSA, Route120_EventScript_Clarissa_Item
  case TRAINER_SHAYLA, Route112_EventScript_Shayla_Item
  case TRAINER_JESSICA_1, Route121_EventScript_Jessica_Item
  case TRAINER_SIMON, Route109_SeashoreHouse_EventScript_Simon_Item
  case TRAINER_BRICE, Route112_EventScript_Brice_Item
  case TRAINER_HEIDI, Route111_EventScript_Heidi_Item
  case TRAINER_BENJAMIN_1, Route110_EventScript_Benjamin_Item
  case TRAINER_WYATT, Route113_EventScript_Wyatt_Item
  case TRAINER_SIENNA, Route126_EventScript_Sienna_Item
  case TRAINER_LAO_1, Route113_EventScript_Lao_Item
  case TRAINER_MATT, AquaHideout_B2F_EventScript_Matt_Item
  case TRAINER_IMANI, Route105_EventScript_Imani_Item
  case TRAINER_DAYTON, Route119_EventScript_Dayton_Item
  case TRAINER_SALLY, Route110_TrickHousePuzzle1_EventScript_Sally_Item
  case TRAINER_JOCELYN, DewfordTown_Gym_EventScript_Jocelyn_Item
  case TRAINER_JACK, Route134_EventScript_Jack_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_6, AquaHideout_B2F_EventScript_Grunt6_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_13, MagmaHideout_4F_EventScript_Grunt13_Item
  case TRAINER_TAMMY, Route121_EventScript_Tammy_Item
  case TRAINER_TABITHA_MAGMA_HIDEOUT, MagmaHideout_4F_EventScript_Tabitha_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_5, MagmaHideout_2F_1R_EventScript_Grunt5_Item
  case TRAINER_SEBASTIAN, Route110_TrickHousePuzzle6_EventScript_Sebastian_Item
  case TRAINER_ALLEN, Route102_EventScript_Allen_Item
  case TRAINER_COBY, Route113_EventScript_Coby_Item
  case TRAINER_NED, Route106_EventScript_Ned_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_2, SeafloorCavern_Room1_EventScript_Grunt2_Item
  case TRAINER_ANNIKA, SootopolisCity_Gym_B1F_EventScript_Annika_Item
  case TRAINER_LISA_AND_RAY, Route107_EventScript_Lisa_Item
  case TRAINER_TAYLOR, Route119_EventScript_Taylor_Item
  case TRAINER_JUAN_1, SootopolisCity_Gym_1F_EventScript_Juan_Item
  case TRAINER_JOHN_AND_JAY_1, MeteorFalls_1F_2R_EventScript_John_Item
  case TRAINER_PATRICIA, Route110_TrickHousePuzzle7_EventScript_Patricia_Item
  case TRAINER_VIRGIL, MossdeepCity_Gym_EventScript_Virgil_Item
  case TRAINER_TIANA, Route102_EventScript_Tiana_Item
  case TRAINER_GWEN, Route109_EventScript_Gwen_Item
  case TRAINER_ROBIN, Route110_TrickHousePuzzle1_EventScript_Robin_Item
  case TRAINER_TARA, Route108_EventScript_Tara_Item
  case TRAINER_BENNY, Route110_TrickHousePuzzle6_EventScript_Benny_Item
  case TRAINER_CLAUDE, Route114_EventScript_Claude_Item
  case TRAINER_DAVID, Route109_EventScript_David_Item
  case TRAINER_KEIRA, Route110_TrickHousePuzzle8_EventScript_Keira_Item
  case TRAINER_ALEX, Route134_EventScript_Alex_Item
  case TRAINER_HOPE, VictoryRoad_1F_EventScript_Hope_Item
  case TRAINER_DAWSON, Route116_EventScript_Dawson_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_3, SeafloorCavern_Room4_EventScript_Grunt3_Item
  case TRAINER_NATE, MossdeepCity_Gym_EventScript_Nate_Item
  case TRAINER_ROLAND, Route124_EventScript_Roland_Item
  case TRAINER_TISHA, Route129_EventScript_Tisha_Item
  case TRAINER_CRISTIN_1, Route121_EventScript_Cristin_Item
  case TRAINER_BARRY, Route126_EventScript_Barry_Item
  case TRAINER_BEAU, Route111_EventScript_Beau_Item
  case TRAINER_MARIELA, Route110_TrickHousePuzzle7_EventScript_Mariela_Item
  case TRAINER_KATELYN_1, Route128_EventScript_Katelyn_Item
  case TRAINER_JARED, FortreeCity_Gym_EventScript_Jared_Item
  case TRAINER_DANIELLE, LavaridgeTown_Gym_1F_EventScript_Danielle_Item
  case TRAINER_BLAKE, MossdeepCity_Gym_EventScript_Blake_Item
  case TRAINER_GRUNT_MT_PYRE_3, MtPyre_Summit_EventScript_Grunt3_Item
  case TRAINER_DENISE, Route107_EventScript_Denise_Item
  case TRAINER_EDDIE, Route110_TrickHousePuzzle1_EventScript_Eddie_Item
  case TRAINER_DAISUKE, Route111_EventScript_Daisuke_Item
  case TRAINER_BRANDI, Route117_EventScript_Brandi_Item
  case TRAINER_NORMAN_1, PetalburgCity_Gym_EventScript_NormanBattle_Item
  case TRAINER_KARA, Route131_EventScript_Kara_Item
  case TRAINER_MARK, MtPyre_2F_EventScript_Mark_Item
  case TRAINER_ALEXIS, Route110_TrickHousePuzzle7_EventScript_Alexis_Item
  case TRAINER_JENNIFER, Route120_EventScript_Jennifer_Item
  case TRAINER_YUJI, Route110_TrickHousePuzzle4_EventScript_Yuji_Item
  case TRAINER_BRIDGET, SootopolisCity_Gym_B1F_EventScript_Bridget_Item
  case TRAINER_ELLIOT_1, Route106_EventScript_Elliot_Item
  case TRAINER_SHANE, Route114_EventScript_Shane_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_9, MagmaHideout_3F_1R_EventScript_Grunt9_Item
  case TRAINER_LEONEL, Route120_EventScript_Leonel_Item
  case TRAINER_BRENDEN, DewfordTown_Gym_EventScript_Brenden_Item
  case TRAINER_STEVEN, MeteorFalls_StevensCave_EventScript_Steven_Item
  case TRAINER_BARNY, Route118_EventScript_Barny_Item
  case TRAINER_ASHLEY, FortreeCity_Gym_EventScript_Ashley_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_1, AquaHideout_1F_EventScript_Grunt1_Item
  case TRAINER_LILITH, DewfordTown_Gym_EventScript_Lilith_Item
  case TRAINER_KYLA, Route106_EventScript_Kyla_Item
  case TRAINER_WALTER_1, Route121_EventScript_Walter_Item
  case TRAINER_DUSTY_1, Route111_EventScript_Dusty_Item
  case TRAINER_VINCENT, Route110_TrickHousePuzzle8_EventScript_Vincent_Item
  case TRAINER_ISOBEL, Route126_EventScript_Isobel_Item
  case TRAINER_LEAH, MtPyre_2F_EventScript_Leah_Item
  case TRAINER_CLARENCE, Route129_EventScript_Clarence_Item
  case TRAINER_HECTOR, Route115_EventScript_Hector_Item
  case TRAINER_SARAH, Route116_EventScript_Sarah_Item
  case TRAINER_CELIA, Route111_EventScript_Celia_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_16, MagmaHideout_3F_1R_EventScript_Grunt16_Item
  case TRAINER_ANTHONY, Route110_EventScript_Anthony_Item
  case TRAINER_JULIO, JaggedPass_EventScript_Julio_Item
  case TRAINER_TRENT_1, Route112_EventScript_Trent_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_4, AquaHideout_B2F_EventScript_Grunt4_Item
case TRAINER_BRENDAN_ROUTE_103_MUDKIP, Route103_EventScript_Item_Rival
    case TRAINER_BRENDAN_ROUTE_110_MUDKIP, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_BRENDAN_ROUTE_119_MUDKIP, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_BRENDAN_ROUTE_103_TREECKO, Route103_EventScript_Item_Rival
    case TRAINER_BRENDAN_ROUTE_110_TREECKO, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_BRENDAN_ROUTE_119_TREECKO, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_BRENDAN_ROUTE_103_TORCHIC, Route103_EventScript_Item_Rival
    case TRAINER_BRENDAN_ROUTE_110_TORCHIC, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_BRENDAN_ROUTE_119_TORCHIC, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_BRENDAN_ROUTE_103_MUDKIP, Route103_EventScript_Item_Rival
    case TRAINER_MAY_ROUTE_103_TREECKO, Route103_EventScript_Item_Rival
    case TRAINER_MAY_ROUTE_110_TREECKO, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_MAY_ROUTE_119_TREECKO, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_MAY_ROUTE_103_TORCHIC, Route103_EventScript_Item_Rival
    case TRAINER_MAY_ROUTE_110_TORCHIC, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_MAY_ROUTE_119_TORCHIC, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_BRENDAN_LILYCOVE_MUDKIP, LilycoveCity_EventScript_Rival_Item
    case TRAINER_BRENDAN_LILYCOVE_TREECKO, LilycoveCity_EventScript_Rival_Item
    case TRAINER_BRENDAN_LILYCOVE_TORCHIC, LilycoveCity_EventScript_Rival_Item
    case TRAINER_MAY_LILYCOVE_TREECKO, LilycoveCity_EventScript_Rival_Item
    case TRAINER_MAY_LILYCOVE_TORCHIC, LilycoveCity_EventScript_Rival_Item
    return
Recieve_Mon_Fanfare::
	playfanfare MUS_OBTAIN_ITEM
	bufferspeciesname STR_VAR_1, VAR_TEMP_1
	message Player_Recieved_Mon
	waitmessage
	waitfanfare
	return

Player_Recieved_Mon:
	.string "{PLAYER} received {STR_VAR_1}!$"

Recieve_Pokemon_Party::
	call Recieve_Mon_Fanfare
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	call Common_EventScript_GetGiftMonPartySlot
	call Common_EventScript_NameReceivedPartyMon
	end

Recieve_Pokemon_PC::
	call Recieve_Mon_Fanfare
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	call Common_EventScript_NameReceivedBoxMon
   call Common_EventScript_TransferredToPC
	end

Get_Pokemon::
	givemon VAR_TEMP_1, 15
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PARTY, Recieve_Pokemon_Party
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PC, Recieve_Pokemon_PC
	goto Common_EventScript_NoMoreRoomForPokemon
Rustboro_Pokemon::
    setvar VAR_TEMP_1, SPECIES_BLASTOISE
   setvar VAR_TEMP_2, 15
   call Get_Pokemon

Dewford_Pokemon::
    setvar VAR_TEMP_1, SPECIES_GENGAR
   setvar VAR_TEMP_2, 19
   call Get_Pokemon

Mauville_Pokemon::
    setvar VAR_TEMP_1, SPECIES_RATTATA
   setvar VAR_TEMP_2, 24
   call Get_Pokemon

Lavaridge_Pokemon::
    setvar VAR_TEMP_1, SPECIES_MILTANK
   setvar VAR_TEMP_2, 29
   call Get_Pokemon

Petalburg_Pokemon::
    setvar VAR_TEMP_1, SPECIES_GLIGAR
   setvar VAR_TEMP_2, 31
   call Get_Pokemon

Fortree_Pokemon::
    setvar VAR_TEMP_1, SPECIES_WOBBUFFET
   setvar VAR_TEMP_2, 33
   call Get_Pokemon

Mosdeep_Pokemon::
    setvar VAR_TEMP_1, SPECIES_MACHOKE
   setvar VAR_TEMP_2, 42
   call Get_Pokemon

Sootopolis_Pokemon::
    setvar VAR_TEMP_1, SPECIES_MAGBY
   setvar VAR_TEMP_2, 46
   call Get_Pokemon
