MagmaHideout_1F_EventScript_Grunt1_Item::
giveegg SPECIES_NIDORINA

return

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
givemon SPECIES_POLIWHIRL, 22, ITEM_NONE

return

DewfordTown_Gym_EventScript_Lilith_Item::
givemon SPECIES_GRAVELER, 16, ITEM_NONE

return

Route113_EventScript_Tori_Item::
giveitem ITEM_HEAL_BALL

return

SootopolisCity_Gym_B1F_EventScript_Daphne_Item::
giveitem ITEM_ULTRA_BALL

return

SootopolisCity_Gym_B1F_EventScript_Tiffany_Item::
giveitem ITEM_MOON_BALL

return

DewfordTown_Gym_EventScript_Brenden_Item::
giveitem ITEM_FRIEND_BALL

return

MeteorFalls_StevensCave_EventScript_Steven_Item::
giveitem ITEM_LOVE_BALL

return

Route133_EventScript_Mollie_Item::
giveitem ITEM_DUSK_BALL

return

Route130_EventScript_Rodney_Item::
giveitem ITEM_REPEAT_BALL

return

Route120_EventScript_Callie_Item::
giveitem ITEM_NET_BALL

return

Gabby_Ty_EventScript_2_Item::
giveitem ITEM_LOVE_BALL

return

MtPyre_6F_EventScript_Cedric_Item::
giveitem ITEM_PREMIER_BALL

return

Route113_EventScript_Jaylen_Item::
giveitem ITEM_DIVE_BALL

return

Route110_EventScript_Timmy_Item::
giveitem ITEM_NET_BALL

return

Route109_EventScript_David_Item::
giveitem ITEM_LURE_BALL

return

Route119_EventScript_RivalExitScottArrive_Item::
giveitem ITEM_LURE_BALL

return

VictoryRoad_B2F_EventScript_Dianne_Item::
giveitem ITEM_PREMIER_BALL

return

Route115_EventScript_ItemSuperPotion::
finditem ITEM_MOON_BALL

return

PetalburgCity_Gym_EventScript_NormanBattle_Item::
giveitem ITEM_NEST_BALL

return

Route106_EventScript_Douglas_Item::
giveitem ITEM_REPEAT_BALL

return

PetalburgCity_EventScript_ItemEther::
finditem ITEM_NET_BALL

return

GraniteCave_1F_EventScript_Hiker_Item::
giveitem ITEM_HM05

return

Route119_EventScript_Hideo_Item::
giveitem ITEM_GREAT_BALL

return

GraniteCave_B1F_EventScript_ItemPokeBall::
finditem ITEM_RARE_CANDY

return

Route113_EventScript_Madeline_Item::
giveitem ITEM_RARE_CANDY

return

Route102_EventScript_Calvin_Item::
giveitem ITEM_RARE_CANDY

return

Route114_EventScript_Lenny_Item::
giveitem ITEM_RARE_CANDY

return

SeafloorCavern_Room3_EventScript_Shelly_Item::
giveitem ITEM_RARE_CANDY

return

Route109_EventScript_Chandler_Item::
giveitem ITEM_RARE_CANDY

return

Route119_EventScript_Jackson_Item::
giveitem ITEM_RARE_CANDY

return

Route110_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

Route104_EventScript_ItemPotion::
finditem ITEM_RARE_CANDY

return

Route107_EventScript_Lisa_Item::
giveitem ITEM_RARE_CANDY

return

Route123_EventScript_Wendy_Item::
giveitem ITEM_RARE_CANDY

return

Route123_EventScript_Kindra_Item::
giveitem ITEM_RARE_CANDY

return

Route128_EventScript_Wayne_Item::
giveitem ITEM_RARE_CANDY

return

Route124_EventScript_Roland_Item::
giveitem ITEM_RARE_CANDY

return

MEScrCmd_givepokemon::
giveitem ITEM_RARE_CANDY

return

Route109_EventScript_Alice_Item::
giveitem ITEM_RARE_CANDY

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle7_Item::
giveitem ITEM_RARE_CANDY

return

Route110_TrickHousePuzzle4_EventScript_Paula_Item::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_Tyron_Item::
giveitem ITEM_RARE_CANDY

return

VictoryRoad_B1F_EventScript_Mitchell_Item::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_ItemTM37::
finditem ITEM_RARE_CANDY

return

Route125_EventScript_Tanya_Item::
giveitem ITEM_RARE_CANDY

return

Route109_EventScript_ItemPotion::
finditem ITEM_RARE_CANDY

return

RusturfTunnel_EventScript_ItemMaxEther::
finditem ITEM_RARE_CANDY

return

LavaridgeTown_Gym_B1F_EventScript_Jeff_Item::
giveitem ITEM_RARE_CANDY

return

GraniteCave_StevensRoom_EventScript_Steven_Item::
giveitem ITEM_RARE_CANDY

return

JaggedPass_EventScript_Eric_Item::
giveitem ITEM_RARE_CANDY

return

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
finditem ITEM_RARE_CANDY

return

FallarborTown_CozmosHouse_EventScript_PlayerHasMeteorite_Item::
giveitem ITEM_RARE_CANDY

return

DewfordTown_Gym_EventScript_Laura_Item::
giveitem ITEM_RARE_CANDY

return

ScorchedSlab_EventScript_ItemTM11::
finditem ITEM_RARE_CANDY

return

FortreeCity_House4_EventScript_WingullReturned_Item::
giveitem ITEM_RARE_CANDY

return

PetalburgCity_Gym_EventScript_Mary_Item::
giveitem ITEM_RARE_CANDY

return

Route111_WinstrateFamilysHouse_EventScript_Victoria_Item::
giveitem ITEM_RARE_CANDY

return

Route120_EventScript_Leonel_Item::
giveitem ITEM_RARE_CANDY

return

SeafloorCavern_Room4_EventScript_Grunt4_Item::
giveitem ITEM_RARE_CANDY

return

Route109_SeashoreHouse_EventScript_Dwayne_Item::
giveitem ITEM_RARE_CANDY

return

Route109_EventScript_Ricky_Item::
giveitem ITEM_RARE_CANDY

return

MtPyre_3F_EventScript_ItemSuperRepel::
finditem ITEM_RARE_CANDY

return

Route111_EventScript_Beau_Item::
giveitem ITEM_RARE_CANDY

return

Route120_EventScript_ItemRevive::
finditem ITEM_RARE_CANDY

return

MossdeepCity_Gym_EventScript_Nate_Item::
giveitem ITEM_RARE_CANDY

return

LavaridgeTown_Gym_B1F_EventScript_Jace_Item::
giveitem ITEM_RARE_CANDY

return

Route133_EventScript_Conor_Item::
giveitem ITEM_RARE_CANDY

return

Route116_EventScript_Janice_Item::
giveitem ITEM_RARE_CANDY

return

Route104_EventScript_ItemPokeBall::
finditem ITEM_RARE_CANDY

return

RusturfTunnel_EventScript_Grunt_Item::
giveitem ITEM_DEVON_PARTS

return

SSTidalRooms_EventScript_Garret_Item::
giveitem ITEM_RARE_CANDY

return

Route113_GlassWorkshop_EventScript_GlassWorker_Item::
giveitem ITEM_SOOT_SACK

return

SafariZone_North_EventScript_ItemCalcium::
finditem ITEM_RARE_CANDY

return

Route126_EventScript_Nikki_Item::
giveitem ITEM_RARE_CANDY

return

Route119_WeatherInstitute_2F_EventScript_Grunt5_Item::
giveitem ITEM_RARE_CANDY

return

Route120_EventScript_ItemNugget::
finditem ITEM_RARE_CANDY

return

SafariZone_Northwest_EventScript_ItemTM22::
finditem ITEM_RARE_CANDY

return

Route115_EventScript_ItemTM01::
finditem ITEM_RARE_CANDY

return

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
finditem ITEM_RARE_CANDY

return

SootopolisCity_Gym_B1F_EventScript_Brianna_Item::
giveitem ITEM_RARE_CANDY

return

Route114_EventScript_Charlotte_Item::
giveitem ITEM_RARE_CANDY

return

Route117_EventScript_Anna_Item::
giveitem ITEM_RARE_CANDY

return

MagmaHideout_4F_EventScript_ItemMaxRevive::
finditem ITEM_RARE_CANDY

return

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
finditem ITEM_RARE_CANDY

return

Route115_EventScript_Marlene_Item::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_Heidi_Item::
giveitem ITEM_RARE_CANDY

return

Route118_EventScript_Perry_Item::
giveitem ITEM_RARE_CANDY

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle4_Item::
giveitem ITEM_RARE_CANDY

return

Route120_EventScript_Chip_Item::
giveitem ITEM_RARE_CANDY

return

PetalburgCity_Gym_EventScript_George_Item::
giveitem ITEM_RARE_CANDY

return

Route115_EventScript_Kyra_Item::
giveitem ITEM_RARE_CANDY

return

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
finditem ITEM_RARE_CANDY

return

PetalburgCity_WallysHouse_EventScript_GiveHM03Surf_Item::
giveitem ITEM_HM03

return

SootopolisCity_Gym_B1F_EventScript_Bridget_Item::
giveitem ITEM_RARE_CANDY

return

NavelRock_Top_EventScript_HoOh_ITEM::
finditem ITEM_RARE_CANDY

return

Route109_EventScript_Austina_Item::
giveitem ITEM_RARE_CANDY

return

MtPyre_6F_EventScript_ItemTM30::
finditem ITEM_RARE_CANDY

return

MossdeepCity_Gym_EventScript_TateAndLiza_Item::
giveitem ITEM_RARE_CANDY

return

MtPyre_Exterior_EventScript_ItemTM48::
finditem ITEM_RARE_CANDY

return

Route111_EventScript_ItemStardust::
finditem ITEM_RARE_CANDY

return

Route119_EventScript_Brent_Item::
giveitem ITEM_RARE_CANDY

return

SootopolisCity_Gym_B1F_EventScript_Annika_Item::
giveitem ITEM_RARE_CANDY

return

MtPyre_Summit_EventScript_Grunt4_Item::
giveitem ITEM_RARE_CANDY

return

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
finditem ITEM_RARE_CANDY

return

Route110_TrickHousePuzzle4_EventScript_Yuji_Item::
giveitem ITEM_RARE_CANDY

return

Route125_EventScript_Ernest_Item::
giveitem ITEM_RARE_CANDY

return

Route120_EventScript_Clarissa_Item::
giveitem ITEM_RARE_CANDY

return

SeafloorCavern_Room9_EventScript_ItemTM26::
finditem ITEM_RARE_CANDY

return

Route115_EventScript_Cyndy_Item::
giveitem ITEM_RARE_CANDY

return

FortreeCity_Gym_EventScript_Ashley_Item::
giveitem ITEM_RARE_CANDY

return

Route109_EventScript_Carter_Item::
giveitem ITEM_RARE_CANDY

return

Route110_TrickHousePuzzle4_EventScript_Cora_Item::
giveitem ITEM_RARE_CANDY

return

Route123_EventScript_ItemUltraBall::
finditem ITEM_RARE_CANDY

return

PetalburgWoods_EventScript_DevonResearcherLeft_Item::
giveitem ITEM_RARE_CANDY

return

MauvilleCity_EventScript_Wattson_Item::
giveitem ITEM_BASEMENT_KEY

return

GraniteCave_B2F_EventScript_ItemRepel::
finditem ITEM_RARE_CANDY

return

Route111_EventScript_Brooke_Item::
giveitem ITEM_RARE_CANDY

return

MagmaHideout_4F_EventScript_Maxie_Item::
giveitem ITEM_RARE_CANDY

return

MtPyre_6F_EventScript_Valerie_Item::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_Bianca_Item::
giveitem ITEM_RARE_CANDY

return

Route110_TrickHousePuzzle2_EventScript_Paul_Item::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_Travis_Item::
giveitem ITEM_RARE_CANDY

return

MossdeepCity_EventScript_KingsRockBoy_Item::
giveitem ITEM_RARE_CANDY

return

Mosdeep_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8EB
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

MauvilleCity_Gym_EventScript_Kirk_Item::
giveitem ITEM_RARE_CANDY

return

MauvilleCity_House2_EventScript_AcceptTrade_Item::
giveitem ITEM_COIN_CASE

return

Route129_EventScript_Clarence_Item::
giveitem ITEM_RARE_CANDY

return

RusturfTunnel_EventScript_Mike_Item::
giveitem ITEM_RARE_CANDY

return

MagmaHideout_2F_1R_EventScript_Grunt14_Item::
giveitem ITEM_RARE_CANDY

return

Route119_WeatherInstitute_1F_EventScript_Grunt4_Item::
giveitem ITEM_RARE_CANDY

return

Route116_EventScript_GiveRepeatBall_Item::
finditem ITEM_RARE_CANDY

return

Route119_EventScript_Hugh_Item::
giveitem ITEM_RARE_CANDY

return

Route133_EventScript_Franklin_Item::
giveitem ITEM_RARE_CANDY

return

AquaHideout_B2F_EventScript_Matt_Item::
giveitem ITEM_RARE_CANDY

return

LavaridgeTown_Gym_B1F_EventScript_Keegan_Item::
giveitem ITEM_RARE_CANDY

return

MagmaHideout_4F_EventScript_Grunt12_Item::
giveitem ITEM_RARE_CANDY

return

PetalburgWoods_EventScript_ItemParalyzeHeal::
giveitem ITEM_RARE_CANDY

return

Route105_EventScript_ItemIron::
finditem ITEM_RARE_CANDY

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle2_Item::
giveitem ITEM_RARE_CANDY

return

Route110_EventScript_Isabel_Item::
giveitem ITEM_RARE_CANDY

return

Route108_EventScript_Cory_Item::
giveitem ITEM_RARE_CANDY

return

VictoryRoad_1F_EventScript_WallyEntranceBattle_Item::
giveitem ITEM_RARE_CANDY

return

SootopolisCity_Gym_B1F_EventScript_Bethany_Item::
giveitem ITEM_RARE_CANDY

return

MeteorFalls_1F_2R_EventScript_Nicolas_Item::
giveitem ITEM_RARE_CANDY

return

FortreeCity_House2_EventScript_HiddenPowerGiver_Item::
giveitem ITEM_RARE_CANDY

return

MagmaHideout_3F_1R_EventScript_ItemNugget::
finditem ITEM_RARE_CANDY

return

MeteorFalls_1F_2R_EventScript_John_Item::
giveitem ITEM_RARE_CANDY

return

Route118_EventScript_Chester_Item::
giveitem ITEM_RARE_CANDY

return

Route103_EventScript_ItemGuardSpec::
finditem ITEM_RARE_CANDY

return

Route121_EventScript_Cale_Item::
giveitem ITEM_RARE_CANDY

return

Lavaridge_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E8
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route120_EventScript_Jenna_Item::
giveitem ITEM_RARE_CANDY

return

MauvilleCity_EventScript_DefeatedWally_Item::
giveitem ITEM_RARE_CANDY

return

MossdeepCity_Gym_EventScript_Samantha_Item::
giveitem ITEM_RARE_CANDY

return

Route116_EventScript_ItemXSpecial::
finditem ITEM_RARE_CANDY

return

NewMauville_Inside_EventScript_ItemEscapeRope::
finditem ITEM_RARE_CANDY

return

Route126_EventScript_Dean_Item::
giveitem ITEM_RARE_CANDY

return

FortreeCity_Gym_EventScript_Jared_Item::
giveitem ITEM_RARE_CANDY

return

RusturfTunnel_EventScript_Grunt_Item_Two::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_GiveSecretPower_Item::
giveitem ITEM_RARE_CANDY

return

Dewford_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E6
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route128_EventScript_Isaiah_Item::
giveitem ITEM_RARE_CANDY

return

Route131_EventScript_Reli_Item::
giveitem ITEM_RARE_CANDY

return

MossdeepCity_Gym_EventScript_Kathleen_Item::
giveitem ITEM_RARE_CANDY

return

Route105_EventScript_Josue_Item::
giveitem ITEM_RARE_CANDY

return

Route104_EventScript_Boy2_Item::
giveitem ITEM_RARE_CANDY

return

RustboroCity_DevonCorp_3F_EventScript_GiveExpShare_Item::
giveitem ITEM_RARE_CANDY

return

Route132_EventScript_Jonathan_Item::
giveitem ITEM_RARE_CANDY

return

Route114_EventScript_Nolan_Item::
giveitem ITEM_RARE_CANDY

return

Route113_EventScript_Coby_Item::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_Branden_Item::
giveitem ITEM_RARE_CANDY

return

Route121_EventScript_ItemCarbos::
finditem ITEM_RARE_CANDY

return

Route116_EventScript_ItemHPUp::
finditem ITEM_RARE_CANDY

return

AquaHideout_B1F_EventScript_ItemMasterBall::
finditem ITEM_RARE_CANDY

return

Route104_EventScript_WhiteHerbFlorist_Item::
giveitem ITEM_RARE_CANDY

return

GraniteCave_1F_EventScript_ItemEscapeRope::
finditem ITEM_RARE_CANDY

return

MossdeepCity_Gym_EventScript_Hannah_Item::
giveitem ITEM_RARE_CANDY

return

Route119_WeatherInstitute_2F_EventScript_Grunt2_Item::
giveitem ITEM_RARE_CANDY

return

Route121_EventScript_Cristin_Item::
giveitem ITEM_RARE_CANDY

return

Route115_EventScript_Hector_Item::
giveitem ITEM_RARE_CANDY

return

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
finditem ITEM_RARE_CANDY

return

SSTidalRooms_EventScript_Micah_Item::
giveitem ITEM_RARE_CANDY

return

Route120_EventScript_Keigo_Item::
giveitem ITEM_RARE_CANDY

return

Route116_EventScript_ItemRepel::
finditem ITEM_RARE_CANDY

return

MtPyre_2F_EventScript_Mark_Item::
giveitem ITEM_RARE_CANDY

return

Route119_EventScript_Phil_Item::
giveitem ITEM_RARE_CANDY

return

Route114_EventScript_Bernie_Item::
giveitem ITEM_RARE_CANDY

return

MossdeepCity_Gym_EventScript_Virgil_Item::
giveitem ITEM_RARE_CANDY

return

MauvilleCity_EventScript_ItemXSpeed::
finditem ITEM_RARE_CANDY

return

LavaridgeTown_Gym_1F_EventScript_Axle_Item::
giveitem ITEM_RARE_CANDY

return

MauvilleCity_Gym_EventScript_Shawn_Item::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_Celia_Item::
giveitem ITEM_RARE_CANDY

return

SootopolisCity_Gym_B1F_EventScript_Crissy_Item::
giveitem ITEM_RARE_CANDY

return

Route121_EventScript_ItemZinc::
finditem ITEM_RARE_CANDY

return

LavaridgeTown_EventScript_EggWoman_Item::
giveitem ITEM_RARE_CANDY

return

Route121_EventScript_Jessica_Item::
giveitem ITEM_RARE_CANDY

return

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
finditem ITEM_RARE_CANDY

return

Route102_EventScript_Rick_Item::
giveitem ITEM_RARE_CANDY

return

Route116_EventScript_Sarah_Item::
giveitem ITEM_RARE_CANDY

return

Petalburg_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E9
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route110_TrickHousePuzzle1_EventScript_Eddie_Item::
giveitem ITEM_RARE_CANDY

return

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

NewMauville_Inside_EventScript_ItemParalyzeHeal::
finditem ITEM_RARE_CANDY

return

LavaridgeTown_Gym_1F_EventScript_Gerald_Item::
giveitem ITEM_RARE_CANDY

return

SootopolisCity_Gym_B1F_EventScript_Olivia_Item::
giveitem ITEM_RARE_CANDY

return

Route114_EventScript_Angelina_Item::
giveitem ITEM_RARE_CANDY

return

Route114_FossilManiacsHouse_EventScript_FossilManiacsBrother_Item::
giveitem ITEM_RARE_CANDY

return

MossdeepCity_Gym_EventScript_Clifford_Item::
giveitem ITEM_RARE_CANDY

return

NewMauville_Inside_EventScript_ItemThunderStone::
finditem ITEM_RARE_CANDY

return

SlateportCity_EventScript_BerryPowderClerk_Item::
giveitem ITEM_POWDER_JAR

return

Route133_EventScript_ItemStarPiece::
finditem ITEM_RARE_CANDY

return

PetalburgWoods_EventScript_DevonResearcherPostBattle_Item::
giveitem ITEM_RARE_CANDY

return

Route120_EventScript_ItemNestBall::
finditem ITEM_RARE_CANDY

return

FortreeCity_Gym_EventScript_Winona_Item::
giveitem ITEM_RARE_CANDY

return

Route119_EventScript_ItemHyperPotion::
finditem ITEM_RARE_CANDY

return

Route110_TrickHousePuzzle7_EventScript_Alvaro_Item::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_Bryan_Item::
giveitem ITEM_RARE_CANDY

return

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
finditem ITEM_STORAGE_KEY

return

Route116_EventScript_Jerry_Item::
giveitem ITEM_RARE_CANDY

return

MauvilleCity_Gym_EventScript_Angelo_Item::
giveitem ITEM_RARE_CANDY

return

SafariZone_Northeast_EventScript_ItemNugget::
finditem ITEM_RARE_CANDY

return

Route134_EventScript_Reyna_Item::
giveitem ITEM_RARE_CANDY

return

AquaHideout_B1F_EventScript_Grunt7_Item::
giveitem ITEM_RARE_CANDY

return

Route115_EventScript_ItemPPUp::
finditem ITEM_RARE_CANDY

return

Route105_EventScript_Dominik_Item::
giveitem ITEM_RARE_CANDY

return

Route119_EventScript_Catherine_Item::
giveitem ITEM_RARE_CANDY

return

Route132_EventScript_Kiyo_Item::
giveitem ITEM_RARE_CANDY

return

Route132_EventScript_Paxton_Item::
giveitem ITEM_RARE_CANDY

return

PetalburgWoods_EventScript_Girl_Item::
giveitem ITEM_RARE_CANDY

return

Route111_EventScript_Dusty_Item::
giveitem ITEM_RARE_CANDY

return

MossdeepCity_EventScript_ItemNetBall::
finditem ITEM_RARE_CANDY

return

Route118_EventScript_Rose_Item::
giveitem ITEM_RARE_CANDY

return

MtPyre_5F_EventScript_Atsushi_Item::
giveitem ITEM_RARE_CANDY

return

FieryPath_EventScript_ItemTM06::
finditem ITEM_RARE_CANDY

return

SootopolisCity_House1_EventScript_BrickBreakBlackBelt_Item::
giveitem ITEM_SPELL_TAG

return

VictoryRoad_1F_EventScript_Edgar_Item::
giveitem ITEM_MIRACLE_SEED

return

PetalburgCity_Gym_EventScript_Parker_Item::
giveitem ITEM_EXPERT_BELT

return

PetalburgCity_EventScript_ItemMaxRevive::
finditem ITEM_BRAVE_MINT

return

Route110_TrickHousePuzzle6_EventScript_Sebastian_Item::
giveitem ITEM_GROWTH_MULCH

return

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
finditem ITEM_FLYING_MEMORY

return

Route119_EventScript_ItemNugget::
finditem ITEM_HP_UP

return

Route121_EventScript_Myles_Item::
giveitem ITEM_STAR_SWEET

return

Route128_EventScript_Alexa_Item::
giveitem ITEM_MAGNET

return

Route114_EventScript_RoarGentleman_Item::
giveitem ITEM_SOLGANIUM_Z

return

AquaHideout_B2F_EventScript_ItemNestBall::
finditem ITEM_MUSCLE_FEATHER

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle1_Item::
giveitem ITEM_TM21

return

Route133_EventScript_ItemMaxRevive::
finditem ITEM_PRISM_SCALE

return

Route134_EventScript_ItemStarPiece::
finditem ITEM_PSYCHIC_GEM

return

AquaHideout_B2F_EventScript_Grunt4_Item::
giveitem ITEM_VENUSAURITE

return

Route123_EventScript_Jazmyn_Item::
giveitem ITEM_TM48

return

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
finditem ITEM_PP_UP

return

Route118_EventScript_Wade_Item::
giveitem ITEM_POKE_DOLL

return

VictoryRoad_B2F_EventScript_Julie_Item::
giveitem ITEM_TM75

return

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
finditem ITEM_TM88

return

Route102_EventScript_Tiana_Item::
giveitem ITEM_PAMTRE_BERRY

return

Route120_EventScript_Lorenzo_Item::
giveitem ITEM_AERODACTYLITE

return

Route124_EventScript_Grace_Item::
giveitem ITEM_BELUE_BERRY

return

AbandonedShip_Rooms_1F_EventScript_Demetrius_Item::
giveitem ITEM_GALARICA_WREATH

return

Route124_EventScript_Chad_Item::
giveitem ITEM_PEWTER_CRUNCHIES

return

MossdeepCity_House3_EventScript_SuperRodFisherman_Item::
giveitem ITEM_SUPER_ROD

return

MagmaHideout_1F_EventScript_Grunt2_Item::
giveitem ITEM_BLAZIKENITE

return

Route117_EventScript_Isaac_Item::
giveitem ITEM_STEELIUM_Z

return

Route132_EventScript_ItemProtein::
finditem ITEM_SITRUS_BERRY

return

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
finditem ITEM_FIRIUM_Z

return

NewMauville_Inside_EventScript_Voltorb2_Item::
finditem ITEM_DAMP_ROCK

return

NewMauville_Inside_EventScript_ItemFullHeal::
finditem ITEM_UTILITY_UMBRELLA

return

RustboroCity_EventScript_ItemXDefend::
finditem ITEM_CLOVER_SWEET

return

Route133_EventScript_ItemBigPearl::
finditem ITEM_ODD_INCENSE

return

Route127_EventScript_ItemCarbos::
finditem ITEM_ADAMANT_MINT

return

DesertUnderpass_EventScript_GiveRootFossil_Item::
giveitem ITEM_WIKI_BERRY

return

Route124_EventScript_Declan_Item::
giveitem ITEM_YELLOW_FLUTE

return

Route120_EventScript_ItemHyperPotion::
finditem ITEM_CASTELIACONE

return

Route104_EventScript_ItemXAccuracy::
finditem ITEM_STRAWBERRY_SWEET

return

Route110_EventScript_Jasmine_Item::
giveitem ITEM_NORMAL_GEM

return

Route114_EventScript_Kai_Item::
giveitem ITEM_HABAN_BERRY

return

Route116_EventScript_Jose_Item::
giveitem ITEM_LAX_MINT

return

Route109_EventScript_Gwen_Item::
giveitem ITEM_TM99

return

Route112_EventScript_Larry_Item::
giveitem ITEM_AMPHAROSITE

return

Route110_TrickHousePuzzle8_EventScript_Keira_Item::
giveitem ITEM_BLACK_BELT

return

Route112_EventScript_Trent_Item::
giveitem ITEM_TROPIC_MAIL

return

MagmaHideout_2F_2R_EventScript_Grunt15_Item::
giveitem ITEM_BALM_MUSHROOM

return

VictoryRoad_B2F_EventScript_Vito_Item::
giveitem ITEM_X_DEFENSE

return

MtPyre_3F_EventScript_Gabrielle_Item::
giveitem ITEM_GROUND_GEM

return

Route132_EventScript_Makayla_Item::
giveitem ITEM_ICICLE_PLATE

return

Route117_EventScript_Aisha_Item::
giveitem ITEM_GHOST_GEM

return

IslandCave_EventScript_Regice_Item::
finditem ITEM_BLUNDER_POLICY

return

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
finditem ITEM_SCANNER

return

Route111_EventScript_ItemElixir::
finditem ITEM_FULL_INCENSE

return

Route119_WeatherInstitute_2F_EventScript_ReceiveCastform_Item::
giveitem ITEM_TM72

return

FortreeCity_Gym_EventScript_Edwardo_Item::
giveitem ITEM_POISON_MEMORY

return

VictoryRoad_B2F_EventScript_ItemFullHeal::
finditem ITEM_DIRE_HIT

return

Route110_EventScript_Benjamin_Item::
giveitem ITEM_TM08

return

SeafloorCavern_Room9_EventScript_ArchieAwakenKyogre_Item::
giveitem ITEM_TM93

return

Route129_EventScript_Tisha_Item::
giveitem ITEM_DRAGON_MEMORY

return

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
finditem ITEM_LURE

return

AbandonedShip_Rooms2_1F_EventScript_Garrison_Item::
giveitem ITEM_WIDE_LENS

return

Route125_EventScript_Nolen_Item::
giveitem ITEM_DYNAMAX_CANDY

return

Route119_WeatherInstitute_1F_EventScript_Grunt1_Item::
giveitem ITEM_KEE_BERRY

return

RustboroCity_CuttersHouse_EventScript_Cutter_Item::
giveitem ITEM_HM01

return

VictoryRoad_B1F_EventScript_ItemTM29::
finditem ITEM_POWER_ANKLET

return

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
finditem ITEM_RUSTED_SHIELD

return

Route112_EventScript_Brice_Item::
giveitem ITEM_TM10

return

Route118_EventScript_ItemHyperPotion::
finditem ITEM_SMOKE_BALL

return

MauvilleCity_Gym_EventScript_Ben_Item::
giveitem ITEM_TANGA_BERRY

return

FortreeCity_Gym_EventScript_Humberto_Item::
giveitem ITEM_DIANCITE

return

MossdeepCity_Gym_EventScript_Macey_Item::
giveitem ITEM_RELIC_STATUE

return

SlateportCity_PokemonFanClub_EventScript_GivePinkScarf_Item::
giveitem ITEM_DESTINY_KNOT

return

Route105_EventScript_Foster_Item::
giveitem ITEM_SHARPEDONITE

return

Route120_EventScript_Robert_Item::
giveitem ITEM_BERRY_SWEET

return

SSTidalLowerDeck_EventScript_Phillip_Item::
giveitem ITEM_PINK_NECTAR

return

MauvilleCity_House1_EventScript_RockSmashDude_Item::
giveitem ITEM_HM06

return

NewMauville_Inside_EventScript_ItemUltraBall::
finditem ITEM_FLUFFY_TAIL

return

Route121_EventScript_Kate_Item::
giveitem ITEM_CAMERUPTITE

return

MtPyre_5F_EventScript_ItemLaxIncense::
finditem ITEM_SOOTHE_BELL

return

Route108_EventScript_Carolina_Item::
giveitem ITEM_SILVER_POWDER

return

VictoryRoad_B2F_EventScript_Caroline_Item::
giveitem ITEM_GARCHOMPITE

return

ArtisanCave_1F_EventScript_ItemCarbos::
finditem ITEM_NORMALIUM_Z

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle5_Item::
giveitem ITEM_MAX_MUSHROOMS

return

Route126_EventScript_Sienna_Item::
giveitem ITEM_FOSSILIZED_BIRD

return

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
finditem ITEM_POWER_HERB

return

MtPyre_Summit_EventScript_Grunt1_Item::
giveitem ITEM_TM50

return

LilycoveCity_EventScript_ItemMaxRepel::
finditem ITEM_LUCK_INCENSE

return

SootopolisCity_EventScript_GiveWaterfall_Item::
giveitem ITEM_HM07

return

Route120_EventScript_Jennifer_Item::
giveitem ITEM_RED_SCARF

return

Route114_EventScript_Shane_Item::
giveitem ITEM_PRIMARIUM_Z

return

Route110_EventScript_Edwin_Item::
giveitem ITEM_BEAD_MAIL

return

Route110_TrickHousePuzzle7_EventScript_Mariela_Item::
giveitem ITEM_STRANGE_SOUVENIR

return

AbandonedShip_Room_B1F_EventScript_ItemTM13::
finditem ITEM_LUMIOSE_GALETTE

return

Route115_EventScript_Alix_Item::
giveitem ITEM_WAVE_INCENSE

return

Route120_EventScript_Jeffrey_Item::
giveitem ITEM_BRIGHT_POWDER

return

Route123_EventScript_ItemElixir::
finditem ITEM_TM17

return

Route124_EventScript_Spencer_Item::
giveitem ITEM_TOXIC_PLATE

return

Route117_EventScript_Maria_Item::
giveitem ITEM_SHELL_BELL

return

Route108_EventScript_Missy_Item::
giveitem ITEM_BLUK_BERRY

return

VictoryRoad_B1F_EventScript_Michelle_Item::
giveitem ITEM_HELIX_FOSSIL

return

Route126_EventScript_ItemGreenShard::
finditem ITEM_X_ACCURACY

return

Drake_Item::
giveitem ITEM_TM80

return

MagmaHideout_3F_2R_EventScript_ItemPPMax::
finditem ITEM_RAGE_CANDY_BAR

return

Route131_EventScript_Herman_Item::
giveitem ITEM_PSYCHIC_MEMORY

return

Route123_EventScript_ItemCalcium::
finditem ITEM_TM73

return

VictoryRoad_B1F_EventScript_Halle_Item::
giveitem ITEM_SUPER_LURE

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle3_Item::
giveitem ITEM_SUN_STONE

return

Route104_EventScript_ItemPPUp::
finditem ITEM_KANGASKHANITE

return

Route125_EventScript_Sharon_Item::
giveitem ITEM_GENIUS_FEATHER

return

VictoryRoad_1F_EventScript_Hope_Item::
giveitem ITEM_RED_APRICORN

return

JaggedPass_EventScript_ItemBurnHeal::
finditem ITEM_GUARD_SPEC

return

Route109_EventScript_Hailey_Item::
giveitem ITEM_GRASSY_SEED

return

AbandonedShip_Rooms2_1F_EventScript_Kira_Item::
giveitem ITEM_TM91

return

Route107_EventScript_Darrin_Item::
giveitem ITEM_TM40

return

Mew_Item::
finditem ITEM_CLEVER_FEATHER

return

Route108_EventScript_Tara_Item::
giveitem ITEM_LAVA_COOKIE

return

SootopolisCity_LotadAndSeedotHouse_EventScript_BigSeedot_Item::
giveitem ITEM_MEDICHAMITE

return

JaggedPass_EventScript_Diana_Item::
giveitem ITEM_QUICK_POWDER

return

SlateportCity_Harbor_EventScript_DeepSeaTooth_Item::
giveitem ITEM_LEAF_STONE

return

MtPyre_Summit_EventScript_Grunt2_Item::
giveitem ITEM_ROOM_SERVICE

return

DewfordTown_Gym_EventScript_Jocelyn_Item::
giveitem ITEM_X_SPEED

return

MtPyre_Summit_EventScript_Grunt3_Item::
giveitem ITEM_RABUTA_BERRY

return

MagmaHideout_2F_2R_EventScript_Grunt6_Item::
giveitem ITEM_PEARL

return

MeteorFalls_1F_1R_EventScript_ItemTM23::
finditem ITEM_PRETTY_FEATHER

return

Route105_EventScript_Beverly_Item::
giveitem ITEM_TM100

return

VictoryRoad_B1F_EventScript_ItemFullRestore::
finditem ITEM_STEEL_GEM

return

FieryPath_EventScript_ItemFireStone::
finditem ITEM_TM59

return

Route119_EventScript_Rachel_Item::
giveitem ITEM_BIG_MALASADA

return

Route132_EventScript_Darcy_Item::
giveitem ITEM_ROCK_MEMORY

return

Fortree_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8EA
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route119_WeatherInstitute_2F_EventScript_Grunt3_Item::
giveitem ITEM_GOOEY_MULCH

return

AbandonedShip_Corridors_1F_EventScript_Charlie_Item::
giveitem ITEM_TERRAIN_EXTENDER

return

Route118_EventScript_Dalton_Item::
giveitem ITEM_TM56

return

Route117_EventScript_Lydia_Item::
giveitem ITEM_MYSTIC_WATER

return

LavaridgeTown_Gym_1F_EventScript_Danielle_Item::
giveitem ITEM_EJECT_PACK

return

JaggedPass_EventScript_Julio_Item::
giveitem ITEM_MAX_REPEL

return

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
finditem ITEM_DEEP_SEA_TOOTH

return

Route119_EventScript_Doug_Item::
giveitem ITEM_TM65

return

Route111_WinstrateFamilysHouse_EventScript_Vivi_Item::
giveitem ITEM_POISON_GEM

return

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
finditem ITEM_OLD_AMBER

return

SSTidalRooms_EventScript_Thomas_Item::
giveitem ITEM_CLAW_FOSSIL

return

Route115_EventScript_ItemIron::
finditem ITEM_GALARICA_CUFF

return

AquaHideout_B1F_EventScript_ItemNugget::
finditem ITEM_TM13

return

Route110_EventScript_Edward_Item::
giveitem ITEM_FAB_MAIL

return

Route110_TrickHousePuzzle2_EventScript_Ted_Item::
giveitem ITEM_COLBUR_BERRY

return

Route133_EventScript_Debra_Item::
giveitem ITEM_ORANGE_MAIL

return

Route108_EventScript_ItemStarPiece::
finditem ITEM_ADAMANT_ORB

return

Route123_EventScript_ItemRevivalHerb::
finditem ITEM_ALAKAZITE

return

Route124_EventScript_ItemRedShard::
finditem ITEM_PP_MAX

return

Route111_EventScript_Girl_Item::
giveitem ITEM_WOOD_MAIL

return

Route124_EventScript_ItemYellowShard::
finditem ITEM_SACHET

return

MauvilleCity_EventScript_CompletedNewMauville_Item::
giveitem ITEM_MAGMARIZER

return

Route123_EventScript_GigaDrainGirl_Item::
giveitem ITEM_ELECTRIUM_Z

return

Route119_EventScript_Fabian_Item::
giveitem ITEM_TM49

return

Gabby_Ty_EventScript_1_Item::
giveitem ITEM_TM16

return

Route110_EventScript_Jaclyn_Item::
giveitem ITEM_TM28

return

Route108_EventScript_Matthew_Item::
giveitem ITEM_LATIASITE

return

Route119_EventScript_GiveFlyHM_Item::
giveitem ITEM_HM02

return

Route123_EventScript_Miu_Item::
giveitem ITEM_MAGOST_BERRY

return

Route115_EventScript_Nob_Item::
giveitem ITEM_TM84

return

Route102_EventScript_ItemPotion::
finditem ITEM_TM53

return

Sootopolis_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8EC
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route130_EventScript_Katie_Item::
giveitem ITEM_RAZOR_CLAW

return

MtChimney_EventScript_MeteoriteMachine_Item::
giveitem ITEM_METEORITE

return

AquaHideout_B1F_EventScript_ItemMaxElixir::
finditem ITEM_TM33

return

Route123_EventScript_Jacki_Item::
giveitem ITEM_WHITE_HERB

return

MagmaHideout_2F_1R_EventScript_Grunt4_Item::
giveitem ITEM_TART_APPLE

return

Route111_EventScript_Daisuke_Item::
giveitem ITEM_BIG_MUSHROOM

return

Route111_EventScript_Celina_Item::
giveitem ITEM_TM78

return

PacifidlogTown_House2_EventScript_GiveFrustration_Item::
giveitem ITEM_GREEN_SCARF

return

Route110_TrickHousePuzzle1_EventScript_Sally_Item::
giveitem ITEM_BINDING_BAND

return

Route111_WinstrateFamilysHouse_EventScript_Vicky_Item::
giveitem ITEM_BLACK_GLASSES

return

PetalburgCity_Gym_EventScript_Alexia_Item::
giveitem ITEM_CHOICE_SPECS

return

Route121_EventScript_Marcel_Item::
giveitem ITEM_SALAC_BERRY

return

Route110_TrickHousePuzzle3_EventScript_Alan_Item::
giveitem ITEM_PIKANIUM_Z

return

AquaHideout_B1F_EventScript_Grunt5_Item::
giveitem ITEM_LOPUNNITE

return

NewMauville_Inside_EventScript_Voltorb1_Item::
finditem ITEM_TM25

return

Route129_EventScript_Chase_Item::
giveitem ITEM_GRASSIUM_Z

return

Glacia_Item::
giveitem ITEM_GREPA_BERRY

return

Route133_EventScript_Warren_Item::
giveitem ITEM_RELAXED_MINT

return

RusturfTunnel_EventScript_ItemPokeBall::
finditem ITEM_GOLD_BOTTLE_CAP

return

SeafloorCavern_Room4_EventScript_Grunt3_Item::
giveitem ITEM_ZOOM_LENS

return

Route115_EventScript_Helene_Item::
giveitem ITEM_HONEY

return

Route109_EventScript_Edmond_Item::
giveitem ITEM_SABLENITE

return

MossdeepCity_Gym_EventScript_Preston_Item::
giveitem ITEM_HARD_STONE

return

DewfordTown_House2_EventScript_Man_Item::
giveitem ITEM_KEBIA_BERRY

return

Route134_EventScript_Hitoshi_Item::
giveitem ITEM_HEAT_ROCK

return

Route114_EventScript_Tyra_Item::
giveitem ITEM_CHESTO_BERRY

return

AquaHideout_B2F_EventScript_Grunt8_Item::
giveitem ITEM_CHARIZARDITE_X

return

Route123_EventScript_ItemPPUp::
finditem ITEM_TM94

return

Route131_EventScript_Talia_Item::
giveitem ITEM_LUM_BERRY

return

LavaridgeTown_Gym_1F_EventScript_Cole_Item::
giveitem ITEM_DYNITE_ORE

return

SootopolisCity_Gym_B1F_EventScript_Andrea_Item::
giveitem ITEM_POWER_BELT

return

Route114_EventScript_Nancy_Item::
giveitem ITEM_PASSHO_BERRY

return

Route111_EventScript_Becky_Item::
giveitem ITEM_SHOAL_SALT

return

ArtisanCave_B1F_EventScript_ItemHPUp::
finditem ITEM_LUSTROUS_ORB

return

Route134_EventScript_Alex_Item::
giveitem ITEM_ALTARIANITE

return

Route129_EventScript_Allison_Item::
giveitem ITEM_DAMP_MULCH

return

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
finditem ITEM_INSECT_PLATE

return

Route111_WinstrateFamilysHouse_EventScript_Victoria_Item_Brace::
giveitem ITEM_TM60

return

Route110_EventScript_Kaleb_Item::
giveitem ITEM_TM89

return

Route107_EventScript_Camron_Item::
giveitem ITEM_EXP_CANDY_S

return

Route132_EventScript_Dana_Item::
giveitem ITEM_OVAL_STONE

return

Route134_EventScript_ItemCarbos::
finditem ITEM_EVERSTONE

return

SSTidalRooms_EventScript_Colton_Item::
giveitem ITEM_SKULL_FOSSIL

return

Route131_EventScript_Kara_Item::
giveitem ITEM_GANLON_BERRY

return

MagmaHideout_4F_EventScript_Grunt11_Item::
giveitem ITEM_NAIVE_MINT

return

AquaHideout_B1F_EventScript_Grunt2_Item::
giveitem ITEM_GHOST_MEMORY

return

VictoryRoad_1F_EventScript_Katelynn_Item::
giveitem ITEM_PIKASHUNIUM_Z

return

Route102_EventScript_Allen_Item::
giveitem ITEM_ICE_MEMORY

return

PetalburgCity_Gym_EventScript_Randall_Item::
giveitem ITEM_POWER_BRACER

return

Route134_EventScript_Laurel_Item::
giveitem ITEM_CUSTAP_BERRY

return

Route115_EventScript_ItemGreatBall::
finditem ITEM_ORAN_BERRY

return

MossdeepCity_Gym_EventScript_Blake_Item::
giveitem ITEM_LYCANIUM_Z

return

Route110_EventScript_ItemDireHit::
finditem ITEM_TM26

return

RustboroCity_Gym_EventScript_Tommy_Item::
giveitem ITEM_BLUE_APRICORN

return

MauvilleCity_Gym_EventScript_Wattson_Item::
giveitem ITEM_X_SPEED

return

SootopolisCity_Gym_B1F_EventScript_Connie_Item::
giveitem ITEM_REAPER_CLOTH

return

Route103_EventScript_ItemPPUp::
finditem ITEM_LONELY_MINT

return

Route126_EventScript_Leonardo_Item::
giveitem ITEM_FLUFFY_TAIL

return

SafariZone_Southeast_EventScript_ItemBigPearl::
finditem ITEM_QUICK_CLAW

return

Route134_EventScript_Jack_Item::
giveitem ITEM_ROOT_FOSSIL

return

Route114_EventScript_Steve_Item::
giveitem ITEM_LEEK

return

Route119_EventScript_Takashi_Item::
giveitem ITEM_SHOAL_SHELL

return

SlateportCity_PokemonFanClub_EventScript_GiveRedScarf_Item::
giveitem ITEM_MACHO_BRACE

return

Route110_TrickHousePuzzle7_EventScript_Patricia_Item::
giveitem ITEM_TM82

return

Route126_EventScript_Isobel_Item::
giveitem ITEM_MISTY_SEED

return

VictoryRoad_B1F_EventScript_Samuel_Item::
giveitem ITEM_X_SP_ATK

return

SootopolisCity_Gym_1F_EventScript_Juan_Item::
giveitem ITEM_ARMORITE_ORE

return

Route110_EventScript_GiveItemfinder_Item2::
giveitem ITEM_STARDUST

return

MossdeepCity_StevensHouse_EventScript_GiveBeldum_Item::
giveitem ITEM_MUSCLE_BAND

return

Route110_EventScript_Alyssa_Item::
giveitem ITEM_IRON_PLATE

return

Route117_EventScript_Brandi_Item::
giveitem ITEM_FIRE_GEM

return

Route110_TrickHousePuzzle1_EventScript_Robin_Item::
giveitem ITEM_RELIC_COPPER

return

SeafloorCavern_Room1_EventScript_Grunt1_Item::
giveitem ITEM_EXP_CANDY_L

return

Route127_EventScript_ItemRareCandy::
finditem ITEM_TM76

return

Route111_EventScript_Wilton_Item::
giveitem ITEM_BUG_MEMORY

return

AquaHideout_B1F_EventScript_Grunt3_Item::
giveitem ITEM_AMAZE_MULCH

return

MtPyre_Summit_EventScript_TeamAquaExits_Item::
giveitem ITEM_MAGMA_EMBLEM

return

MagmaHideout_3F_1R_EventScript_Grunt9_Item::
giveitem ITEM_PLUME_FOSSIL

return

Route110_TrickHousePuzzle7_EventScript_Alexis_Item::
giveitem ITEM_TM74

return

Route113_EventScript_ItemMaxEther::
finditem ITEM_ICE_GEM

return

Route120_EventScript_Angelica_Item::
giveitem ITEM_SEA_INCENSE

return

MossdeepCity_Gym_EventScript_Nicholas_Item::
giveitem ITEM_FLAME_PLATE

return

Route114_EventScript_Claude_Item::
giveitem ITEM_ZAP_PLATE

return

Route117_EventScript_ItemGreatBall::
finditem ITEM_TM77

return

DewfordTown_Hall_EventScript_SludgeBombMan_Item::
giveitem ITEM_RING_TARGET

return

LavaridgeTown_Gym_B1F_EventScript_Eli_Item::
giveitem ITEM_QUIET_MINT

return

MtPyre_2F_EventScript_Leah_Item::
giveitem ITEM_SHARP_BEAK

return

VictoryRoad_B2F_EventScript_Felix_Item::
giveitem ITEM_TM47

return

Route105_EventScript_Andres_Item::
giveitem ITEM_TM18

return

MtPyre_4F_EventScript_ItemSeaIncense::
finditem ITEM_TM67

return

LavaridgeTown_Gym_1F_EventScript_Flannery_Item::
giveitem ITEM_PIXIE_PLATE

return

VictoryRoad_1F_EventScript_ItemMaxElixir::
finditem ITEM_WHIPPED_DREAM

return

Route121_EventScript_ItemRevive::
finditem ITEM_PAYAPA_BERRY

return

Route128_EventScript_Harrison_Item::
giveitem ITEM_DAWN_STONE

return

Route111_EventScript_Drew_Item::
giveitem ITEM_POISON_BARB

return

Route119_EventScript_Donald_Item::
giveitem ITEM_TM32

return

Route119_EventScript_ItemElixir::
finditem ITEM_TM43

return

Route129_EventScript_Reed_Item::
giveitem ITEM_FOCUS_SASH

return

Route123_EventScript_Ed_Item::
giveitem ITEM_TM38

return

Route114_EventScript_Lucas_Item::
giveitem ITEM_WACAN_BERRY

return

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
finditem ITEM_EXP_CANDY_XS

return

AbandonedShip_Rooms2_1F_EventScript_Jani_Item::
giveitem ITEM_POWER_WEIGHT

return

Route119_EventScript_Chris_Item::
giveitem ITEM_WAVE_MAIL

return

Route126_EventScript_Brenda_Item::
giveitem ITEM_RELIC_CROWN

return

RustboroCity_EventScript_ReturnGoods_Item::
giveitem ITEM_ICY_ROCK

return

Route111_EventScript_ItemHPUp::
finditem ITEM_GRASS_MEMORY

return

Route116_EventScript_Karen_Item::
giveitem ITEM_SUPER_REPEL

return

Route109_EventScript_Elijah_Item::
giveitem ITEM_ELECTRIC_SEED

return

JaggedPass_EventScript_Autumn_Item::
giveitem ITEM_ASSAULT_VEST

return

AncientTomb_EventScript_Registeel_Item::
finditem ITEM_FLAME_ORB

return

Route114_EventScript_ItemProtein::
finditem ITEM_BIG_PEARL

return

MagmaHideout_1F_EventScript_ItemRareCandy::
finditem ITEM_RED_FLUTE

return

Route124_EventScript_Lila_Item::
giveitem ITEM_STARF_BERRY

return

Route113_EventScript_Sophie_Item::
giveitem ITEM_ICE_STONE

return

PetalburgCity_Gym_EventScript_Berke_Item::
giveitem ITEM_TM12

return

Gabby_Ty_EventScript_3_Item::
giveitem ITEM_HARBOR_MAIL

return

Route105_EventScript_Imani_Item::
giveitem ITEM_CAREFUL_MINT

return

Route119_WeatherInstitute_2F_EventScript_Shelly_Item::
giveitem ITEM_ULTRANECROZIUM_Z

return

MagmaHideout_3F_2R_EventScript_Grunt10_Item::
giveitem ITEM_ROCKIUM_Z

return

FortreeCity_Gym_EventScript_Darius_Item::
giveitem ITEM_SHINY_STONE

return

Route123_EventScript_Davis_Item::
giveitem ITEM_TM31

return

Route108_EventScript_Jerome_Item::
giveitem ITEM_METAL_POWDER

return

Route116_EventScript_Johnson_Item::
giveitem ITEM_CARBOS

return

Route106_EventScript_Elliot_Item::
giveitem ITEM_ROSELI_BERRY

return

Route133_EventScript_Beck_Item::
giveitem ITEM_ESCAPE_ROPE

return

Route116_EventScript_ItemEther::
finditem ITEM_TM58

return

MossdeepCity_Gym_EventScript_Sylvia_Item::
giveitem ITEM_BLACK_SLUDGE

return

NewMauville_Inside_EventScript_Voltorb3_Item::
finditem ITEM_FIGHTINIUM_Z

return

Route119_EventScript_ItemRareCandy::
finditem ITEM_STEELIXITE

return

SlateportCity_PokemonFanClub_EventScript_GiveBlueScarf_Item::
giveitem ITEM_ALORAICHIUM_Z

return

Route125_EventScript_Stan_Item::
giveitem ITEM_MODEST_MINT

return

MtPyre_1F_EventScript_CleanseTagWoman_Item::
giveitem ITEM_GENTLE_MINT

return

Route123_EventScript_Violet_Item::
giveitem ITEM_PINK_APRICORN

return

VerdanturfTown_BattleTentLobby_EventScript_AttractGiver_Item::
giveitem ITEM_HEALTH_FEATHER

return

Route114_EventScript_ItemEnergyPowder::
finditem ITEM_AGUAV_BERRY

return

Route128_EventScript_Ruben_Item::
giveitem ITEM_TAPUNIUM_Z

return

DesertUnderpass_EventScript_GiveClawFossil_Item::
giveitem ITEM_MIMIKIUM_Z

return

Route121_EventScript_Tammy_Item::
giveitem ITEM_COMET_SHARD

return

Route117_EventScript_Derek_Item::
giveitem ITEM_TM62

return

MtPyre_3F_EventScript_William_Item::
giveitem ITEM_HEART_SCALE

return

Route116_EventScript_ItemPotion::
finditem ITEM_SERIOUS_MINT

return

Route109_EventScript_Lola_Item::
giveitem ITEM_TM96

return

MtPyre_2F_EventScript_Zander_Item::
giveitem ITEM_DARKINIUM_Z

return

MossdeepCity_Gym_EventScript_Maura_Item::
giveitem ITEM_EXP_SHARE

return

Route118_EventScript_Barny_Item::
giveitem ITEM_AIR_BALLOON

return

AbandonedShip_Rooms_1F_Eventscript_Thalia_Item::
giveitem ITEM_NANAB_BERRY

return

Route119_EventScript_Greg_Item::
giveitem ITEM_SWIFT_FEATHER

return

LittlerootTown_ProfessorBirchsLab_EventScript_MayGivePokeBalls_Items::
giveitem ITEM_SHINY_CHARM

return

DewfordTown_EventScript_GiveOldRod_Item::
giveitem ITEM_OLD_ROD

return

Rustboro_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E5
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route109_SeashoreHouse_EventScript_Johanna_Item::
giveitem ITEM_MENTAL_HERB

return

PetalburgWoods_EventScript_James_Item::
giveitem ITEM_EEVIUM_Z

return

Route134_EventScript_Marley_Item::
giveitem ITEM_TM05

return

LilycoveCity_House2_EventScript_FatMan_Item::
giveitem ITEM_THROAT_SPRAY

return

MagmaHideout_2F_1R_EventScript_Grunt3_Item::
giveitem ITEM_CHILAN_BERRY

return

AquaHideout_1F_EventScript_Grunt1_Item::
giveitem ITEM_RED_NECTAR

return

Route119_EventScript_ItemZinc::
finditem ITEM_WEPEAR_BERRY

return

Route118_EventScript_Deandre_Item::
giveitem ITEM_CHARTI_BERRY

return

Route115_EventScript_Jaiden_Item::
giveitem ITEM_LIFE_ORB

return

Route103_EventScript_Item_Rival::
giveitem ITEM_ROCK_INCENSE

return

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
finditem ITEM_RESIST_FEATHER

return

Route113_EventScript_ItemSuperRepel::
finditem ITEM_ARMOR_FOSSIL

return

Route126_EventScript_Pablo_Item::
giveitem ITEM_RICH_MULCH

return

SlateportCity_PokemonFanClub_EventScript_GiveYellowScarf_Item::
giveitem ITEM_CHOPLE_BERRY

return

Route114_LanettesHouse_EventScript_Lanette_Item::
giveitem ITEM_DRAGONIUM_Z

return

Route107_EventScript_Beth_Item::
giveitem ITEM_POKE_TOY

return

Route120_EventScript_Riley_Item::
giveitem ITEM_CRACKED_POT

return

JaggedPass_EventScript_Ethan_Item::
giveitem ITEM_GARDEVOIRITE

return

Route110_TrickHousePuzzle6_EventScript_Sophia_Item::
giveitem ITEM_MIND_PLATE

return

VictoryRoad_B2F_EventScript_Owen_Item::
giveitem ITEM_STEEL_MEMORY

return

MtPyre_4F_EventScript_Tasha_Item::
giveitem ITEM_PURE_INCENSE

return

OldaleTown_EventScript_ExplainPokemonMart_Item::
giveitem ITEM_TM86

return

MagmaHideout_3F_1R_EventScript_Grunt16_Item::
giveitem ITEM_ADRENALINE_ORB

return

RustboroCity_Flat2_2F_EventScript_NinjaBoy_Item::
giveitem ITEM_OCCA_BERRY

return

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
finditem ITEM_THUNDER_STONE

return

Route125_EventScript_Kim_Item::
giveitem ITEM_ELECTRIC_MEMORY

return

Route111_EventScript_Irene_Item::
giveitem ITEM_YACHE_BERRY

return

Route110_EventScript_Abigail_Item::
giveitem ITEM_PURPLE_NECTAR

return

Route107_EventScript_Tony_Item::
giveitem ITEM_TM46

return

MagmaHideout_4F_EventScript_Tabitha_Item::
giveitem ITEM_YELLOW_NECTAR

return

MeteorFalls_1F_1R_EventScript_ItemPPUP::
finditem ITEM_DEEP_SEA_SCALE

return

Route112_EventScript_Shayla_Item::
giveitem ITEM_DARK_MEMORY

return

AquaHideout_B1F_EventScript_Electrode2_Item::
finditem ITEM_WATERIUM_Z

return

DewfordTown_Gym_EventScript_Brawly_Item::
giveitem ITEM_JABOCA_BERRY

return

Route119_EventScript_Taylor_Item::
giveitem ITEM_SHADOW_MAIL

return

Route116_EventScript_Devan_Item::
giveitem ITEM_FIGY_BERRY

return

Route123_EventScript_Braxton_Item::
giveitem ITEM_CHIPPED_POT

return

Route113_EventScript_Dillon_Item::
giveitem ITEM_BOOST_MULCH

return

Route132_EventScript_Ronald_Item::
giveitem ITEM_LUCKY_EGG

return

Route127_EventScript_ItemZinc::
finditem ITEM_BOTTLE_CAP

return

Route124_EventScript_Isabella_Item::
giveitem ITEM_IMPISH_MINT

return

SafariZone_Southwest_EventScript_ItemMaxRevive::
finditem ITEM_ROSE_INCENSE

return

Route115_EventScript_Timothy_Item::
giveitem ITEM_BUG_GEM

return

VictoryRoad_1F_EventScript_ItemPPUp::
finditem ITEM_FIGHTING_MEMORY

return

Route110_EventScript_Joseph_Item::
giveitem ITEM_TM36

return

PetalburgWoods_EventScript_Lyle_Item::
giveitem ITEM_NUGGET

return

Route126_EventScript_Barry_Item::
giveitem ITEM_METRONOME

return

Route111_EventScript_Hayden_Item::
giveitem ITEM_APICOT_BERRY

return

PetalburgWoods_EventScript_ItemEther::
finditem ITEM_CHARIZARDITE_Y

return

Route110_EventScript_Anthony_Item::
giveitem ITEM_TM39

return

Route124_EventScript_ItemBlueShard::
finditem ITEM_DUBIOUS_DISC

return

Route110_TrickHousePuzzle7_EventScript_Everett_Item::
giveitem ITEM_EVIOLITE

return

RusturfTunnel_EventScript_ClearTunnelScene_ITEM::
giveitem ITEM_HM04

return

Route110_TrickHousePuzzle8_EventScript_Vincent_Item::
giveitem ITEM_BIG_ROOT

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle6_Item::
giveitem ITEM_GROUND_MEMORY

return

LavaridgeTown_HerbShop_EventScript_OldMan_Item::
giveitem ITEM_GROUNDIUM_Z

return

RustboroCity_Gym_EventScript_Josh_Item::
giveitem ITEM_MAX_MUSHROOMS

return

JaggedPass_EventScript_MagmaHideoutGuard_Item::
giveitem ITEM_INCINIUM_Z

return

MauvilleCity_Gym_EventScript_Vivian_Item::
giveitem ITEM_DRAGON_FANG

return

LilycoveCity_EventScript_Rival_Item::
giveitem ITEM_RETRO_MAIL

return

FortreeCity_Gym_EventScript_Flint_Item::
giveitem ITEM_BANETTITE

return

SlateportCity_PokemonFanClub_EventScript_GiveGreenScarf_Item::
giveitem ITEM_WISE_GLASSES

return

SeafloorCavern_Room3_EventScript_Grunt5_Item::
giveitem ITEM_IAPAPA_BERRY

return

Route118_EventScript_ReceiveGoodRod_Item::
giveitem ITEM_GOOD_ROD

return

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
finditem ITEM_MICLE_BERRY

return

Route111_EventScript_Victor_Item::
giveitem ITEM_DREAM_MAIL

return

Route110_EventScript_Dale_Item::
giveitem ITEM_WATER_STONE

return

Route119_EventScript_ItemHyperPotion2::
finditem ITEM_GALLADITE

return

SeafloorCavern_Room1_EventScript_Grunt2_Item::
giveitem ITEM_CHOICE_BAND

return

SlateportCity_PokemonFanClub_EventScript_GiveSootheBell_Item::
giveitem ITEM_MECH_MAIL

return

Route115_EventScript_Koichi_Item::
giveitem ITEM_BUGINIUM_Z

return

SSTidalRooms_EventScript_Naomi_Item::
giveitem ITEM_DECIDIUM_Z

return

Route106_EventScript_ItemProtein::
finditem ITEM_TM03

return

MagmaHideout_2F_2R_EventScript_Grunt8_Item::
giveitem ITEM_TM90

return

MagmaHideout_2F_1R_EventScript_Grunt5_Item::
giveitem ITEM_RARE_CANDY

return

SSTidalRooms_EventScript_SnatchGiver_Item::
finditem ITEM_FIST_PLATE

return

MossdeepCity_StevensHouse_EventScript_StevenGivesDive_Item::
giveitem ITEM_HM08

return

Route133_EventScript_Linda_Item::
giveitem ITEM_X_SP_DEF

return

DesertRuins_EventScript_Regirock_Item::
finditem ITEM_SWEET_APPLE

return

Route112_EventScript_Carol_Item::
giveitem ITEM_WHITE_FLUTE

return

Route110_EventScript_GiveItemfinder_Item::
giveitem ITEM_DOWSING_MACHINE

return

Route107_EventScript_Denise_Item::
giveitem ITEM_MEWTWONITE_X

return

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
finditem ITEM_TM42

return

Route110_TrickHousePuzzle2_EventScript_Georgia_Item::
giveitem ITEM_WATER_MEMORY

return

VictoryRoad_1F_EventScript_Albert_Item::
giveitem ITEM_CORNN_BERRY

return

Route125_EventScript_Auron_Item::
giveitem ITEM_FOCUS_BAND

return

AquaHideout_B1F_EventScript_Electrode1_Item::
finditem ITEM_TM02

return

Route105_EventScript_Luis_Item::
giveitem ITEM_WISHING_PIECE

return

SSTidalRooms_EventScript_Jed_Item::
giveitem ITEM_TM98

return

MtPyre_3F_EventScript_Kayla_Item::
giveitem ITEM_TM24

return

PetalburgWoods_EventScript_ItemGreatBall::
giveitem ITEM_EARTH_PLATE

return

Route112_EventScript_ItemNugget::
finditem ITEM_DARK_GEM

return

PacifidlogTown_House2_EventScript_GiveReturn_Item::
giveitem ITEM_YELLOW_APRICORN

return

Route134_EventScript_Aaron_Item::
giveitem ITEM_HEAVY_DUTY_BOOTS

return

Route130_EventScript_Santiago_Item::
giveitem ITEM_PROTEIN

return

Route117_EventScript_ItemRevive::
finditem ITEM_TM71

return

Route125_EventScript_ItemBigPearl::
finditem ITEM_SLOWBRONITE

return

Route112_EventScript_Bryant_Item::
giveitem ITEM_AUDINITE

return

Route119_EventScript_ItemLeafStone::
finditem ITEM_X_ACCURACY

return

Route121_EventScript_Walter_Item::
giveitem ITEM_TM51

return

Route116_EventScript_Clark_Item::
giveitem ITEM_RAWST_BERRY

return

Route106_EventScript_Ned_Item::
giveitem ITEM_POWER_LENS

return

Route123_EventScript_Alberto_Item::
giveitem ITEM_RELIC_GOLD

return

Route110_TrickHousePuzzle8_EventScript_Leroy_Item::
giveitem ITEM_PEARL_STRING

return

Route110_TrickHousePuzzle6_EventScript_Benny_Item::
giveitem ITEM_BLASTOISINITE

return

Phoebe_Item::
giveitem ITEM_SOUL_DEW

return

Route109_EventScript_ItemPPUp::
finditem ITEM_PETAYA_BERRY

return

MtPyre_Exterior_EventScript_ItemMaxPotion::
finditem ITEM_RELIC_VASE

return

Route117_EventScript_Melina_Item::
giveitem ITEM_TM85

return

Route104_PrettyPetalFlowerShop_EventScript_GiveWailmerPail_ITEM::
giveitem ITEM_WAILMER_PAIL

return

RustboroCity_Gym_EventScript_Marc_Item::
giveitem ITEM_WHITE_APRICORN

return

Route119_EventScript_ItemElixir2::
finditem ITEM_POMEG_BERRY

return

Route113_EventScript_ItemHyperPotion::
finditem ITEM_TM45

return

Route110_EventScript_Jacob_Item::
giveitem ITEM_GLALITITE

return

MtPyre_2F_EventScript_Dez_Item::
giveitem ITEM_TM35

return

Route113_EventScript_Wyatt_Item::
giveitem ITEM_TM97

return

RustboroCity_Gym_EventScript_Roxanne_Item::
giveitem ITEM_BEEDRILLITE

return

Route121_EventScript_Pat_Item::
giveitem ITEM_AGGRONITE

return

Route120_EventScript_StevenGiveDeconScope_ITEM::
giveitem ITEM_DEVON_SCOPE

return

AbandonedShip_Corridors_B1F_EventScript_Duncan_Item::
giveitem ITEM_OVAL_CHARM

return

Route119_EventScript_Yasu_Item::
giveitem ITEM_RASH_MINT

return

Route109_SeashoreHouse_EventScript_Simon_Item::
giveitem ITEM_MANECTITE

return

Route106_EventScript_Kyla_Item::
giveitem ITEM_TM79

return

Route131_EventScript_Susie_Item::
giveitem ITEM_TYRANITARITE

return

Route132_EventScript_ItemRareCandy::
finditem ITEM_POWER_BAND

return

MagmaHideout_2F_2R_EventScript_Grunt7_Item::
giveitem ITEM_ABILITY_PATCH

return

Route125_EventScript_Presley_Item::
giveitem ITEM_STAR_PIECE

return

MtPyre_2F_EventScript_ItemUltraBall::
finditem ITEM_LUCARIONITE

return

Route128_EventScript_Katelyn_Item::
giveitem ITEM_JAW_FOSSIL

return

MagmaHideout_4F_EventScript_Grunt13_Item::
giveitem ITEM_YELLOW_SCARF

return

PetalburgWoods_EventScript_ItemXAttack::
giveitem ITEM_SCIZORITE

return

Route116_EventScript_Dawson_Item::
giveitem ITEM_NAUGHTY_MINT

return

Route120_EventScript_Colin_Item::
giveitem ITEM_TM95

return

Route123_EventScript_Frederick_Item::
giveitem ITEM_TM52

return

Route134_EventScript_Kelvin_Item::
giveitem ITEM_FOSSILIZED_FISH

return

VictoryRoad_1F_EventScript_Quincy_Item::
giveitem ITEM_ABILITY_CAPSULE

return

Route123_EventScript_Fernando_Item::
giveitem ITEM_TM09

return

VictoryRoad_B1F_EventScript_Shannon_Item::
giveitem ITEM_STICKY_BARB

return

Mauville_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_UNUSED_0x8E7
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT
return

Route128_EventScript_Carlee_Item::
giveitem ITEM_TM69

return

PetalburgCity_Gym_EventScript_Jody_Item::
giveitem ITEM_METAGROSSITE

return

Route120_EventScript_ItemFullHeal::
finditem ITEM_BLACK_FLUTE

return

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
finditem ITEM_TINY_MUSHROOM

return

Route119_EventScript_Kent_Item::
giveitem ITEM_TM55

return

SSTidalLowerDeck_EventScript_Leonard_Item::
giveitem ITEM_RAZZ_BERRY

return

Route132_EventScript_Gilbert_Item::
giveitem ITEM_TM66

return

Route131_EventScript_Kevin_Item::
giveitem ITEM_TIMID_MINT

return

DewfordTown_Gym_EventScript_Cristian_Item::
giveitem ITEM_PROTECTIVE_PADS

return

Route131_EventScript_Richard_Item::
giveitem ITEM_BLACK_APRICORN

return

Route114_EventScript_ItemRareCandy::
finditem ITEM_RIBBON_SWEET

return

MarineCave_End_EventScript_Kyogre_Item::
finditem ITEM_ROCK_GEM

return

Route109_EventScript_Huey_Item::
giveitem ITEM_PINK_SCARF

return

Route110_TrickHousePuzzle3_EventScript_Justin_Item::
giveitem ITEM_STONE_PLATE

return

Route116_EventScript_Joey_Item::
giveitem ITEM_WATER_GEM

return

AquaHideout_B2F_EventScript_Grunt6_Item::
giveitem ITEM_SHED_SHELL

return

Route117_EventScript_Dylan_Item::
giveitem ITEM_POISONIUM_Z

return

Route110_TrickHousePuzzle7_EventScript_Joshua_Item::
giveitem ITEM_SHUCA_BERRY

return

Route121_EventScript_Vanessa_Item::
giveitem ITEM_BOLD_MINT

return

LavaridgeTown_EventScript_MayGiveGoGoggles_ITEM::
giveitem ITEM_GO_GOGGLES

return

Route124_EventScript_Jenny_Item::
giveitem ITEM_MEADOW_PLATE

return

MeteorFalls_B1F_2R_EventScript_ItemTM02::
finditem ITEM_CALCIUM

return

Route109_EventScript_Mel_Item::
giveitem ITEM_TM19

return

Route119_EventScript_ItemSuperRepel::
finditem ITEM_TM22

return

Route110_TrickHousePuzzle3_EventScript_Martha_Item::
giveitem ITEM_SCOPE_LENS

return

Route109_EventScript_SoftSandGirl_ITEM::
giveitem ITEM_DREAD_PLATE

return

Route110_EventScript_ItemElixir::
finditem ITEM_KASIB_BERRY

return

Sydney_Item::
giveitem ITEM_BABIRI_BERRY

return

Route115_EventScript_ItemHealPowder::
finditem ITEM_GENGARITE

return

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
finditem ITEM_DIRE_HIT

return

Route134_EventScript_Hudson_Item::
giveitem ITEM_CALM_MINT

return

GraniteCave_B2F_EventScript_ItemRareCandy::
finditem ITEM_MAGO_BERRY

return

Route113_EventScript_Lao_Item::
giveitem ITEM_RED_CARD

return

Route109_SeashoreHouse_EventScript_DefeatedTrainers_Item::
giveitem ITEM_QUALOT_BERRY

return

Route113_EventScript_Lawrence_Item::
giveitem ITEM_LEPPA_BERRY

return

BirthIsland_Exterior_EventScript_Deoxys_Item::
finditem ITEM_TM14

return

Route113_EventScript_Lung_Item::
giveitem ITEM_RUSTED_SWORD

return

Route119_EventScript_Dayton_Item::
giveitem ITEM_MILD_MINT

return


trainer_items::
    switch VAR_TRAINER_BATTLE_OPPONENT_A

case TRAINER_GRUNT_MAGMA_HIDEOUT_1, MagmaHideout_1F_EventScript_Grunt1_Item
case TRAINER_LILITH, DewfordTown_Gym_EventScript_Lilith_Item
case TRAINER_TORI_AND_TIA, Route113_EventScript_Tori_Item
case TRAINER_DAPHNE, SootopolisCity_Gym_B1F_EventScript_Daphne_Item
case TRAINER_TIFFANY, SootopolisCity_Gym_B1F_EventScript_Tiffany_Item
case TRAINER_BRENDEN, DewfordTown_Gym_EventScript_Brenden_Item
case TRAINER_STEVEN, MeteorFalls_StevensCave_EventScript_Steven_Item
case TRAINER_MOLLIE, Route133_EventScript_Mollie_Item
case TRAINER_RODNEY, Route130_EventScript_Rodney_Item
case TRAINER_CALLIE, Route120_EventScript_Callie_Item
case TRAINER_GABBY_AND_TY_2, Gabby_Ty_EventScript_2_Item
case TRAINER_CEDRIC, MtPyre_6F_EventScript_Cedric_Item
case TRAINER_JAYLEN, Route113_EventScript_Jaylen_Item
case TRAINER_TIMMY, Route110_EventScript_Timmy_Item
case TRAINER_DAVID, Route109_EventScript_David_Item
case TRAINER_MAY_ROUTE_119_MUDKIP, Route119_EventScript_RivalExitScottArrive_Item
case TRAINER_DIANNE, VictoryRoad_B2F_EventScript_Dianne_Item
case TRAINER_NORMAN_1, PetalburgCity_Gym_EventScript_NormanBattle_Item
case TRAINER_DOUGLAS, Route106_EventScript_Douglas_Item
case TRAINER_HIDEO, Route119_EventScript_Hideo_Item
case TRAINER_MADELINE_1, Route113_EventScript_Madeline_Item
case TRAINER_CALVIN_1, Route102_EventScript_Calvin_Item
case TRAINER_LENNY, Route114_EventScript_Lenny_Item
case TRAINER_SHELLY_SEAFLOOR_CAVERN, SeafloorCavern_Room3_EventScript_Shelly_Item
case TRAINER_CHANDLER, Route109_EventScript_Chandler_Item
case TRAINER_JACKSON_1, Route119_EventScript_Jackson_Item
case TRAINER_LISA_AND_RAY, Route107_EventScript_Lisa_Item
case TRAINER_WENDY, Route123_EventScript_Wendy_Item
case TRAINER_KINDRA, Route123_EventScript_Kindra_Item
case TRAINER_WAYNE, Route128_EventScript_Wayne_Item
case TRAINER_ROLAND, Route124_EventScript_Roland_Item
case TRAINER_ALICE, Route109_EventScript_Alice_Item
case TRAINER_PAULA, Route110_TrickHousePuzzle4_EventScript_Paula_Item
case TRAINER_TYRON, Route111_EventScript_Tyron_Item
case TRAINER_MITCHELL, VictoryRoad_B1F_EventScript_Mitchell_Item
case TRAINER_TANYA, Route125_EventScript_Tanya_Item
case TRAINER_JEFF, LavaridgeTown_Gym_B1F_EventScript_Jeff_Item
case TRAINER_ERIC, JaggedPass_EventScript_Eric_Item
case TRAINER_LAURA, DewfordTown_Gym_EventScript_Laura_Item
case TRAINER_MARY, PetalburgCity_Gym_EventScript_Mary_Item
case TRAINER_VICTORIA, Route111_WinstrateFamilysHouse_EventScript_Victoria_Item
case TRAINER_LEONEL, Route120_EventScript_Leonel_Item
case TRAINER_GRUNT_SEAFLOOR_CAVERN_4, SeafloorCavern_Room4_EventScript_Grunt4_Item
case TRAINER_DWAYNE, Route109_SeashoreHouse_EventScript_Dwayne_Item
case TRAINER_RICKY_1, Route109_EventScript_Ricky_Item
case TRAINER_BEAU, Route111_EventScript_Beau_Item
case TRAINER_NATE, MossdeepCity_Gym_EventScript_Nate_Item
case TRAINER_JACE, LavaridgeTown_Gym_B1F_EventScript_Jace_Item
case TRAINER_CONOR, Route133_EventScript_Conor_Item
case TRAINER_JANICE, Route116_EventScript_Janice_Item
case TRAINER_GARRET, SSTidalRooms_EventScript_Garret_Item
case TRAINER_NIKKI, Route126_EventScript_Nikki_Item
case TRAINER_GRUNT_WEATHER_INST_5, Route119_WeatherInstitute_2F_EventScript_Grunt5_Item
case TRAINER_BRIANNA, SootopolisCity_Gym_B1F_EventScript_Brianna_Item
case TRAINER_CHARLOTTE, Route114_EventScript_Charlotte_Item
case TRAINER_ANNA_AND_MEG_1, Route117_EventScript_Anna_Item
case TRAINER_MARLENE, Route115_EventScript_Marlene_Item
case TRAINER_HEIDI, Route111_EventScript_Heidi_Item
case TRAINER_PERRY, Route118_EventScript_Perry_Item
case TRAINER_CHIP, Route120_EventScript_Chip_Item
case TRAINER_GEORGE, PetalburgCity_Gym_EventScript_George_Item
case TRAINER_KYRA, Route115_EventScript_Kyra_Item
case TRAINER_BRIDGET, SootopolisCity_Gym_B1F_EventScript_Bridget_Item
case TRAINER_AUSTINA, Route109_EventScript_Austina_Item
case TRAINER_TATE_AND_LIZA_1, MossdeepCity_Gym_EventScript_TateAndLiza_Item
case TRAINER_BRENT, Route119_EventScript_Brent_Item
case TRAINER_ANNIKA, SootopolisCity_Gym_B1F_EventScript_Annika_Item
case TRAINER_GRUNT_MT_PYRE_4, MtPyre_Summit_EventScript_Grunt4_Item
case TRAINER_YUJI, Route110_TrickHousePuzzle4_EventScript_Yuji_Item
case TRAINER_ERNEST_1, Route125_EventScript_Ernest_Item
case TRAINER_CLARISSA, Route120_EventScript_Clarissa_Item
case TRAINER_CYNDY_1, Route115_EventScript_Cyndy_Item
case TRAINER_ASHLEY, FortreeCity_Gym_EventScript_Ashley_Item
case TRAINER_CARTER, Route109_EventScript_Carter_Item
case TRAINER_CORA, Route110_TrickHousePuzzle4_EventScript_Cora_Item
case TRAINER_GRUNT_PETALBURG_WOODS, PetalburgWoods_EventScript_DevonResearcherLeft_Item
case TRAINER_BROOKE_1, Route111_EventScript_Brooke_Item
case TRAINER_MAXIE_MAGMA_HIDEOUT, MagmaHideout_4F_EventScript_Maxie_Item
case TRAINER_VALERIE_1, MtPyre_6F_EventScript_Valerie_Item
case TRAINER_BIANCA, Route111_EventScript_Bianca_Item
case TRAINER_PAUL, Route110_TrickHousePuzzle2_EventScript_Paul_Item
case TRAINER_TRAVIS, Route111_EventScript_Travis_Item
case TRAINER_KIRK, MauvilleCity_Gym_EventScript_Kirk_Item
case TRAINER_CLARENCE, Route129_EventScript_Clarence_Item
case TRAINER_MIKE_1, RusturfTunnel_EventScript_Mike_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_14, MagmaHideout_2F_1R_EventScript_Grunt14_Item
case TRAINER_GRUNT_WEATHER_INST_4, Route119_WeatherInstitute_1F_EventScript_Grunt4_Item
case TRAINER_HUGH, Route119_EventScript_Hugh_Item
case TRAINER_FRANKLIN, Route133_EventScript_Franklin_Item
case TRAINER_MATT, AquaHideout_B2F_EventScript_Matt_Item
case TRAINER_KEEGAN, LavaridgeTown_Gym_B1F_EventScript_Keegan_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_12, MagmaHideout_4F_EventScript_Grunt12_Item
case TRAINER_ISABEL_1, Route110_EventScript_Isabel_Item
case TRAINER_CORY_1, Route108_EventScript_Cory_Item
case TRAINER_WALLY_VR_1, VictoryRoad_1F_EventScript_WallyEntranceBattle_Item
case TRAINER_BETHANY, SootopolisCity_Gym_B1F_EventScript_Bethany_Item
case TRAINER_NICOLAS_1, MeteorFalls_1F_2R_EventScript_Nicolas_Item
case TRAINER_JOHN_AND_JAY_1, MeteorFalls_1F_2R_EventScript_John_Item
case TRAINER_CHESTER, Route118_EventScript_Chester_Item
case TRAINER_CALE, Route121_EventScript_Cale_Item
case TRAINER_JENNA, Route120_EventScript_Jenna_Item
case TRAINER_WALLY_MAUVILLE, MauvilleCity_EventScript_DefeatedWally_Item
case TRAINER_SAMANTHA, MossdeepCity_Gym_EventScript_Samantha_Item
case TRAINER_DEAN, Route126_EventScript_Dean_Item
case TRAINER_JARED, FortreeCity_Gym_EventScript_Jared_Item
case TRAINER_GRUNT_RUSTURF_TUNNEL, RusturfTunnel_EventScript_Grunt_Item_Two
case TRAINER_ISAIAH_1, Route128_EventScript_Isaiah_Item
case TRAINER_RELI_AND_IAN, Route131_EventScript_Reli_Item
case TRAINER_KATHLEEN, MossdeepCity_Gym_EventScript_Kathleen_Item
case TRAINER_JOSUE, Route105_EventScript_Josue_Item
case TRAINER_JONATHAN, Route132_EventScript_Jonathan_Item
case TRAINER_NOLAN, Route114_EventScript_Nolan_Item
case TRAINER_COBY, Route113_EventScript_Coby_Item
case TRAINER_BRANDEN, Route111_EventScript_Branden_Item
case TRAINER_HANNAH, MossdeepCity_Gym_EventScript_Hannah_Item
case TRAINER_GRUNT_WEATHER_INST_2, Route119_WeatherInstitute_2F_EventScript_Grunt2_Item
case TRAINER_CRISTIN_1, Route121_EventScript_Cristin_Item
case TRAINER_HECTOR, Route115_EventScript_Hector_Item
case TRAINER_MICAH, SSTidalRooms_EventScript_Micah_Item
case TRAINER_KEIGO, Route120_EventScript_Keigo_Item
case TRAINER_MARK, MtPyre_2F_EventScript_Mark_Item
case TRAINER_PHIL, Route119_EventScript_Phil_Item
case TRAINER_BERNIE_1, Route114_EventScript_Bernie_Item
case TRAINER_VIRGIL, MossdeepCity_Gym_EventScript_Virgil_Item
case TRAINER_AXLE, LavaridgeTown_Gym_1F_EventScript_Axle_Item
case TRAINER_SHAWN, MauvilleCity_Gym_EventScript_Shawn_Item
case TRAINER_CELIA, Route111_EventScript_Celia_Item
case TRAINER_CRISSY, SootopolisCity_Gym_B1F_EventScript_Crissy_Item
case TRAINER_JESSICA_1, Route121_EventScript_Jessica_Item
case TRAINER_RICK, Route102_EventScript_Rick_Item
case TRAINER_SARAH, Route116_EventScript_Sarah_Item
case TRAINER_EDDIE, Route110_TrickHousePuzzle1_EventScript_Eddie_Item
case TRAINER_GERALD, LavaridgeTown_Gym_1F_EventScript_Gerald_Item
case TRAINER_OLIVIA, SootopolisCity_Gym_B1F_EventScript_Olivia_Item
case TRAINER_ANGELINA, Route114_EventScript_Angelina_Item
case TRAINER_CLIFFORD, MossdeepCity_Gym_EventScript_Clifford_Item
case TRAINER_WINONA_1, FortreeCity_Gym_EventScript_Winona_Item
case TRAINER_ALVARO, Route110_TrickHousePuzzle7_EventScript_Alvaro_Item
case TRAINER_BRYAN, Route111_EventScript_Bryan_Item
case TRAINER_JERRY_1, Route116_EventScript_Jerry_Item
case TRAINER_ANGELO, MauvilleCity_Gym_EventScript_Angelo_Item
case TRAINER_REYNA, Route134_EventScript_Reyna_Item
case TRAINER_GRUNT_AQUA_HIDEOUT_7, AquaHideout_B1F_EventScript_Grunt7_Item
case TRAINER_DOMINIK, Route105_EventScript_Dominik_Item
case TRAINER_CATHERINE_1, Route119_EventScript_Catherine_Item
case TRAINER_KIYO, Route132_EventScript_Kiyo_Item
case TRAINER_PAXTON, Route132_EventScript_Paxton_Item
case TRAINER_DUSTY_1, Route111_EventScript_Dusty_Item
case TRAINER_ROSE_1, Route118_EventScript_Rose_Item
case TRAINER_ATSUSHI, MtPyre_5F_EventScript_Atsushi_Item
case TRAINER_EDGAR, VictoryRoad_1F_EventScript_Edgar_Item
case TRAINER_PARKER, PetalburgCity_Gym_EventScript_Parker_Item
case TRAINER_SEBASTIAN, Route110_TrickHousePuzzle6_EventScript_Sebastian_Item
case TRAINER_MYLES, Route121_EventScript_Myles_Item
case TRAINER_ALEXA, Route128_EventScript_Alexa_Item
case TRAINER_GRUNT_AQUA_HIDEOUT_4, AquaHideout_B2F_EventScript_Grunt4_Item
case TRAINER_JAZMYN, Route123_EventScript_Jazmyn_Item
case TRAINER_WADE, Route118_EventScript_Wade_Item
case TRAINER_JULIE, VictoryRoad_B2F_EventScript_Julie_Item
case TRAINER_TIANA, Route102_EventScript_Tiana_Item
case TRAINER_LORENZO, Route120_EventScript_Lorenzo_Item
case TRAINER_GRACE, Route124_EventScript_Grace_Item
case TRAINER_DEMETRIUS, AbandonedShip_Rooms_1F_EventScript_Demetrius_Item
case TRAINER_CHAD, Route124_EventScript_Chad_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_2, MagmaHideout_1F_EventScript_Grunt2_Item
case TRAINER_ISAAC_1, Route117_EventScript_Isaac_Item
case TRAINER_DECLAN, Route124_EventScript_Declan_Item
case TRAINER_JASMINE, Route110_EventScript_Jasmine_Item
case TRAINER_KAI, Route114_EventScript_Kai_Item
case TRAINER_JOSE, Route116_EventScript_Jose_Item
case TRAINER_GWEN, Route109_EventScript_Gwen_Item
case TRAINER_LARRY, Route112_EventScript_Larry_Item
case TRAINER_KEIRA, Route110_TrickHousePuzzle8_EventScript_Keira_Item
case TRAINER_TRENT_1, Route112_EventScript_Trent_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_15, MagmaHideout_2F_2R_EventScript_Grunt15_Item
case TRAINER_VITO, VictoryRoad_B2F_EventScript_Vito_Item
case TRAINER_GABRIELLE_1, MtPyre_3F_EventScript_Gabrielle_Item
case TRAINER_MAKAYLA, Route132_EventScript_Makayla_Item
case TRAINER_AISHA, Route117_EventScript_Aisha_Item
case TRAINER_EDWARDO, FortreeCity_Gym_EventScript_Edwardo_Item
case TRAINER_BENJAMIN_1, Route110_EventScript_Benjamin_Item
case TRAINER_ARCHIE, SeafloorCavern_Room9_EventScript_ArchieAwakenKyogre_Item
case TRAINER_TISHA, Route129_EventScript_Tisha_Item
case TRAINER_GARRISON, AbandonedShip_Rooms2_1F_EventScript_Garrison_Item
case TRAINER_NOLEN, Route125_EventScript_Nolen_Item
case TRAINER_GRUNT_WEATHER_INST_1, Route119_WeatherInstitute_1F_EventScript_Grunt1_Item
case TRAINER_BRICE, Route112_EventScript_Brice_Item
case TRAINER_BEN, MauvilleCity_Gym_EventScript_Ben_Item
case TRAINER_HUMBERTO, FortreeCity_Gym_EventScript_Humberto_Item
case TRAINER_MACEY, MossdeepCity_Gym_EventScript_Macey_Item
case TRAINER_FOSTER, Route105_EventScript_Foster_Item
case TRAINER_ROBERT_1, Route120_EventScript_Robert_Item
case TRAINER_PHILLIP, SSTidalLowerDeck_EventScript_Phillip_Item
case TRAINER_KATE_AND_JOY, Route121_EventScript_Kate_Item
case TRAINER_CAROLINA, Route108_EventScript_Carolina_Item
case TRAINER_CAROLINE, VictoryRoad_B2F_EventScript_Caroline_Item
case TRAINER_SIENNA, Route126_EventScript_Sienna_Item
case TRAINER_GRUNT_MT_PYRE_1, MtPyre_Summit_EventScript_Grunt1_Item
case TRAINER_JENNIFER, Route120_EventScript_Jennifer_Item
case TRAINER_SHANE, Route114_EventScript_Shane_Item
case TRAINER_EDWIN_1, Route110_EventScript_Edwin_Item
case TRAINER_MARIELA, Route110_TrickHousePuzzle7_EventScript_Mariela_Item
case TRAINER_ALIX, Route115_EventScript_Alix_Item
case TRAINER_JEFFREY_1, Route120_EventScript_Jeffrey_Item
case TRAINER_SPENCER, Route124_EventScript_Spencer_Item
case TRAINER_MARIA_1, Route117_EventScript_Maria_Item
case TRAINER_MISSY, Route108_EventScript_Missy_Item
case TRAINER_MICHELLE, VictoryRoad_B1F_EventScript_Michelle_Item
case TRAINER_DRAKE, Drake_Item
case TRAINER_HERMAN, Route131_EventScript_Herman_Item
case TRAINER_HALLE, VictoryRoad_B1F_EventScript_Halle_Item
case TRAINER_SHARON, Route125_EventScript_Sharon_Item
case TRAINER_HOPE, VictoryRoad_1F_EventScript_Hope_Item
case TRAINER_HAILEY, Route109_EventScript_Hailey_Item
case TRAINER_KIRA_AND_DAN_1, AbandonedShip_Rooms2_1F_EventScript_Kira_Item
case TRAINER_DARRIN, Route107_EventScript_Darrin_Item
case TRAINER_TARA, Route108_EventScript_Tara_Item
case TRAINER_DIANA_1, JaggedPass_EventScript_Diana_Item
case TRAINER_GRUNT_MT_PYRE_2, MtPyre_Summit_EventScript_Grunt2_Item
case TRAINER_JOCELYN, DewfordTown_Gym_EventScript_Jocelyn_Item
case TRAINER_GRUNT_MT_PYRE_3, MtPyre_Summit_EventScript_Grunt3_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_6, MagmaHideout_2F_2R_EventScript_Grunt6_Item
case TRAINER_BEVERLY, Route105_EventScript_Beverly_Item
case TRAINER_RACHEL, Route119_EventScript_Rachel_Item
case TRAINER_DARCY, Route132_EventScript_Darcy_Item
case TRAINER_GRUNT_WEATHER_INST_3, Route119_WeatherInstitute_2F_EventScript_Grunt3_Item
case TRAINER_CHARLIE, AbandonedShip_Corridors_1F_EventScript_Charlie_Item
case TRAINER_DALTON_1, Route118_EventScript_Dalton_Item
case TRAINER_LYDIA_1, Route117_EventScript_Lydia_Item
case TRAINER_DANIELLE, LavaridgeTown_Gym_1F_EventScript_Danielle_Item
case TRAINER_JULIO, JaggedPass_EventScript_Julio_Item
case TRAINER_DOUG, Route119_EventScript_Doug_Item
case TRAINER_VIVI, Route111_WinstrateFamilysHouse_EventScript_Vivi_Item
case TRAINER_THOMAS, SSTidalRooms_EventScript_Thomas_Item
case TRAINER_EDWARD, Route110_EventScript_Edward_Item
case TRAINER_TED, Route110_TrickHousePuzzle2_EventScript_Ted_Item
case TRAINER_DEBRA, Route133_EventScript_Debra_Item
case TRAINER_FABIAN, Route119_EventScript_Fabian_Item
case TRAINER_GABBY_AND_TY_1, Gabby_Ty_EventScript_1_Item
case TRAINER_JACLYN, Route110_EventScript_Jaclyn_Item
case TRAINER_MATTHEW, Route108_EventScript_Matthew_Item
case TRAINER_MIU_AND_YUKI, Route123_EventScript_Miu_Item
case TRAINER_NOB_1, Route115_EventScript_Nob_Item
case TRAINER_KATIE, Route130_EventScript_Katie_Item
case TRAINER_JACKI_1, Route123_EventScript_Jacki_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_4, MagmaHideout_2F_1R_EventScript_Grunt4_Item
case TRAINER_DAISUKE, Route111_EventScript_Daisuke_Item
case TRAINER_CELINA, Route111_EventScript_Celina_Item
case TRAINER_SALLY, Route110_TrickHousePuzzle1_EventScript_Sally_Item
case TRAINER_VICKY, Route111_WinstrateFamilysHouse_EventScript_Vicky_Item
case TRAINER_ALEXIA, PetalburgCity_Gym_EventScript_Alexia_Item
case TRAINER_MARCEL, Route121_EventScript_Marcel_Item
case TRAINER_ALAN, Route110_TrickHousePuzzle3_EventScript_Alan_Item
case TRAINER_GRUNT_AQUA_HIDEOUT_5, AquaHideout_B1F_EventScript_Grunt5_Item
case TRAINER_CHASE, Route129_EventScript_Chase_Item
case TRAINER_GLACIA, Glacia_Item
case TRAINER_WARREN, Route133_EventScript_Warren_Item
case TRAINER_GRUNT_SEAFLOOR_CAVERN_3, SeafloorCavern_Room4_EventScript_Grunt3_Item
case TRAINER_HELENE, Route115_EventScript_Helene_Item
case TRAINER_EDMOND, Route109_EventScript_Edmond_Item
case TRAINER_PRESTON, MossdeepCity_Gym_EventScript_Preston_Item
case TRAINER_HITOSHI, Route134_EventScript_Hitoshi_Item
case TRAINER_TYRA_AND_IVY, Route114_EventScript_Tyra_Item
case TRAINER_GRUNT_AQUA_HIDEOUT_8, AquaHideout_B2F_EventScript_Grunt8_Item
case TRAINER_TALIA, Route131_EventScript_Talia_Item
case TRAINER_COLE, LavaridgeTown_Gym_1F_EventScript_Cole_Item
case TRAINER_ANDREA, SootopolisCity_Gym_B1F_EventScript_Andrea_Item
case TRAINER_NANCY, Route114_EventScript_Nancy_Item
case TRAINER_BECKY, Route111_EventScript_Becky_Item
case TRAINER_ALEX, Route134_EventScript_Alex_Item
case TRAINER_ALLISON, Route129_EventScript_Allison_Item
case TRAINER_KALEB, Route110_EventScript_Kaleb_Item
case TRAINER_CAMRON, Route107_EventScript_Camron_Item
case TRAINER_DANA, Route132_EventScript_Dana_Item
case TRAINER_COLTON, SSTidalRooms_EventScript_Colton_Item
case TRAINER_KARA, Route131_EventScript_Kara_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_11, MagmaHideout_4F_EventScript_Grunt11_Item
case TRAINER_GRUNT_AQUA_HIDEOUT_2, AquaHideout_B1F_EventScript_Grunt2_Item
case TRAINER_KATELYNN, VictoryRoad_1F_EventScript_Katelynn_Item
case TRAINER_ALLEN, Route102_EventScript_Allen_Item
case TRAINER_RANDALL, PetalburgCity_Gym_EventScript_Randall_Item
case TRAINER_LAUREL, Route134_EventScript_Laurel_Item
case TRAINER_BLAKE, MossdeepCity_Gym_EventScript_Blake_Item
case TRAINER_TOMMY, RustboroCity_Gym_EventScript_Tommy_Item
case TRAINER_WATTSON_1, MauvilleCity_Gym_EventScript_Wattson_Item
case TRAINER_CONNIE, SootopolisCity_Gym_B1F_EventScript_Connie_Item
case TRAINER_LEONARDO, Route126_EventScript_Leonardo_Item
case TRAINER_JACK, Route134_EventScript_Jack_Item
case TRAINER_STEVE_1, Route114_EventScript_Steve_Item
case TRAINER_TAKASHI, Route119_EventScript_Takashi_Item
case TRAINER_PATRICIA, Route110_TrickHousePuzzle7_EventScript_Patricia_Item
case TRAINER_ISOBEL, Route126_EventScript_Isobel_Item
case TRAINER_SAMUEL, VictoryRoad_B1F_EventScript_Samuel_Item
case TRAINER_JUAN_1, SootopolisCity_Gym_1F_EventScript_Juan_Item
case TRAINER_MAY_ROUTE_110_MUDKIP, Route110_EventScript_GiveItemfinder_Item2
case TRAINER_ALYSSA, Route110_EventScript_Alyssa_Item
case TRAINER_BRANDI, Route117_EventScript_Brandi_Item
case TRAINER_ROBIN, Route110_TrickHousePuzzle1_EventScript_Robin_Item
case TRAINER_GRUNT_SEAFLOOR_CAVERN_1, SeafloorCavern_Room1_EventScript_Grunt1_Item
case TRAINER_WILTON_1, Route111_EventScript_Wilton_Item
case TRAINER_GRUNT_AQUA_HIDEOUT_3, AquaHideout_B1F_EventScript_Grunt3_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_9, MagmaHideout_3F_1R_EventScript_Grunt9_Item
case TRAINER_ALEXIS, Route110_TrickHousePuzzle7_EventScript_Alexis_Item
case TRAINER_ANGELICA, Route120_EventScript_Angelica_Item
case TRAINER_NICHOLAS, MossdeepCity_Gym_EventScript_Nicholas_Item
case TRAINER_CLAUDE, Route114_EventScript_Claude_Item
case TRAINER_ELI, LavaridgeTown_Gym_B1F_EventScript_Eli_Item
case TRAINER_LEAH, MtPyre_2F_EventScript_Leah_Item
case TRAINER_FELIX, VictoryRoad_B2F_EventScript_Felix_Item
case TRAINER_ANDRES_1, Route105_EventScript_Andres_Item
case TRAINER_FLANNERY_1, LavaridgeTown_Gym_1F_EventScript_Flannery_Item
case TRAINER_HARRISON, Route128_EventScript_Harrison_Item
case TRAINER_DREW, Route111_EventScript_Drew_Item
case TRAINER_DONALD, Route119_EventScript_Donald_Item
case TRAINER_REED, Route129_EventScript_Reed_Item
case TRAINER_ED, Route123_EventScript_Ed_Item
case TRAINER_LUCAS_1, Route114_EventScript_Lucas_Item
case TRAINER_JANI, AbandonedShip_Rooms2_1F_EventScript_Jani_Item
case TRAINER_CHRIS, Route119_EventScript_Chris_Item
case TRAINER_BRENDA, Route126_EventScript_Brenda_Item
case TRAINER_KAREN_1, Route116_EventScript_Karen_Item
case TRAINER_ELIJAH, Route109_EventScript_Elijah_Item
case TRAINER_AUTUMN, JaggedPass_EventScript_Autumn_Item
case TRAINER_LILA_AND_ROY_1, Route124_EventScript_Lila_Item
case TRAINER_SOPHIE, Route113_EventScript_Sophie_Item
case TRAINER_BERKE, PetalburgCity_Gym_EventScript_Berke_Item
case TRAINER_GABBY_AND_TY_3, Gabby_Ty_EventScript_3_Item
case TRAINER_IMANI, Route105_EventScript_Imani_Item
case TRAINER_SHELLY_WEATHER_INSTITUTE, Route119_WeatherInstitute_2F_EventScript_Shelly_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_10, MagmaHideout_3F_2R_EventScript_Grunt10_Item
case TRAINER_DARIUS, FortreeCity_Gym_EventScript_Darius_Item
case TRAINER_DAVIS, Route123_EventScript_Davis_Item
case TRAINER_JEROME, Route108_EventScript_Jerome_Item
case TRAINER_JOHNSON, Route116_EventScript_Johnson_Item
case TRAINER_ELLIOT_1, Route106_EventScript_Elliot_Item
case TRAINER_BECK, Route133_EventScript_Beck_Item
case TRAINER_SYLVIA, MossdeepCity_Gym_EventScript_Sylvia_Item
case TRAINER_STAN, Route125_EventScript_Stan_Item
case TRAINER_VIOLET, Route123_EventScript_Violet_Item
case TRAINER_RUBEN, Route128_EventScript_Ruben_Item
case TRAINER_TAMMY, Route121_EventScript_Tammy_Item
case TRAINER_DEREK, Route117_EventScript_Derek_Item
case TRAINER_WILLIAM, MtPyre_3F_EventScript_William_Item
case TRAINER_LOLA_1, Route109_EventScript_Lola_Item
case TRAINER_ZANDER, MtPyre_2F_EventScript_Zander_Item
case TRAINER_MAURA, MossdeepCity_Gym_EventScript_Maura_Item
case TRAINER_BARNY, Route118_EventScript_Barny_Item
case TRAINER_THALIA_1, AbandonedShip_Rooms_1F_Eventscript_Thalia_Item
case TRAINER_GREG, Route119_EventScript_Greg_Item
case TRAINER_JOHANNA, Route109_SeashoreHouse_EventScript_Johanna_Item
case TRAINER_JAMES_1, PetalburgWoods_EventScript_James_Item
case TRAINER_MARLEY, Route134_EventScript_Marley_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_3, MagmaHideout_2F_1R_EventScript_Grunt3_Item
case TRAINER_GRUNT_AQUA_HIDEOUT_1, AquaHideout_1F_EventScript_Grunt1_Item
case TRAINER_DEANDRE, Route118_EventScript_Deandre_Item
case TRAINER_JAIDEN, Route115_EventScript_Jaiden_Item
case TRAINER_MAY_ROUTE_103_MUDKIP, Route103_EventScript_Item_Rival
case TRAINER_PABLO_1, Route126_EventScript_Pablo_Item
case TRAINER_BETH, Route107_EventScript_Beth_Item
case TRAINER_RILEY, Route120_EventScript_Riley_Item
case TRAINER_ETHAN_1, JaggedPass_EventScript_Ethan_Item
case TRAINER_SOPHIA, Route110_TrickHousePuzzle6_EventScript_Sophia_Item
case TRAINER_OWEN, VictoryRoad_B2F_EventScript_Owen_Item
case TRAINER_TASHA, MtPyre_4F_EventScript_Tasha_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_16, MagmaHideout_3F_1R_EventScript_Grunt16_Item
case TRAINER_KIM_AND_IRIS, Route125_EventScript_Kim_Item
case TRAINER_IRENE, Route111_EventScript_Irene_Item
case TRAINER_ABIGAIL_1, Route110_EventScript_Abigail_Item
case TRAINER_TONY_1, Route107_EventScript_Tony_Item
case TRAINER_TABITHA_MAGMA_HIDEOUT, MagmaHideout_4F_EventScript_Tabitha_Item
case TRAINER_SHAYLA, Route112_EventScript_Shayla_Item
case TRAINER_BRAWLY_1, DewfordTown_Gym_EventScript_Brawly_Item
case TRAINER_TAYLOR, Route119_EventScript_Taylor_Item
case TRAINER_DEVAN, Route116_EventScript_Devan_Item
case TRAINER_BRAXTON, Route123_EventScript_Braxton_Item
case TRAINER_DILLON, Route113_EventScript_Dillon_Item
case TRAINER_RONALD, Route132_EventScript_Ronald_Item
case TRAINER_ISABELLA, Route124_EventScript_Isabella_Item
case TRAINER_TIMOTHY_1, Route115_EventScript_Timothy_Item
case TRAINER_JOSEPH, Route110_EventScript_Joseph_Item
case TRAINER_LYLE, PetalburgWoods_EventScript_Lyle_Item
case TRAINER_BARRY, Route126_EventScript_Barry_Item
case TRAINER_HAYDEN, Route111_EventScript_Hayden_Item
case TRAINER_ANTHONY, Route110_EventScript_Anthony_Item
case TRAINER_EVERETT, Route110_TrickHousePuzzle7_EventScript_Everett_Item
case TRAINER_VINCENT, Route110_TrickHousePuzzle8_EventScript_Vincent_Item
case TRAINER_JOSH, RustboroCity_Gym_EventScript_Josh_Item
case TRAINER_GRUNT_JAGGED_PASS, JaggedPass_EventScript_MagmaHideoutGuard_Item
case TRAINER_VIVIAN, MauvilleCity_Gym_EventScript_Vivian_Item
case TRAINER_MAY_LILYCOVE_MUDKIP, LilycoveCity_EventScript_Rival_Item
case TRAINER_FLINT, FortreeCity_Gym_EventScript_Flint_Item
case TRAINER_GRUNT_SEAFLOOR_CAVERN_5, SeafloorCavern_Room3_EventScript_Grunt5_Item
case TRAINER_VICTOR, Route111_EventScript_Victor_Item
case TRAINER_DALE, Route110_EventScript_Dale_Item
case TRAINER_GRUNT_SEAFLOOR_CAVERN_2, SeafloorCavern_Room1_EventScript_Grunt2_Item
case TRAINER_KOICHI, Route115_EventScript_Koichi_Item
case TRAINER_NAOMI, SSTidalRooms_EventScript_Naomi_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_8, MagmaHideout_2F_2R_EventScript_Grunt8_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_5, MagmaHideout_2F_1R_EventScript_Grunt5_Item
case TRAINER_LINDA, Route133_EventScript_Linda_Item
case TRAINER_CAROL, Route112_EventScript_Carol_Item
case TRAINER_DENISE, Route107_EventScript_Denise_Item
case TRAINER_GEORGIA, Route110_TrickHousePuzzle2_EventScript_Georgia_Item
case TRAINER_ALBERT, VictoryRoad_1F_EventScript_Albert_Item
case TRAINER_AURON, Route125_EventScript_Auron_Item
case TRAINER_LUIS, Route105_EventScript_Luis_Item
case TRAINER_LEA_AND_JED, SSTidalRooms_EventScript_Jed_Item
case TRAINER_KAYLA, MtPyre_3F_EventScript_Kayla_Item
case TRAINER_AARON, Route134_EventScript_Aaron_Item
case TRAINER_SANTIAGO, Route130_EventScript_Santiago_Item
case TRAINER_BRYANT, Route112_EventScript_Bryant_Item
case TRAINER_WALTER_1, Route121_EventScript_Walter_Item
case TRAINER_CLARK, Route116_EventScript_Clark_Item
case TRAINER_NED, Route106_EventScript_Ned_Item
case TRAINER_ALBERTO, Route123_EventScript_Alberto_Item
case TRAINER_LEROY, Route110_TrickHousePuzzle8_EventScript_Leroy_Item
case TRAINER_BENNY, Route110_TrickHousePuzzle6_EventScript_Benny_Item
case TRAINER_PHOEBE, Phoebe_Item
case TRAINER_MELINA, Route117_EventScript_Melina_Item
case TRAINER_MARC, RustboroCity_Gym_EventScript_Marc_Item
case TRAINER_JACOB, Route110_EventScript_Jacob_Item
case TRAINER_DEZ_AND_LUKE, MtPyre_2F_EventScript_Dez_Item
case TRAINER_WYATT, Route113_EventScript_Wyatt_Item
case TRAINER_ROXANNE_1, RustboroCity_Gym_EventScript_Roxanne_Item
case TRAINER_PAT, Route121_EventScript_Pat_Item
case TRAINER_DUNCAN, AbandonedShip_Corridors_B1F_EventScript_Duncan_Item
case TRAINER_YASU, Route119_EventScript_Yasu_Item
case TRAINER_SIMON, Route109_SeashoreHouse_EventScript_Simon_Item
case TRAINER_KYLA, Route106_EventScript_Kyla_Item
case TRAINER_SUSIE, Route131_EventScript_Susie_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_7, MagmaHideout_2F_2R_EventScript_Grunt7_Item
case TRAINER_PRESLEY, Route125_EventScript_Presley_Item
case TRAINER_KATELYN_1, Route128_EventScript_Katelyn_Item
case TRAINER_GRUNT_MAGMA_HIDEOUT_13, MagmaHideout_4F_EventScript_Grunt13_Item
case TRAINER_DAWSON, Route116_EventScript_Dawson_Item
case TRAINER_COLIN, Route120_EventScript_Colin_Item
case TRAINER_FREDRICK, Route123_EventScript_Frederick_Item
case TRAINER_KELVIN, Route134_EventScript_Kelvin_Item
case TRAINER_QUINCY, VictoryRoad_1F_EventScript_Quincy_Item
case TRAINER_FERNANDO_1, Route123_EventScript_Fernando_Item
case TRAINER_SHANNON, VictoryRoad_B1F_EventScript_Shannon_Item
case TRAINER_CARLEE, Route128_EventScript_Carlee_Item
case TRAINER_JODY, PetalburgCity_Gym_EventScript_Jody_Item
case TRAINER_KENT, Route119_EventScript_Kent_Item
case TRAINER_LEONARD, SSTidalLowerDeck_EventScript_Leonard_Item
case TRAINER_GILBERT, Route132_EventScript_Gilbert_Item
case TRAINER_KEVIN, Route131_EventScript_Kevin_Item
case TRAINER_CRISTIAN, DewfordTown_Gym_EventScript_Cristian_Item
case TRAINER_RICHARD, Route131_EventScript_Richard_Item
case TRAINER_HUEY, Route109_EventScript_Huey_Item
case TRAINER_JUSTIN, Route110_TrickHousePuzzle3_EventScript_Justin_Item
case TRAINER_JOEY, Route116_EventScript_Joey_Item
case TRAINER_GRUNT_AQUA_HIDEOUT_6, AquaHideout_B2F_EventScript_Grunt6_Item
case TRAINER_DYLAN_1, Route117_EventScript_Dylan_Item
case TRAINER_JOSHUA, Route110_TrickHousePuzzle7_EventScript_Joshua_Item
case TRAINER_VANESSA, Route121_EventScript_Vanessa_Item
case TRAINER_JENNY_1, Route124_EventScript_Jenny_Item
case TRAINER_MEL_AND_PAUL, Route109_EventScript_Mel_Item
case TRAINER_MARTHA, Route110_TrickHousePuzzle3_EventScript_Martha_Item
case TRAINER_SIDNEY, Sydney_Item
case TRAINER_HUDSON, Route134_EventScript_Hudson_Item
case TRAINER_LAO_1, Route113_EventScript_Lao_Item
case TRAINER_LAWRENCE, Route113_EventScript_Lawrence_Item
case TRAINER_LUNG, Route113_EventScript_Lung_Item
case TRAINER_DAYTON, Route119_EventScript_Dayton_Item
end