AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
finditem ITEM_HARBOR_MAIL

return

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
finditem ITEM_DIVE_BALL

return

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
finditem ITEM_ESCAPE_ROPE

return

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
finditem ITEM_REVIVE

return

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
finditem ITEM_STORAGE_KEY

return

AbandonedShip_Room_B1F_EventScript_ItemTM13::
finditem ITEM_TM13

return

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
finditem ITEM_WATER_STONE

return

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
finditem ITEM_TM18

return

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
finditem ITEM_LUXURY_BALL

return

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
finditem ITEM_SCANNER

return

AbandonedShip_Rooms_1F_Eventscript_Thalia_Item::

return

AbandonedShip_Rooms_1F_EventScript_Demetrius_Item::

return

AbandonedShip_Corridors_B1F_EventScript_Duncan_Item::

return

AbandonedShip_Corridors_1F_EventScript_Charlie_Item::

return

AbandonedShip_Rooms2_1F_EventScript_Garrison_Item::

return

AbandonedShip_Rooms2_1F_EventScript_Jani_Item::

return

AbandonedShip_Rooms2_1F_EventScript_Kira_Item::

return

AncientTomb_EventScript_Registeel_Item::

return

AquaHideout_B1F_EventScript_ItemMasterBall::
finditem ITEM_MASTER_BALL

return

AquaHideout_B1F_EventScript_ItemNugget::
finditem ITEM_NUGGET

return

AquaHideout_B1F_EventScript_ItemMaxElixir::
finditem ITEM_MAX_ELIXIR

return

AquaHideout_B2F_EventScript_ItemNestBall::
finditem ITEM_NEST_BALL

return

AquaHideout_B1F_EventScript_Electrode1_Item::

return

AquaHideout_B1F_EventScript_Electrode2_Item::

return

AquaHideout_1F_EventScript_Grunt1_Item::

return

AquaHideout_B1F_EventScript_Grunt2_Item::

return

AquaHideout_B1F_EventScript_Grunt3_Item::

return

AquaHideout_B2F_EventScript_Grunt4_Item::

return

AquaHideout_B1F_EventScript_Grunt5_Item::

return

AquaHideout_B2F_EventScript_Grunt6_Item::

return

AquaHideout_B1F_EventScript_Grunt7_Item::

return

AquaHideout_B2F_EventScript_Grunt8_Item::

return

AquaHideout_B2F_EventScript_Matt_Item::

return

BirthIsland_Exterior_EventScript_Deoxys_Item::

return

DesertRuins_EventScript_Regirock_Item::

return

DesertUnderpass_EventScript_GiveRootFossil_Item::
giveitem ITEM_ROOT_FOSSIL

return

DesertUnderpass_EventScript_GiveClawFossil_Item::
giveitem ITEM_CLAW_FOSSIL

return

DewfordTown_Gym_EventScript_Laura_Item::

return

DewfordTown_Gym_EventScript_Lilith_Item::

return

DewfordTown_Gym_EventScript_Brenden_Item::

return

DewfordTown_Gym_EventScript_Cristian_Item::

return

DewfordTown_Gym_EventScript_Jocelyn_Item::

return

DewfordTown_Gym_EventScript_Brawly_Item::

return

DewfordTown_EventScript_GiveOldRod_Item::
giveitem ITEM_OLD_ROD

return

DewfordTown_House2_EventScript_Man_Item::
giveitem ITEM_SILK_SCARF

return

DewfordTown_Hall_EventScript_SludgeBombMan_Item::
giveitem ITEM_TM36

return

Drake_Item::

return

Phoebe_Item::

return

Glacia_Item::

return

Sydney_Item::

return

FallarborTown_CozmosHouse_EventScript_PlayerHasMeteorite_Item::
giveitem ITEM_TM27

return

Mew_Item::

return

FieryPath_EventScript_ItemFireStone::
finditem ITEM_FIRE_STONE

return

FieryPath_EventScript_ItemTM06::
finditem ITEM_TM06

return

FortreeCity_House2_EventScript_HiddenPowerGiver_Item::
giveitem ITEM_TM10

return

FortreeCity_House4_EventScript_WingullReturned_Item::
giveitem ITEM_MENTAL_HERB

return

FortreeCity_Gym_EventScript_Jared_Item::

return

FortreeCity_Gym_EventScript_Humberto_Item::

return

FortreeCity_Gym_EventScript_Ashley_Item::

return

FortreeCity_Gym_EventScript_Flint_Item::

return

FortreeCity_Gym_EventScript_Edwardo_Item::

return

FortreeCity_Gym_EventScript_Darius_Item::

return

FortreeCity_Gym_EventScript_Winona_Item::

return

GraniteCave_B2F_EventScript_ItemRepel::
finditem ITEM_REPEL

return

GraniteCave_1F_EventScript_Hiker_Item::
giveitem ITEM_HM05

return

GraniteCave_1F_EventScript_ItemEscapeRope::
finditem ITEM_ESCAPE_ROPE

return

GraniteCave_B1F_EventScript_ItemPokeBall::
finditem ITEM_POKE_BALL

return

GraniteCave_StevensRoom_EventScript_Steven_Item::
giveitem ITEM_TM47

return

GraniteCave_B2F_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

IslandCave_EventScript_Regice_Item::

return

JaggedPass_EventScript_ItemBurnHeal::
finditem ITEM_BURN_HEAL

return

JaggedPass_EventScript_Eric_Item::

return

JaggedPass_EventScript_MagmaHideoutGuard_Item::

return

JaggedPass_EventScript_Diana_Item::

return

JaggedPass_EventScript_Autumn_Item::

return

JaggedPass_EventScript_Julio_Item::

return

JaggedPass_EventScript_Ethan_Item::

return

LavaridgeTown_HerbShop_EventScript_OldMan_Item::
giveitem ITEM_CHARCOAL

return

LavaridgeTown_EventScript_MayGiveGoGoggles_ITEM::
giveitem ITEM_GO_GOGGLES

return

LavaridgeTown_EventScript_EggWoman_Item::
giveegg SPECIES_WYNAUT

return

LavaridgeTown_Gym_B1F_EventScript_Jeff_Item::

return

LavaridgeTown_Gym_B1F_EventScript_Jace_Item::

return

LavaridgeTown_Gym_B1F_EventScript_Eli_Item::

return

LavaridgeTown_Gym_1F_EventScript_Cole_Item::

return

LavaridgeTown_Gym_1F_EventScript_Gerald_Item::

return

LavaridgeTown_Gym_1F_EventScript_Axle_Item::

return

LavaridgeTown_Gym_B1F_EventScript_Keegan_Item::

return

LavaridgeTown_Gym_1F_EventScript_Danielle_Item::

return

LavaridgeTown_Gym_1F_EventScript_Flannery_Item::

return

LilycoveCity_House2_EventScript_FatMan_Item::
giveitem ITEM_TM44

return

LilycoveCity_EventScript_ItemMaxRepel::
finditem ITEM_MAX_REPEL

return

LilycoveCity_EventScript_Rival_Item::

return

LittlerootTown_ProfessorBirchsLab_EventScript_MayGivePokeBalls_Items::
giveitem ITEM_POKE_BALL 5

return

MagmaHideout_1F_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

MagmaHideout_3F_1R_EventScript_ItemNugget::
finditem ITEM_NUGGET

return

MagmaHideout_4F_EventScript_ItemMaxRevive::
finditem ITEM_MAX_REVIVE

return

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
finditem ITEM_ESCAPE_ROPE

return

MagmaHideout_3F_2R_EventScript_ItemPPMax::
finditem ITEM_PP_MAX

return

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
finditem ITEM_FULL_RESTORE

return

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
finditem ITEM_MAX_ELIXIR

return

MagmaHideout_1F_EventScript_Grunt1_Item::

return

MagmaHideout_1F_EventScript_Grunt2_Item::

return

MagmaHideout_2F_1R_EventScript_Grunt3_Item::

return

MagmaHideout_2F_1R_EventScript_Grunt4_Item::

return

MagmaHideout_2F_1R_EventScript_Grunt5_Item::

return

MagmaHideout_2F_2R_EventScript_Grunt6_Item::

return

MagmaHideout_2F_2R_EventScript_Grunt7_Item::

return

MagmaHideout_2F_2R_EventScript_Grunt8_Item::

return

MagmaHideout_3F_1R_EventScript_Grunt9_Item::

return

MagmaHideout_3F_2R_EventScript_Grunt10_Item::

return

MagmaHideout_4F_EventScript_Grunt11_Item::

return

MagmaHideout_4F_EventScript_Grunt12_Item::

return

MagmaHideout_4F_EventScript_Grunt13_Item::

return

MagmaHideout_2F_1R_EventScript_Grunt14_Item::

return

MagmaHideout_2F_2R_EventScript_Grunt15_Item::

return

MagmaHideout_3F_1R_EventScript_Grunt16_Item::

return

MagmaHideout_4F_EventScript_Tabitha_Item::

return

MagmaHideout_4F_EventScript_Maxie_Item::

return

MarineCave_End_EventScript_Kyogre_Item::

return

MauvilleCity_House2_EventScript_AcceptTrade_Item::
giveitem ITEM_COIN_CASE

return

MauvilleCity_EventScript_ItemXSpeed::
finditem ITEM_X_SPEED

return

MauvilleCity_House1_EventScript_RockSmashDude_Item::
giveitem ITEM_HM06

return

MauvilleCity_EventScript_Wattson_Item::
giveitem ITEM_BASEMENT_KEY

return

MauvilleCity_EventScript_CompletedNewMauville_Item::
giveitem ITEM_TM24

return

MauvilleCity_EventScript_DefeatedWally_Item::

return

MauvilleCity_Gym_EventScript_Vivian_Item::

return

MauvilleCity_Gym_EventScript_Kirk_Item::

return

MauvilleCity_Gym_EventScript_Ben_Item::

return

MauvilleCity_Gym_EventScript_Angelo_Item::

return

MauvilleCity_Gym_EventScript_Shawn_Item::

return

MauvilleCity_Gym_EventScript_Wattson_Item::

return

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
finditem ITEM_FULL_HEAL

return

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
finditem ITEM_MOON_STONE

return

MeteorFalls_1F_1R_EventScript_ItemTM23::
finditem ITEM_TM23

return

MeteorFalls_B1F_2R_EventScript_ItemTM02::
finditem ITEM_TM02

return

MeteorFalls_1F_1R_EventScript_ItemPPUP::
finditem ITEM_PP_UP

return

MeteorFalls_1F_2R_EventScript_John_Item::

return

MeteorFalls_1F_2R_EventScript_Nicolas_Item::

return

MeteorFalls_StevensCave_EventScript_Steven_Item::

return

MossdeepCity_EventScript_ItemNetBall::
finditem ITEM_NET_BALL

return

MossdeepCity_EventScript_KingsRockBoy_Item::
giveitem ITEM_KINGS_ROCK

return

MossdeepCity_StevensHouse_EventScript_StevenGivesDive_Item::
giveitem ITEM_HM08

return

MossdeepCity_House3_EventScript_SuperRodFisherman_Item::
giveitem ITEM_SUPER_ROD

return

MossdeepCity_StevensHouse_EventScript_GiveBeldum_Item::
givemon SPECIES_BELDUM, 25, ITEM_NONE

return

MossdeepCity_Gym_EventScript_Preston_Item::

return

MossdeepCity_Gym_EventScript_Maura_Item::

return

MossdeepCity_Gym_EventScript_Samantha_Item::

return

MossdeepCity_Gym_EventScript_Blake_Item::

return

MossdeepCity_Gym_EventScript_Macey_Item::

return

MossdeepCity_Gym_EventScript_Clifford_Item::

return

MossdeepCity_Gym_EventScript_Kathleen_Item::

return

MossdeepCity_Gym_EventScript_Nicholas_Item::

return

MossdeepCity_Gym_EventScript_Nate_Item::

return

MossdeepCity_Gym_EventScript_Virgil_Item::

return

MossdeepCity_Gym_EventScript_Sylvia_Item::

return

MossdeepCity_Gym_EventScript_Hannah_Item::

return

MossdeepCity_Gym_EventScript_TateAndLiza_Item::

return

MtChimney_EventScript_MeteoriteMachine_Item::
giveitem ITEM_METEORITE

return

MtPyre_1F_EventScript_CleanseTagWoman_Item::
giveitem ITEM_CLEANSE_TAG

return

MtPyre_2F_EventScript_ItemUltraBall::
finditem ITEM_ULTRA_BALL

return

MtPyre_3F_EventScript_ItemSuperRepel::
finditem ITEM_SUPER_REPEL

return

MtPyre_4F_EventScript_ItemSeaIncense::
finditem ITEM_SEA_INCENSE

return

MtPyre_5F_EventScript_ItemLaxIncense::
finditem ITEM_LAX_INCENSE

return

MtPyre_6F_EventScript_ItemTM30::
finditem ITEM_TM30

return

MtPyre_Exterior_EventScript_ItemTM48::
finditem ITEM_TM48

return

MtPyre_Exterior_EventScript_ItemMaxPotion::
finditem ITEM_MAX_POTION

return

MtPyre_Summit_EventScript_TeamAquaExits_Item::
giveitem ITEM_MAGMA_EMBLEM

return

MtPyre_2F_EventScript_Mark_Item::

return

MtPyre_2F_EventScript_Leah_Item::

return

MtPyre_2F_EventScript_Zander_Item::

return

MtPyre_2F_EventScript_Dez_Item::

return

MtPyre_3F_EventScript_Kayla_Item::

return

MtPyre_3F_EventScript_Gabrielle_Item::

return

MtPyre_3F_EventScript_William_Item::

return

MtPyre_4F_EventScript_Tasha_Item::

return

MtPyre_5F_EventScript_Atsushi_Item::

return

MtPyre_6F_EventScript_Valerie_Item::

return

MtPyre_6F_EventScript_Cedric_Item::

return

MtPyre_Summit_EventScript_Grunt1_Item::

return

MtPyre_Summit_EventScript_Grunt2_Item::

return

MtPyre_Summit_EventScript_Grunt3_Item::

return

MtPyre_Summit_EventScript_Grunt4_Item::

return

NavelRock_Top_EventScript_HoOh_ITEM::

return

NewMauville_Inside_EventScript_ItemEscapeRope::
finditem ITEM_ESCAPE_ROPE

return

NewMauville_Inside_EventScript_ItemUltraBall::
finditem ITEM_ULTRA_BALL

return

NewMauville_Inside_EventScript_ItemParalyzeHeal::
finditem ITEM_PARALYZE_HEAL

return

NewMauville_Inside_EventScript_ItemFullHeal::
finditem ITEM_FULL_HEAL

return

NewMauville_Inside_EventScript_ItemThunderStone::
finditem ITEM_THUNDER_STONE

return

NewMauville_Inside_EventScript_Voltorb1_Item::

return

NewMauville_Inside_EventScript_Voltorb2_Item::

return

NewMauville_Inside_EventScript_Voltorb3_Item::

return

OldaleTown_EventScript_ExplainPokemonMart_Item::
giveitem ITEM_POTION

return

PacifidlogTown_House2_EventScript_GiveFrustration_Item::
giveitem ITEM_TM21

return

PacifidlogTown_House2_EventScript_GiveReturn_Item::
giveitem ITEM_TM27

return

PetalburgCity_WallysHouse_EventScript_GiveHM03Surf_Item::
giveitem ITEM_HM03

return

PetalburgCity_EventScript_ItemMaxRevive::
finditem ITEM_MAX_REVIVE

return

PetalburgCity_EventScript_ItemEther::
finditem ITEM_ETHER

return

PetalburgCity_Gym_EventScript_Randall_Item::

return

PetalburgCity_Gym_EventScript_Mary_Item::

return

PetalburgCity_Gym_EventScript_Parker_Item::

return

PetalburgCity_Gym_EventScript_Alexia_Item::

return

PetalburgCity_Gym_EventScript_George_Item::

return

PetalburgCity_Gym_EventScript_Jody_Item::

return

PetalburgCity_Gym_EventScript_Berke_Item::

return

PetalburgCity_Gym_EventScript_NormanBattle_Item::

return

PetalburgWoods_EventScript_ItemParalyzeHeal::
giveitem ITEM_PARALYZE_HEAL

return

PetalburgWoods_EventScript_DevonResearcherPostBattle_Item::
giveitem ITEM_GREAT_BALL

return

PetalburgWoods_EventScript_ItemEther::
finditem ITEM_ETHER

return

PetalburgWoods_EventScript_Girl_Item::
giveitem ITEM_MIRACLE_SEED

return

PetalburgWoods_EventScript_ItemGreatBall::
giveitem ITEM_GREAT_BALL

return

PetalburgWoods_EventScript_ItemXAttack::
giveitem ITEM_X_ATTACK

return

PetalburgWoods_EventScript_Lyle_Item::

return

PetalburgWoods_EventScript_James_Item::

return

PetalburgWoods_EventScript_DevonResearcherLeft_Item::

return

Route102_EventScript_ItemPotion::
finditem ITEM_POTION

return

Route102_EventScript_Calvin_Item::

return

Route102_EventScript_Rick_Item::

return

Route102_EventScript_Allen_Item::

return

Route102_EventScript_Tiana_Item::

return

Route103_EventScript_ItemGuardSpec::
finditem ITEM_GUARD_SPEC

return

Route103_EventScript_ItemPPUp::
finditem ITEM_PP_UP

return

Route103_EventScript_Item_Rival::

return

Route104_EventScript_ItemPokeBall::
finditem ITEM_POKE_BALL

return

Route104_EventScript_Boy2_Item::
giveitem ITEM_TM09

return

Route104_EventScript_ItemPotion::
finditem ITEM_POTION

return

Route104_EventScript_ItemXAccuracy::
finditem ITEM_X_ACCURACY

return

Route104_EventScript_ItemPPUp::
finditem ITEM_PP_UP

return

Route104_EventScript_WhiteHerbFlorist_Item::
giveitem ITEM_WHITE_HERB

return

Route104_PrettyPetalFlowerShop_EventScript_GiveWailmerPail_ITEM::
giveitem ITEM_WAILMER_PAIL

return

Route105_EventScript_ItemIron::
finditem ITEM_IRON

return

Route105_EventScript_Imani_Item::

return

Route105_EventScript_Dominik_Item::

return

Route105_EventScript_Foster_Item::

return

Route105_EventScript_Beverly_Item::

return

Route105_EventScript_Andres_Item::

return

Route105_EventScript_Josue_Item::

return

Route105_EventScript_Luis_Item::

return

Route106_EventScript_ItemProtein::
finditem ITEM_PROTEIN

return

Route106_EventScript_Ned_Item::

return

Route106_EventScript_Elliot_Item::

return

Route106_EventScript_Douglas_Item::

return

Route106_EventScript_Kyla_Item::

return

Route107_EventScript_Denise_Item::

return

Route107_EventScript_Tony_Item::

return

Route107_EventScript_Lisa_Item::

return

Route107_EventScript_Darrin_Item::

return

Route107_EventScript_Beth_Item::

return

Route107_EventScript_Camron_Item::

return

Route108_EventScript_ItemStarPiece::
finditem ITEM_STAR_PIECE

return

Route108_EventScript_Missy_Item::

return

Route108_EventScript_Matthew_Item::

return

Route108_EventScript_Tara_Item::

return

Route108_EventScript_Carolina_Item::

return

Route108_EventScript_Cory_Item::

return

Route108_EventScript_Jerome_Item::

return

Route109_EventScript_SoftSandGirl_ITEM::
giveitem ITEM_SOFT_SAND

return

Route109_SeashoreHouse_EventScript_DefeatedTrainers_Item::
giveitem ITEM_SODA_POP, 6

return

Route109_EventScript_ItemPotion::
finditem ITEM_POTION

return

Route109_EventScript_ItemPPUp::
finditem ITEM_PP_UP

return

Route109_EventScript_Huey_Item::

return

Route109_EventScript_Edmond_Item::

return

Route109_EventScript_Hailey_Item::

return

Route109_EventScript_Ricky_Item::

return

Route109_EventScript_Lola_Item::

return

Route109_EventScript_Chandler_Item::

return

Route109_SeashoreHouse_EventScript_Simon_Item::

return

Route109_SeashoreHouse_EventScript_Johanna_Item::

return

Route109_SeashoreHouse_EventScript_Dwayne_Item::

return

Route109_EventScript_Austina_Item::

return

Route109_EventScript_Gwen_Item::

return

Route109_EventScript_David_Item::

return

Route109_EventScript_Alice_Item::

return

Route109_EventScript_Carter_Item::

return

Route109_EventScript_Elijah_Item::

return

Route109_EventScript_Mel_Item::

return

Route110_EventScript_ItemDireHit::
finditem ITEM_DIRE_HIT

return

Route110_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

Route110_EventScript_GiveItemfinder_Item::
giveitem ITEM_DOWSING_MACHINE

return

Route110_EventScript_ItemElixir::
finditem ITEM_ELIXIR

return

Route110_EventScript_Isabel_Item::

return

Route110_EventScript_Kaleb_Item::

return

Route110_EventScript_Timmy_Item::

return

Route110_EventScript_Edwin_Item::

return

Route110_EventScript_Joseph_Item::

return

Route110_EventScript_Edward_Item::

return

Route110_EventScript_Alyssa_Item::

return

Route110_EventScript_Dale_Item::

return

Route110_EventScript_GiveItemfinder_Item2::

return

Route110_EventScript_Jaclyn_Item::

return

Route110_EventScript_Abigail_Item::

return

Route110_EventScript_Anthony_Item::

return

Route110_EventScript_Benjamin_Item::

return

Route110_EventScript_Jasmine_Item::

return

Route110_EventScript_Jacob_Item::

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle1_Item::
giveitem ITEM_RARE_CANDY

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle2_Item::
giveitem ITEM_TIMER_BALL

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle3_Item::
giveitem ITEM_HARD_STONE

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle4_Item::
giveitem ITEM_SMOKE_BALL

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle5_Item::
giveitem ITEM_TM12

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle6_Item::
giveitem ITEM_MAGNET

return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle7_Item::
giveitem ITEM_PP_MAX

return

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
finditem ITEM_ORANGE_MAIL

return

Route110_TrickHousePuzzle1_EventScript_Sally_Item::

return

Route110_TrickHousePuzzle1_EventScript_Robin_Item::

return

Route110_TrickHousePuzzle1_EventScript_Eddie_Item::

return

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
finditem ITEM_WAVE_MAIL

return

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
finditem ITEM_HARBOR_MAIL

return

Route110_TrickHousePuzzle2_EventScript_Ted_Item::

return

Route110_TrickHousePuzzle2_EventScript_Paul_Item::

return

Route110_TrickHousePuzzle2_EventScript_Georgia_Item::

return

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
finditem ITEM_WOOD_MAIL

return

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
finditem ITEM_SHADOW_MAIL

return

Route110_TrickHousePuzzle3_EventScript_Justin_Item::

return

Route110_TrickHousePuzzle3_EventScript_Martha_Item::

return

Route110_TrickHousePuzzle3_EventScript_Alan_Item::

return

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
finditem ITEM_MECH_MAIL

return

Route110_TrickHousePuzzle4_EventScript_Yuji_Item::

return

Route110_TrickHousePuzzle4_EventScript_Cora_Item::

return

Route110_TrickHousePuzzle4_EventScript_Paula_Item::

return

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
finditem ITEM_GLITTER_MAIL

return

Route110_TrickHousePuzzle6_EventScript_Sophia_Item::

return

Route110_TrickHousePuzzle6_EventScript_Sebastian_Item::

return

Route110_TrickHousePuzzle6_EventScript_Benny_Item::

return

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
finditem ITEM_TROPIC_MAIL

return

Route110_TrickHousePuzzle7_EventScript_Joshua_Item::

return

Route110_TrickHousePuzzle7_EventScript_Patricia_Item::

return

Route110_TrickHousePuzzle7_EventScript_Mariela_Item::

return

Route110_TrickHousePuzzle7_EventScript_Everett_Item::

return

Route110_TrickHousePuzzle7_EventScript_Alexis_Item::

return

Route110_TrickHousePuzzle7_EventScript_Alvaro_Item::

return

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
finditem ITEM_BEAD_MAIL

return

Route110_TrickHousePuzzle8_EventScript_Keira_Item::

return

Route110_TrickHousePuzzle8_EventScript_Vincent_Item::

return

Route110_TrickHousePuzzle8_EventScript_Leroy_Item::

return

Route111_WinstrateFamilysHouse_EventScript_Victoria_Item_Brace::
giveitem ITEM_MACHO_BRACE

return

Route111_EventScript_ItemHPUp::
finditem ITEM_HP_UP

return

Route111_EventScript_ItemElixir::
finditem ITEM_ELIXIR

return

Route111_EventScript_ItemStardust::
finditem ITEM_STARDUST

return

Route111_EventScript_Girl_Item::
giveitem ITEM_RAZZ_BERRY

return

Route111_EventScript_ItemTM37::
finditem ITEM_TM37

return

Route111_EventScript_GiveSecretPower_Item::
giveitem ITEM_TM43

return

Route111_EventScript_Tyron_Item::

return

Route111_EventScript_Celina_Item::

return

Route111_EventScript_Bianca_Item::

return

Route111_EventScript_Hayden_Item::

return

::

return

Route111_EventScript_Irene_Item::

return

Route111_EventScript_Travis_Item::

return

Route111_EventScript_Heidi_Item::

return

Route111_EventScript_Beau_Item::

return

Route111_EventScript_Drew_Item::

return

Route111_EventScript_Becky_Item::

return

Route111_EventScript_Dusty_Item::

return

Route111_EventScript_Celia_Item::

return

Route111_EventScript_Bryan_Item::

return

Route111_EventScript_Branden_Item::

return

Route111_EventScript_Wilton_Item::

return

Route111_EventScript_Brooke_Item::

return

Route111_EventScript_Daisuke_Item::

return

Route111_EventScript_Victor_Item::

return

Route111_WinstrateFamilysHouse_EventScript_Victoria_Item::

return

Route111_WinstrateFamilysHouse_EventScript_Vivi_Item::

return

Route111_WinstrateFamilysHouse_EventScript_Vicky_Item::

return

Route112_EventScript_ItemNugget::
finditem ITEM_NUGGET

return

Route112_EventScript_Larry_Item::

return

Route112_EventScript_Carol_Item::

return

Route112_EventScript_Trent_Item::

return

Route112_EventScript_Brice_Item::

return

Route112_EventScript_Bryant_Item::

return

Route112_EventScript_Shayla_Item::

return

Route113_EventScript_ItemMaxEther::
finditem ITEM_MAX_ETHER

return

Route113_GlassWorkshop_EventScript_GlassWorker_Item::
giveitem ITEM_SOOT_SACK

return

Route113_EventScript_ItemHyperPotion::
finditem ITEM_HYPER_POTION

return

Route113_EventScript_ItemSuperRepel::
finditem ITEM_SUPER_REPEL

return

Route113_EventScript_Jaylen_Item::

return

Route113_EventScript_Lawrence_Item::

return

Route113_EventScript_Lung_Item::

return

Route113_EventScript_Wyatt_Item::

return

Route113_EventScript_Madeline_Item::

return

Route113_EventScript_Tori_Item::

return

Route113_EventScript_Lao_Item::

return

Route113_EventScript_Dillon_Item::

return

Route113_EventScript_Sophie_Item::

return

Route113_EventScript_Coby_Item::

return

Route114_FossilManiacsHouse_EventScript_FossilManiacsBrother_Item::
giveitem ITEM_TM28

return

Route114_EventScript_RoarGentleman_Item::
giveitem ITEM_TM05

return

Route114_EventScript_ItemEnergyPowder::
finditem ITEM_ENERGY_POWDER

return

Route114_EventScript_ItemProtein::
finditem ITEM_PROTEIN

return

Route114_LanettesHouse_EventScript_Lanette_Item::
giveitem DECOR_LOTAD_DOLL

return

Route114_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

Route114_EventScript_Nolan_Item::

return

Route114_EventScript_Charlotte_Item::

return

Route114_EventScript_Kai_Item::

return

Route114_EventScript_Claude_Item::

return

Route114_EventScript_Nancy_Item::

return

Route114_EventScript_Tyra_Item::

return

Route114_EventScript_Shane_Item::

return

Route114_EventScript_Steve_Item::

return

Route114_EventScript_Bernie_Item::

return

Route114_EventScript_Lucas_Item::

return

Route114_EventScript_Angelina_Item::

return

Route114_EventScript_Lenny_Item::

return

Route115_EventScript_ItemSuperPotion::
finditem ITEM_SUPER_POTION

return

Route115_EventScript_ItemGreatBall::
finditem ITEM_GREAT_BALL

return

Route115_EventScript_ItemPPUp::
finditem ITEM_PP_UP

return

Route115_EventScript_ItemTM01::
finditem ITEM_TM01

return

Route115_EventScript_ItemHealPowder::
finditem ITEM_HEAL_POWDER

return

Route115_EventScript_ItemIron::
finditem ITEM_IRON

return

Route115_EventScript_Nob_Item::

return

Route115_EventScript_Hector_Item::

return

Route115_EventScript_Marlene_Item::

return

Route115_EventScript_Cyndy_Item::

return

Route115_EventScript_Jaiden_Item::

return

Route115_EventScript_Timothy_Item::

return

Route115_EventScript_Kyra_Item::

return

Route115_EventScript_Koichi_Item::

return

Route115_EventScript_Helene_Item::

return

Route115_EventScript_Alix_Item::

return

Route116_EventScript_ItemRepel::
finditem ITEM_REPEL

return

Route116_EventScript_ItemXSpecial::
finditem ITEM_X_SP_ATK

return

Route116_EventScript_ItemEther::
finditem ITEM_ETHER

return

Route116_EventScript_ItemPotion::
finditem ITEM_POTION

return

Route116_EventScript_GiveRepeatBall_Item::
finditem ITEM_REPEAT_BALL

return

Route116_EventScript_ItemHPUp::
finditem ITEM_HP_UP

return

Route116_EventScript_Jose_Item::

return

Route116_EventScript_Joey_Item::

return

Route116_EventScript_Karen_Item::

return

Route116_EventScript_Clark_Item::

return

Route116_EventScript_Johnson_Item::

return

Route116_EventScript_Devan_Item::

return

Route116_EventScript_Sarah_Item::

return

Route116_EventScript_Dawson_Item::

return

Route116_EventScript_Jerry_Item::

return

Route116_EventScript_Janice_Item::

return

Route117_EventScript_ItemRevive::
finditem ITEM_REVIVE

return

Route117_EventScript_ItemGreatBall::
finditem ITEM_GREAT_BALL

return

Route117_EventScript_Dylan_Item::

return

Route117_EventScript_Anna_Item::

return

Route117_EventScript_Isaac_Item::

return

Route117_EventScript_Maria_Item::

return

Route117_EventScript_Derek_Item::

return

Route117_EventScript_Brandi_Item::

return

Route117_EventScript_Melina_Item::

return

Route117_EventScript_Aisha_Item::

return

Route117_EventScript_Lydia_Item::

return

Route118_EventScript_ReceiveGoodRod_Item::
giveitem ITEM_GOOD_ROD

return

Route118_EventScript_ItemHyperPotion::
finditem ITEM_HYPER_POTION

return

Route118_EventScript_Rose_Item::

return

Route118_EventScript_Deandre_Item::

return

Route118_EventScript_Wade_Item::

return

Route118_EventScript_Dalton_Item::

return

::

return

Route118_EventScript_Barny_Item::

return

Route118_EventScript_Chester_Item::

return

Route118_EventScript_Perry_Item::

return

Route119_EventScript_ItemElixir::
finditem ITEM_ELIXIR

return

Route119_EventScript_ItemElixir2::
finditem ITEM_ELIXIR

return

Route119_EventScript_ItemLeafStone::
finditem ITEM_LEAF_STONE

return

Route119_EventScript_GiveFlyHM_Item::
giveitem ITEM_HM02

return

Route119_EventScript_ItemSuperRepel::
finditem ITEM_SUPER_REPEL

return

Route119_EventScript_ItemHyperPotion::
finditem ITEM_HYPER_POTION

return

Route119_EventScript_ItemHyperPotion2::
finditem ITEM_HYPER_POTION

return

Route119_EventScript_ItemZinc::
finditem ITEM_ZINC

return

Route119_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

Route119_EventScript_ItemNugget::
finditem ITEM_NUGGET

return

Route119_EventScript_Kent_Item::

return

Route119_EventScript_Donald_Item::

return

Route119_EventScript_Greg_Item::

return

Route119_EventScript_Taylor_Item::

return

Route119_EventScript_Doug_Item::

return

Route119_EventScript_Brent_Item::

return

Route119_EventScript_Chris_Item::

return

Route119_EventScript_Catherine_Item::

return

Route119_EventScript_Jackson_Item::

return

Route119_EventScript_Rachel_Item::

return

Route119_EventScript_Phil_Item::

return

Route119_EventScript_Takashi_Item::

return

Route119_EventScript_Dayton_Item::

return

Route119_EventScript_Hugh_Item::

return

Route119_EventScript_Fabian_Item::

return

Route119_EventScript_Yasu_Item::

return

Route119_EventScript_Hideo_Item::

return

Route119_EventScript_RivalExitScottArrive_Item::

return

Route119_WeatherInstitute_2F_EventScript_ReceiveCastform_Item::
givemon SPECIES_CASTFORM, 25, ITEM_NONE

return

Route119_WeatherInstitute_1F_EventScript_Grunt1_Item::

return

Route119_WeatherInstitute_2F_EventScript_Grunt2_Item::

return

Route119_WeatherInstitute_2F_EventScript_Grunt3_Item::

return

Route119_WeatherInstitute_1F_EventScript_Grunt4_Item::

return

Route119_WeatherInstitute_2F_EventScript_Grunt5_Item::

return

Route119_WeatherInstitute_2F_EventScript_Shelly_Item::

return

Route120_EventScript_StevenGiveDeconScope_ITEM::
giveitem ITEM_DEVON_SCOPE

return

Route120_EventScript_ItemNestBall::
finditem ITEM_NEST_BALL

return

Route120_EventScript_ItemRevive::
finditem ITEM_REVIVE

return

Route120_EventScript_ItemNugget::
finditem ITEM_NUGGET

return

Route120_EventScript_ItemFullHeal::
finditem ITEM_FULL_HEAL

return

Route120_EventScript_ItemHyperPotion::
finditem ITEM_HYPER_POTION

return

Route120_EventScript_Clarissa_Item::

return

::

return

Route120_EventScript_Robert_Item::

return

Route120_EventScript_Colin_Item::

return

Route120_EventScript_Leonel_Item::

return

Route120_EventScript_Angelica_Item::

return

Route120_EventScript_Riley_Item::

return

Route120_EventScript_Callie_Item::

return

Route120_EventScript_Jennifer_Item::

return

Route120_EventScript_Jenna_Item::

return

Route120_EventScript_Lorenzo_Item::

return

Route120_EventScript_Jeffrey_Item::

return

Route120_EventScript_Keigo_Item::

return

Route120_EventScript_Chip_Item::

return

Route121_EventScript_ItemZinc::
finditem ITEM_ZINC

return

Route121_EventScript_ItemRevive::
finditem ITEM_REVIVE

return

Route121_EventScript_ItemCarbos::
finditem ITEM_CARBOS

return

Route121_EventScript_Cale_Item::

return

Route121_EventScript_Tammy_Item::

return

Route121_EventScript_Jessica_Item::

return

Route121_EventScript_Kate_Item::

return

Route121_EventScript_Pat_Item::

return

Route121_EventScript_Myles_Item::

return

Route121_EventScript_Walter_Item::

return

Route121_EventScript_Vanessa_Item::

return

Route121_EventScript_Marcel_Item::

return

Route121_EventScript_Cristin_Item::

return

SafariZone_Southwest_EventScript_ItemMaxRevive::
finditem ITEM_MAX_REVIVE

return

SafariZone_Northwest_EventScript_ItemTM22::
finditem ITEM_TM22

return

SafariZone_North_EventScript_ItemCalcium::
finditem ITEM_CALCIUM

return

SafariZone_Southeast_EventScript_ItemBigPearl::
finditem ITEM_BIG_PEARL

return

SafariZone_Northeast_EventScript_ItemNugget::
finditem ITEM_NUGGET

return

Route123_EventScript_GigaDrainGirl_Item::
giveitem ITEM_TM19

return

Route123_EventScript_ItemElixir::
finditem ITEM_ELIXIR

return

Route123_EventScript_ItemRevivalHerb::
finditem ITEM_REVIVAL_HERB

return

Route123_EventScript_ItemPPUp::
finditem ITEM_PP_UP

return

Route123_EventScript_ItemCalcium::
finditem ITEM_CALCIUM

return

Route123_EventScript_ItemUltraBall::
finditem ITEM_ULTRA_BALL

return

Route123_EventScript_Davis_Item::

return

Route123_EventScript_Jazmyn_Item::

return

Route123_EventScript_Violet_Item::

return

Route123_EventScript_Miu_Item::

return

Route123_EventScript_Kindra_Item::

return

Route123_EventScript_Ed_Item::

return

Route123_EventScript_Wendy_Item::

return

Route123_EventScript_Braxton_Item::

return

Route123_EventScript_Fernando_Item::

return

Route123_EventScript_Alberto_Item::

return

Route123_EventScript_Jacki_Item::

return

Route123_EventScript_Frederick_Item::

return

Route124_EventScript_ItemBlueShard::
finditem ITEM_BLUE_SHARD

return

Route124_EventScript_ItemYellowShard::
finditem ITEM_YELLOW_SHARD

return

Route124_EventScript_ItemRedShard::
finditem ITEM_RED_SHARD

return

Route124_EventScript_Grace_Item::

return

Route124_EventScript_Declan_Item::

return

Route124_EventScript_Lila_Item::

return

Route124_EventScript_Spencer_Item::

return

Route124_EventScript_Jenny_Item::

return

Route124_EventScript_Chad_Item::

return

Route124_EventScript_Isabella_Item::

return

Route124_EventScript_Roland_Item::

return

Route125_EventScript_ItemBigPearl::
finditem ITEM_BIG_PEARL

return

Route125_EventScript_Ernest_Item::

return

Route125_EventScript_Nolen_Item::

return

Route125_EventScript_Sharon_Item::

return

Route125_EventScript_Tanya_Item::

return

Route125_EventScript_Presley_Item::

return

Route125_EventScript_Auron_Item::

return

Route125_EventScript_Stan_Item::

return

Route125_EventScript_Kim_Item::

return

Route126_EventScript_ItemGreenShard::
finditem ITEM_GREEN_SHARD

return

Route126_EventScript_Leonardo_Item::

return

Route126_EventScript_Isobel_Item::

return

Route126_EventScript_Dean_Item::

return

Route126_EventScript_Nikki_Item::

return

Route126_EventScript_Barry_Item::

return

Route126_EventScript_Sienna_Item::

return

Route126_EventScript_Pablo_Item::

return

Route126_EventScript_Brenda_Item::

return

Route127_EventScript_ItemZinc::
finditem ITEM_ZINC

return

Route127_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

Route127_EventScript_ItemCarbos::
finditem ITEM_CARBOS

return

Route128_EventScript_Ruben_Item::

return

Route128_EventScript_Alexa_Item::

return

Route128_EventScript_Wayne_Item::

return

Route128_EventScript_Isaiah_Item::

return

Route128_EventScript_Katelyn_Item::

return

Route128_EventScript_Carlee_Item::

return

Route128_EventScript_Harrison_Item::

return

Route129_EventScript_Reed_Item::

return

Route129_EventScript_Chase_Item::

return

Route129_EventScript_Allison_Item::

return

Route129_EventScript_Clarence_Item::

return

Route129_EventScript_Tisha_Item::

return

Route130_EventScript_Rodney_Item::

return

Route130_EventScript_Katie_Item::

return

Route130_EventScript_Santiago_Item::

return

Route131_EventScript_Kevin_Item::

return

Route131_EventScript_Talia_Item::

return

Route131_EventScript_Richard_Item::

return

Route131_EventScript_Kara_Item::

return

Route131_EventScript_Herman_Item::

return

Route131_EventScript_Susie_Item::

return

Route131_EventScript_Reli_Item::

return

Route132_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

Route132_EventScript_ItemProtein::
finditem ITEM_PROTEIN

return

Route132_EventScript_Gilbert_Item::

return

Route132_EventScript_Dana_Item::

return

Route132_EventScript_Ronald_Item::

return

Route132_EventScript_Kiyo_Item::

return

Route132_EventScript_Paxton_Item::

return

Route132_EventScript_Darcy_Item::

return

Route132_EventScript_Makayla_Item::

return

Route132_EventScript_Jonathan_Item::

return

Route133_EventScript_ItemBigPearl::
finditem ITEM_BIG_PEARL

return

Route133_EventScript_ItemMaxRevive::
finditem ITEM_MAX_REVIVE

return

Route133_EventScript_ItemStarPiece::
finditem ITEM_STAR_PIECE

return

Route133_EventScript_Franklin_Item::

return

Route133_EventScript_Warren_Item::

return

Route133_EventScript_Beck_Item::

return

Route133_EventScript_Debra_Item::

return

Route133_EventScript_Linda_Item::

return

Route133_EventScript_Conor_Item::

return

Route133_EventScript_Mollie_Item::

return

Route134_EventScript_ItemCarbos::
finditem ITEM_CARBOS

return

Route134_EventScript_ItemStarPiece::
finditem ITEM_STAR_PIECE

return

Route134_EventScript_Laurel_Item::

return

Route134_EventScript_Jack_Item::

return

Route134_EventScript_Hitoshi_Item::

return

Route134_EventScript_Reyna_Item::

return

Route134_EventScript_Hudson_Item::

return

Route134_EventScript_Aaron_Item::

return

Route134_EventScript_Marley_Item::

return

Route134_EventScript_Alex_Item::

return

Route134_EventScript_Kelvin_Item::

return

RustboroCity_EventScript_ItemXDefend::
finditem ITEM_X_DEFENSE

return

RustboroCity_Flat2_2F_EventScript_NinjaBoy_Item::
giveitem ITEM_PREMIER_BALL

return

RustboroCity_CuttersHouse_EventScript_Cutter_Item::
giveitem ITEM_HM01

return

RustboroCity_EventScript_ReturnGoods_Item::
giveitem ITEM_GREAT_BALL

return

RustboroCity_DevonCorp_3F_EventScript_GiveExpShare_Item::
giveitem ITEM_EXP_SHARE

return

RustboroCity_Gym_EventScript_Josh_Item::

return

RustboroCity_Gym_EventScript_Tommy_Item::

return

RustboroCity_Gym_EventScript_Marc_Item::

return

RustboroCity_Gym_EventScript_Roxanne_Item::

return

RusturfTunnel_EventScript_ItemPokeBall::
finditem ITEM_POKE_BALL

return

RusturfTunnel_EventScript_Grunt_Item::
giveitem ITEM_DEVON_PARTS

return

RusturfTunnel_EventScript_ClearTunnelScene_ITEM::
giveitem ITEM_HM04

return

RusturfTunnel_EventScript_ItemMaxEther::
finditem ITEM_MAX_ETHER

return

RusturfTunnel_EventScript_Grunt_Item_Two::

return

RusturfTunnel_EventScript_Mike_Item::

return

ScorchedSlab_EventScript_ItemTM11::
finditem ITEM_TM11

return

SeafloorCavern_Room9_EventScript_ItemTM26::
finditem ITEM_TM26

return

SeafloorCavern_Room1_EventScript_Grunt1_Item::

return

SeafloorCavern_Room1_EventScript_Grunt2_Item::

return

SeafloorCavern_Room4_EventScript_Grunt3_Item::

return

SeafloorCavern_Room4_EventScript_Grunt4_Item::

return

SeafloorCavern_Room3_EventScript_Grunt5_Item::

return

SeafloorCavern_Room3_EventScript_Shelly_Item::

return

SeafloorCavern_Room9_EventScript_ArchieAwakenKyogre_Item::

return

SlateportCity_PokemonFanClub_EventScript_GiveSootheBell_Item::
giveitem ITEM_SOOTHE_BELL

return

SlateportCity_PokemonFanClub_EventScript_GiveRedScarf_Item::
giveitem ITEM_RED_SCARF

return

SlateportCity_PokemonFanClub_EventScript_GiveBlueScarf_Item::
giveitem ITEM_BLUE_SCARF

return

SlateportCity_PokemonFanClub_EventScript_GivePinkScarf_Item::
giveitem ITEM_PINK_SCARF

return

SlateportCity_PokemonFanClub_EventScript_GiveGreenScarf_Item::
giveitem ITEM_GREEN_SCARF

return

SlateportCity_PokemonFanClub_EventScript_GiveYellowScarf_Item::
giveitem ITEM_YELLOW_SCARF

return

SlateportCity_EventScript_BerryPowderClerk_Item::
giveitem ITEM_POWDER_JAR

return

SlateportCity_Harbor_EventScript_DeepSeaTooth_Item::
giveitem ITEM_DEEP_SEA_TOOTH

return

SootopolisCity_House1_EventScript_BrickBreakBlackBelt_Item::
giveitem ITEM_TM31

return

SootopolisCity_EventScript_GiveWaterfall_Item::
giveitem ITEM_HM07

return

SootopolisCity_LotadAndSeedotHouse_EventScript_BigSeedot_Item::
giveitem ITEM_ELIXIR

return

SootopolisCity_Gym_1F_EventScript_Juan_Item::

return

SootopolisCity_Gym_B1F_EventScript_Connie_Item::

return

SootopolisCity_Gym_B1F_EventScript_Andrea_Item::

return

SootopolisCity_Gym_B1F_EventScript_Daphne_Item::

return

SootopolisCity_Gym_B1F_EventScript_Annika_Item::

return

SootopolisCity_Gym_B1F_EventScript_Tiffany_Item::

return

SootopolisCity_Gym_B1F_EventScript_Crissy_Item::

return

SootopolisCity_Gym_B1F_EventScript_Bethany_Item::

return

SootopolisCity_Gym_B1F_EventScript_Olivia_Item::

return

SootopolisCity_Gym_B1F_EventScript_Brianna_Item::

return

SootopolisCity_Gym_B1F_EventScript_Bridget_Item::

return

SSTidalRooms_EventScript_SnatchGiver_Item::
finditem ITEM_TM49

return

SSTidalRooms_EventScript_Jed_Item::

return

SSTidalRooms_EventScript_Garret_Item::

return

SSTidalRooms_EventScript_Micah_Item::

return

SSTidalRooms_EventScript_Colton_Item::

return

SSTidalRooms_EventScript_Naomi_Item::

return

SSTidalRooms_EventScript_Thomas_Item::

return

SSTidalLowerDeck_EventScript_Phillip_Item::

return

SSTidalLowerDeck_EventScript_Leonard_Item::

return

VerdanturfTown_BattleTentLobby_EventScript_AttractGiver_Item::
giveitem ITEM_TM45

return

VictoryRoad_1F_EventScript_ItemMaxElixir::
finditem ITEM_MAX_ELIXIR

return

VictoryRoad_1F_EventScript_ItemPPUp::
finditem ITEM_PP_UP

return

VictoryRoad_B1F_EventScript_ItemFullRestore::
finditem ITEM_FULL_RESTORE

return

VictoryRoad_B1F_EventScript_ItemTM29::
finditem ITEM_TM29

return

VictoryRoad_B2F_EventScript_ItemFullHeal::
finditem ITEM_FULL_HEAL

return

VictoryRoad_1F_EventScript_Albert_Item::

return

VictoryRoad_1F_EventScript_Hope_Item::

return

VictoryRoad_B1F_EventScript_Shannon_Item::

return

VictoryRoad_B1F_EventScript_Samuel_Item::

return

VictoryRoad_B2F_EventScript_Julie_Item::

return

VictoryRoad_B2F_EventScript_Owen_Item::

return

VictoryRoad_B2F_EventScript_Dianne_Item::

return

VictoryRoad_B2F_EventScript_Felix_Item::

return

VictoryRoad_B2F_EventScript_Caroline_Item::

return

VictoryRoad_B2F_EventScript_Vito_Item::

return

VictoryRoad_B1F_EventScript_Michelle_Item::

return

VictoryRoad_B1F_EventScript_Mitchell_Item::

return

VictoryRoad_B1F_EventScript_Halle_Item::

return

VictoryRoad_1F_EventScript_Edgar_Item::

return

VictoryRoad_1F_EventScript_Katelynn_Item::

return

VictoryRoad_1F_EventScript_Quincy_Item::

return

VictoryRoad_1F_EventScript_WallyEntranceBattle_Item::

return

MEScrCmd_givepokemon::
givemon SPECIES_REGIGIGAS, 25, ITEM_NONE

return

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
finditem ITEM_BIG_PEARL

return

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

return

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
finditem ITEM_ICE_HEAL

return

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
finditem ITEM_TM07

return

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
finditem ITEM_NEVER_MELT_ICE

return

ArtisanCave_B1F_EventScript_ItemHPUp::
finditem ITEM_HP_UP

return

ArtisanCave_1F_EventScript_ItemCarbos::
finditem ITEM_CARBOS

return

