AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
finditem ITEM_HARBOR_MAIL

call FALSE
release
return

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
finditem ITEM_DIVE_BALL

call FALSE
release
return

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
finditem ITEM_ESCAPE_ROPE

call FALSE
release
return

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
finditem ITEM_REVIVE

call FALSE
release
return

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
finditem ITEM_STORAGE_KEY

call FALSE
release
return

AbandonedShip_Room_B1F_EventScript_ItemTM13::
finditem ITEM_TM13

call FALSE
release
return

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
finditem ITEM_WATER_STONE

call FALSE
release
return

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
finditem ITEM_TM18

call FALSE
release
return

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
finditem ITEM_LUXURY_BALL

call FALSE
release
return

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
finditem ITEM_SCANNER

call FALSE
release
return

AbandonedShip_Rooms_1F_Eventscript_Thalia_Item::

call FALSE
release
return

AbandonedShip_Rooms_1F_EventScript_Demetrius_Item::

call FALSE
release
return

AbandonedShip_Corridors_B1F_EventScript_Duncan_Item::

call FALSE
release
return

AbandonedShip_Corridors_1F_EventScript_Charlie_Item::

call FALSE
release
return

AbandonedShip_Rooms2_1F_EventScript_Garrison_Item::

call FALSE
release
return

AbandonedShip_Rooms2_1F_EventScript_Jani_Item::

call FALSE
release
return

AbandonedShip_Rooms2_1F_EventScript_Kira_Item::

call FALSE
release
return

AncientTomb_EventScript_Registeel_Item::

call FALSE
release
return

AquaHideout_B1F_EventScript_ItemMasterBall::
finditem ITEM_MASTER_BALL

call FALSE
release
return

AquaHideout_B1F_EventScript_ItemNugget::
finditem ITEM_NUGGET

call FALSE
release
return

AquaHideout_B1F_EventScript_ItemMaxElixir::
finditem ITEM_MAX_ELIXIR

call FALSE
release
return

AquaHideout_B2F_EventScript_ItemNestBall::
finditem ITEM_NEST_BALL

call FALSE
release
return

AquaHideout_B1F_EventScript_Electrode1_Item::

call FALSE
release
return

AquaHideout_B1F_EventScript_Electrode2_Item::

call FALSE
release
return

AquaHideout_1F_EventScript_Grunt1_Item::

call FALSE
release
return

AquaHideout_B1F_EventScript_Grunt2_Item::

call FALSE
release
return

AquaHideout_B1F_EventScript_Grunt3_Item::

call FALSE
release
return

AquaHideout_B2F_EventScript_Grunt4_Item::

call FALSE
release
return

AquaHideout_B1F_EventScript_Grunt5_Item::

call FALSE
release
return

AquaHideout_B2F_EventScript_Grunt6_Item::

call FALSE
release
return

AquaHideout_B1F_EventScript_Grunt7_Item::

call FALSE
release
return

AquaHideout_B2F_EventScript_Grunt8_Item::

call FALSE
release
return

AquaHideout_B2F_EventScript_Matt_Item::

call FALSE
release
return

BirthIsland_Exterior_EventScript_Deoxys_Item::

call FALSE
release
return

DesertRuins_EventScript_Regirock_Item::

call FALSE
release
return

DesertUnderpass_EventScript_GiveRootFossil_Item::
giveitem ITEM_ROOT_FOSSIL

call FALSE
release
return

DesertUnderpass_EventScript_GiveClawFossil_Item::
giveitem ITEM_CLAW_FOSSIL

call FALSE
release
return

DewfordTown_Gym_EventScript_Laura_Item::

call FALSE
release
return

DewfordTown_Gym_EventScript_Lilith_Item::

call FALSE
release
return

DewfordTown_Gym_EventScript_Brenden_Item::

call FALSE
release
return

DewfordTown_Gym_EventScript_Cristian_Item::

call FALSE
release
return

DewfordTown_Gym_EventScript_Jocelyn_Item::

call FALSE
release
return

DewfordTown_Gym_EventScript_Brawly_Item::

call FALSE
release
return

Dewford_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_BADGE02_GET
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT

call FALSE
release
return

DewfordTown_EventScript_GiveOldRod_Item::
giveitem ITEM_OLD_ROD

call FALSE
release
return

DewfordTown_House2_EventScript_Man_Item::
giveitem ITEM_SILK_SCARF

call FALSE
release
return

DewfordTown_Hall_EventScript_SludgeBombMan_Item::
giveitem ITEM_TM36

call FALSE
release
return

Drake_Item::

call FALSE
release
return

Phoebe_Item::

call FALSE
release
return

Glacia_Item::

call FALSE
release
return

Sydney_Item::

call FALSE
release
return

FallarborTown_CozmosHouse_EventScript_PlayerHasMeteorite_Item::
giveitem ITEM_TM27

call FALSE
release
return

Mew_Item::

call FALSE
release
return

FieryPath_EventScript_ItemFireStone::
finditem ITEM_FIRE_STONE

call FALSE
release
return

FieryPath_EventScript_ItemTM06::
finditem ITEM_TM06

call FALSE
release
return

FortreeCity_House2_EventScript_HiddenPowerGiver_Item::
giveitem ITEM_TM10

call FALSE
release
return

FortreeCity_House4_EventScript_WingullReturned_Item::
giveitem ITEM_MENTAL_HERB

call FALSE
release
return

FortreeCity_Gym_EventScript_Jared_Item::

call FALSE
release
return

FortreeCity_Gym_EventScript_Humberto_Item::

call FALSE
release
return

FortreeCity_Gym_EventScript_Ashley_Item::

call FALSE
release
return

FortreeCity_Gym_EventScript_Flint_Item::

call FALSE
release
return

FortreeCity_Gym_EventScript_Edwardo_Item::

call FALSE
release
return

FortreeCity_Gym_EventScript_Darius_Item::

call FALSE
release
return

FortreeCity_Gym_EventScript_Winona_Item::

call FALSE
release
return

Fortree_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_BADGE06_GET
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT

call FALSE
release
return

GraniteCave_B2F_EventScript_ItemRepel::
finditem ITEM_REPEL

call FALSE
release
return

GraniteCave_1F_EventScript_Hiker_Item::
giveitem ITEM_HM05

call FALSE
release
return

GraniteCave_1F_EventScript_ItemEscapeRope::
finditem ITEM_ESCAPE_ROPE

call FALSE
release
return

GraniteCave_B1F_EventScript_ItemPokeBall::
finditem ITEM_POKE_BALL

call FALSE
release
return

GraniteCave_StevensRoom_EventScript_Steven_Item::
giveitem ITEM_TM47

call FALSE
release
return

GraniteCave_B2F_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

call FALSE
release
return

IslandCave_EventScript_Regice_Item::

call FALSE
release
return

JaggedPass_EventScript_ItemBurnHeal::
finditem ITEM_BURN_HEAL

call FALSE
release
return

JaggedPass_EventScript_Eric_Item::

call FALSE
release
return

JaggedPass_EventScript_MagmaHideoutGuard_Item::

call FALSE
release
return

JaggedPass_EventScript_Diana_Item::

call FALSE
release
return

JaggedPass_EventScript_Autumn_Item::

call FALSE
release
return

JaggedPass_EventScript_Julio_Item::

call FALSE
release
return

JaggedPass_EventScript_Ethan_Item::

call FALSE
release
return

LavaridgeTown_HerbShop_EventScript_OldMan_Item::
giveitem ITEM_CHARCOAL

call FALSE
release
return

LavaridgeTown_EventScript_MayGiveGoGoggles_ITEM::
giveitem ITEM_GO_GOGGLES

call FALSE
release
return

LavaridgeTown_EventScript_EggWoman_Item::
giveegg SPECIES_WYNAUT

call FALSE
release
return

LavaridgeTown_Gym_B1F_EventScript_Jeff_Item::

call FALSE
release
return

LavaridgeTown_Gym_B1F_EventScript_Jace_Item::

call FALSE
release
return

LavaridgeTown_Gym_B1F_EventScript_Eli_Item::

call FALSE
release
return

LavaridgeTown_Gym_1F_EventScript_Cole_Item::

call FALSE
release
return

LavaridgeTown_Gym_1F_EventScript_Gerald_Item::

call FALSE
release
return

LavaridgeTown_Gym_1F_EventScript_Axle_Item::

call FALSE
release
return

LavaridgeTown_Gym_B1F_EventScript_Keegan_Item::

call FALSE
release
return

LavaridgeTown_Gym_1F_EventScript_Danielle_Item::

call FALSE
release
return

LavaridgeTown_Gym_1F_EventScript_Flannery_Item::

call FALSE
release
return

Lavaridge_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_BADGE04_GET
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT

call FALSE
release
return

LilycoveCity_House2_EventScript_FatMan_Item::
giveitem ITEM_TM44

call FALSE
release
return

LilycoveCity_EventScript_ItemMaxRepel::
finditem ITEM_MAX_REPEL

call FALSE
release
return

LilycoveCity_EventScript_Rival_Item::

call FALSE
release
return

LittlerootTown_ProfessorBirchsLab_EventScript_MayGivePokeBalls_Items::
giveitem ITEM_POKE_BALL 5

call FALSE
release
return

MagmaHideout_1F_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

call FALSE
release
return

MagmaHideout_3F_1R_EventScript_ItemNugget::
finditem ITEM_NUGGET

call FALSE
release
return

MagmaHideout_4F_EventScript_ItemMaxRevive::
finditem ITEM_MAX_REVIVE

call FALSE
release
return

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
finditem ITEM_ESCAPE_ROPE

call FALSE
release
return

MagmaHideout_3F_2R_EventScript_ItemPPMax::
finditem ITEM_PP_MAX

call FALSE
release
return

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
finditem ITEM_FULL_RESTORE

call FALSE
release
return

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
finditem ITEM_MAX_ELIXIR

call FALSE
release
return

MagmaHideout_1F_EventScript_Grunt1_Item::

call FALSE
release
return

MagmaHideout_1F_EventScript_Grunt2_Item::

call FALSE
release
return

MagmaHideout_2F_1R_EventScript_Grunt3_Item::

call FALSE
release
return

MagmaHideout_2F_1R_EventScript_Grunt4_Item::

call FALSE
release
return

MagmaHideout_2F_1R_EventScript_Grunt5_Item::

call FALSE
release
return

MagmaHideout_2F_2R_EventScript_Grunt6_Item::

call FALSE
release
return

MagmaHideout_2F_2R_EventScript_Grunt7_Item::

call FALSE
release
return

MagmaHideout_2F_2R_EventScript_Grunt8_Item::

call FALSE
release
return

MagmaHideout_3F_1R_EventScript_Grunt9_Item::

call FALSE
release
return

MagmaHideout_3F_2R_EventScript_Grunt10_Item::

call FALSE
release
return

MagmaHideout_4F_EventScript_Grunt11_Item::

call FALSE
release
return

MagmaHideout_4F_EventScript_Grunt12_Item::

call FALSE
release
return

MagmaHideout_4F_EventScript_Grunt13_Item::

call FALSE
release
return

MagmaHideout_2F_1R_EventScript_Grunt14_Item::

call FALSE
release
return

MagmaHideout_2F_2R_EventScript_Grunt15_Item::

call FALSE
release
return

MagmaHideout_3F_1R_EventScript_Grunt16_Item::

call FALSE
release
return

MagmaHideout_4F_EventScript_Tabitha_Item::

call FALSE
release
return

MagmaHideout_4F_EventScript_Maxie_Item::

call FALSE
release
return

MarineCave_End_EventScript_Kyogre_Item::

call FALSE
release
return

MauvilleCity_House2_EventScript_AcceptTrade_Item::
giveitem ITEM_COIN_CASE

call FALSE
release
return

MauvilleCity_EventScript_ItemXSpeed::
finditem ITEM_X_SPEED

call FALSE
release
return

MauvilleCity_House1_EventScript_RockSmashDude_Item::
giveitem ITEM_HM06

call FALSE
release
return

MauvilleCity_EventScript_Wattson_Item::
giveitem ITEM_BASEMENT_KEY

call FALSE
release
return

MauvilleCity_EventScript_CompletedNewMauville_Item::
giveitem ITEM_TM24

call FALSE
release
return

MauvilleCity_EventScript_DefeatedWally_Item::

call FALSE
release
return

MauvilleCity_Gym_EventScript_Vivian_Item::

call FALSE
release
return

MauvilleCity_Gym_EventScript_Kirk_Item::

call FALSE
release
return

MauvilleCity_Gym_EventScript_Ben_Item::

call FALSE
release
return

MauvilleCity_Gym_EventScript_Angelo_Item::

call FALSE
release
return

MauvilleCity_Gym_EventScript_Shawn_Item::

call FALSE
release
return

MauvilleCity_Gym_EventScript_Wattson_Item::

call FALSE
release
return

Mauville_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_BADGE03_GET
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT

call FALSE
release
return

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
finditem ITEM_FULL_HEAL

call FALSE
release
return

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
finditem ITEM_MOON_STONE

call FALSE
release
return

MeteorFalls_1F_1R_EventScript_ItemTM23::
finditem ITEM_TM23

call FALSE
release
return

MeteorFalls_B1F_2R_EventScript_ItemTM02::
finditem ITEM_TM02

call FALSE
release
return

MeteorFalls_1F_1R_EventScript_ItemPPUP::
finditem ITEM_PP_UP

call FALSE
release
return

MeteorFalls_1F_2R_EventScript_John_Item::

call FALSE
release
return

MeteorFalls_1F_2R_EventScript_Nicolas_Item::

call FALSE
release
return

MeteorFalls_StevensCave_EventScript_Steven_Item::

call FALSE
release
return

MossdeepCity_EventScript_ItemNetBall::
finditem ITEM_NET_BALL

call FALSE
release
return

MossdeepCity_EventScript_KingsRockBoy_Item::
giveitem ITEM_KINGS_ROCK

call FALSE
release
return

MossdeepCity_StevensHouse_EventScript_StevenGivesDive_Item::
giveitem ITEM_HM08

call FALSE
release
return

MossdeepCity_House3_EventScript_SuperRodFisherman_Item::
giveitem ITEM_SUPER_ROD

call FALSE
release
return

MossdeepCity_StevensHouse_EventScript_GiveBeldum_Item::


        setvar VAR_TEMP_1, SPECIES_FOMANTIS
       setvar VAR_TEMP_2, 5
       call Get_Pokemon

call FALSE
release
return

MossdeepCity_Gym_EventScript_Preston_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Maura_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Samantha_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Blake_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Macey_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Clifford_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Kathleen_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Nicholas_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Nate_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Virgil_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Sylvia_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_Hannah_Item::

call FALSE
release
return

MossdeepCity_Gym_EventScript_TateAndLiza_Item::

call FALSE
release
return

Mosdeep_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_BADGE07_GET
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT

call FALSE
release
return

MtChimney_EventScript_MeteoriteMachine_Item::
giveitem ITEM_METEORITE

call FALSE
release
return

MtPyre_1F_EventScript_CleanseTagWoman_Item::
giveitem ITEM_CLEANSE_TAG

call FALSE
release
return

MtPyre_2F_EventScript_ItemUltraBall::
finditem ITEM_ULTRA_BALL

call FALSE
release
return

MtPyre_3F_EventScript_ItemSuperRepel::
finditem ITEM_SUPER_REPEL

call FALSE
release
return

MtPyre_4F_EventScript_ItemSeaIncense::
finditem ITEM_SEA_INCENSE

call FALSE
release
return

MtPyre_5F_EventScript_ItemLaxIncense::
finditem ITEM_LAX_INCENSE

call FALSE
release
return

MtPyre_6F_EventScript_ItemTM30::
finditem ITEM_TM30

call FALSE
release
return

MtPyre_Exterior_EventScript_ItemTM48::
finditem ITEM_TM48

call FALSE
release
return

MtPyre_Exterior_EventScript_ItemMaxPotion::
finditem ITEM_MAX_POTION

call FALSE
release
return

MtPyre_Summit_EventScript_TeamAquaExits_Item::
giveitem ITEM_MAGMA_EMBLEM

call FALSE
release
return

MtPyre_2F_EventScript_Mark_Item::

call FALSE
release
return

MtPyre_2F_EventScript_Leah_Item::

call FALSE
release
return

MtPyre_2F_EventScript_Zander_Item::

call FALSE
release
return

MtPyre_2F_EventScript_Dez_Item::

call FALSE
release
return

MtPyre_3F_EventScript_Kayla_Item::

call FALSE
release
return

MtPyre_3F_EventScript_Gabrielle_Item::

call FALSE
release
return

MtPyre_3F_EventScript_William_Item::

call FALSE
release
return

MtPyre_4F_EventScript_Tasha_Item::

call FALSE
release
return

MtPyre_5F_EventScript_Atsushi_Item::

call FALSE
release
return

MtPyre_6F_EventScript_Valerie_Item::

call FALSE
release
return

MtPyre_6F_EventScript_Cedric_Item::

call FALSE
release
return

MtPyre_Summit_EventScript_Grunt1_Item::

call FALSE
release
return

MtPyre_Summit_EventScript_Grunt2_Item::

call FALSE
release
return

MtPyre_Summit_EventScript_Grunt3_Item::

call FALSE
release
return

MtPyre_Summit_EventScript_Grunt4_Item::

call FALSE
release
return

NavelRock_Top_EventScript_HoOh_ITEM::

call FALSE
release
return

NewMauville_Inside_EventScript_ItemEscapeRope::
finditem ITEM_ESCAPE_ROPE

call FALSE
release
return

NewMauville_Inside_EventScript_ItemUltraBall::
finditem ITEM_ULTRA_BALL

call FALSE
release
return

NewMauville_Inside_EventScript_ItemParalyzeHeal::
finditem ITEM_PARALYZE_HEAL

call FALSE
release
return

NewMauville_Inside_EventScript_ItemFullHeal::
finditem ITEM_FULL_HEAL

call FALSE
release
return

NewMauville_Inside_EventScript_ItemThunderStone::
finditem ITEM_THUNDER_STONE

call FALSE
release
return

NewMauville_Inside_EventScript_Voltorb1_Item::

call FALSE
release
return

NewMauville_Inside_EventScript_Voltorb2_Item::

call FALSE
release
return

NewMauville_Inside_EventScript_Voltorb3_Item::

call FALSE
release
return

OldaleTown_EventScript_ExplainPokemonMart_Item::
giveitem ITEM_POTION

call FALSE
release
return

PacifidlogTown_House2_EventScript_GiveFrustration_Item::
giveitem ITEM_TM21

call FALSE
release
return

PacifidlogTown_House2_EventScript_GiveReturn_Item::
giveitem ITEM_TM27

call FALSE
release
return

PetalburgCity_WallysHouse_EventScript_GiveHM03Surf_Item::
giveitem ITEM_HM03

call FALSE
release
return

PetalburgCity_EventScript_ItemMaxRevive::
finditem ITEM_MAX_REVIVE

call FALSE
release
return

PetalburgCity_EventScript_ItemEther::
finditem ITEM_ETHER

call FALSE
release
return

PetalburgCity_Gym_EventScript_Randall_Item::

call FALSE
release
return

PetalburgCity_Gym_EventScript_Mary_Item::

call FALSE
release
return

PetalburgCity_Gym_EventScript_Parker_Item::

call FALSE
release
return

PetalburgCity_Gym_EventScript_Alexia_Item::

call FALSE
release
return

PetalburgCity_Gym_EventScript_George_Item::

call FALSE
release
return

PetalburgCity_Gym_EventScript_Jody_Item::

call FALSE
release
return

PetalburgCity_Gym_EventScript_Berke_Item::

call FALSE
release
return

PetalburgCity_Gym_EventScript_NormanBattle_Item::

call FALSE
release
return

Petalburg_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_BADGE05_GET
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT

call FALSE
release
return

PetalburgWoods_EventScript_ItemParalyzeHeal::
giveitem ITEM_PARALYZE_HEAL

call FALSE
release
return

PetalburgWoods_EventScript_DevonResearcherPostBattle_Item::
giveitem ITEM_GREAT_BALL

call FALSE
release
return

PetalburgWoods_EventScript_ItemEther::
finditem ITEM_ETHER

call FALSE
release
return

PetalburgWoods_EventScript_Girl_Item::
giveitem ITEM_MIRACLE_SEED

call FALSE
release
return

PetalburgWoods_EventScript_ItemGreatBall::
giveitem ITEM_GREAT_BALL

call FALSE
release
return

PetalburgWoods_EventScript_ItemXAttack::
giveitem ITEM_X_ATTACK

call FALSE
release
return

PetalburgWoods_EventScript_Lyle_Item::

call FALSE
release
return

PetalburgWoods_EventScript_James_Item::

call FALSE
release
return

PetalburgWoods_EventScript_DevonResearcherLeft_Item::

call FALSE
release
return

Route102_EventScript_ItemPotion::
finditem ITEM_POTION

call FALSE
release
return

Route102_EventScript_Calvin_Item::

call FALSE
release
return

Route102_EventScript_Rick_Item::

call FALSE
release
return

Route102_EventScript_Allen_Item::

call FALSE
release
return

Route102_EventScript_Tiana_Item::

call FALSE
release
return

Route103_EventScript_ItemGuardSpec::
finditem ITEM_GUARD_SPEC

call FALSE
release
return

Route103_EventScript_ItemPPUp::
finditem ITEM_PP_UP

call FALSE
release
return

Route103_EventScript_Item_Rival::

call FALSE
release
return

Route104_EventScript_ItemPokeBall::
finditem ITEM_POKE_BALL

call FALSE
release
return

Route104_EventScript_Boy2_Item::
giveitem ITEM_TM09

call FALSE
release
return

Route104_EventScript_ItemPotion::
finditem ITEM_POTION

call FALSE
release
return

Route104_EventScript_ItemXAccuracy::
finditem ITEM_X_ACCURACY

call FALSE
release
return

Route104_EventScript_ItemPPUp::
finditem ITEM_PP_UP

call FALSE
release
return

Route104_EventScript_WhiteHerbFlorist_Item::
giveitem ITEM_WHITE_HERB

call FALSE
release
return

Route104_PrettyPetalFlowerShop_EventScript_GiveWailmerPail_ITEM::
giveitem ITEM_WAILMER_PAIL

call FALSE
release
return

Route105_EventScript_ItemIron::
finditem ITEM_IRON

call FALSE
release
return

Route105_EventScript_Imani_Item::

call FALSE
release
return

Route105_EventScript_Dominik_Item::

call FALSE
release
return

Route105_EventScript_Foster_Item::

call FALSE
release
return

Route105_EventScript_Beverly_Item::

call FALSE
release
return

Route105_EventScript_Andres_Item::

call FALSE
release
return

Route105_EventScript_Josue_Item::

call FALSE
release
return

Route105_EventScript_Luis_Item::

call FALSE
release
return

Route106_EventScript_ItemProtein::
finditem ITEM_PROTEIN

call FALSE
release
return

Route106_EventScript_Ned_Item::

call FALSE
release
return

Route106_EventScript_Elliot_Item::

call FALSE
release
return

Route106_EventScript_Douglas_Item::

call FALSE
release
return

Route106_EventScript_Kyla_Item::

call FALSE
release
return

Route107_EventScript_Denise_Item::

call FALSE
release
return

Route107_EventScript_Tony_Item::

call FALSE
release
return

Route107_EventScript_Lisa_Item::

call FALSE
release
return

Route107_EventScript_Darrin_Item::

call FALSE
release
return

Route107_EventScript_Beth_Item::

call FALSE
release
return

Route107_EventScript_Camron_Item::

call FALSE
release
return

Route108_EventScript_ItemStarPiece::
finditem ITEM_STAR_PIECE

call FALSE
release
return

Route108_EventScript_Missy_Item::

call FALSE
release
return

Route108_EventScript_Matthew_Item::

call FALSE
release
return

Route108_EventScript_Tara_Item::

call FALSE
release
return

Route108_EventScript_Carolina_Item::

call FALSE
release
return

Route108_EventScript_Cory_Item::

call FALSE
release
return

Route108_EventScript_Jerome_Item::

call FALSE
release
return

Route109_EventScript_SoftSandGirl_ITEM::
giveitem ITEM_SOFT_SAND

call FALSE
release
return

Route109_SeashoreHouse_EventScript_DefeatedTrainers_Item::
giveitem ITEM_SODA_POP, 6

call FALSE
release
return

Route109_EventScript_ItemPotion::
finditem ITEM_POTION

call FALSE
release
return

Route109_EventScript_ItemPPUp::
finditem ITEM_PP_UP

call FALSE
release
return

Route109_EventScript_Huey_Item::

call FALSE
release
return

Route109_EventScript_Edmond_Item::

call FALSE
release
return

Route109_EventScript_Hailey_Item::

call FALSE
release
return

Route109_EventScript_Ricky_Item::

call FALSE
release
return

Route109_EventScript_Lola_Item::

call FALSE
release
return

Route109_EventScript_Chandler_Item::

call FALSE
release
return

Route109_SeashoreHouse_EventScript_Simon_Item::

call FALSE
release
return

Route109_SeashoreHouse_EventScript_Johanna_Item::

call FALSE
release
return

Route109_SeashoreHouse_EventScript_Dwayne_Item::

call FALSE
release
return

Route109_EventScript_Austina_Item::

call FALSE
release
return

Route109_EventScript_Gwen_Item::

call FALSE
release
return

Route109_EventScript_David_Item::

call FALSE
release
return

Route109_EventScript_Alice_Item::

call FALSE
release
return

Route109_EventScript_Carter_Item::

call FALSE
release
return

Route109_EventScript_Elijah_Item::

call FALSE
release
return

Route109_EventScript_Mel_Item::

call FALSE
release
return

Route110_EventScript_ItemDireHit::
finditem ITEM_DIRE_HIT

call FALSE
release
return

Route110_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

call FALSE
release
return

Route110_EventScript_GiveItemfinder_Item::
giveitem ITEM_DOWSING_MACHINE

call FALSE
release
return

Route110_EventScript_ItemElixir::
finditem ITEM_ELIXIR

call FALSE
release
return

Route110_EventScript_Isabel_Item::

call FALSE
release
return

Route110_EventScript_Kaleb_Item::

call FALSE
release
return

Route110_EventScript_Timmy_Item::

call FALSE
release
return

Route110_EventScript_Edwin_Item::

call FALSE
release
return

Route110_EventScript_Joseph_Item::

call FALSE
release
return

Route110_EventScript_Edward_Item::

call FALSE
release
return

Route110_EventScript_Alyssa_Item::

call FALSE
release
return

Route110_EventScript_Dale_Item::

call FALSE
release
return

Route110_EventScript_GiveItemfinder_Item2::

call FALSE
release
return

Route110_EventScript_Jaclyn_Item::

call FALSE
release
return

Route110_EventScript_Abigail_Item::

call FALSE
release
return

Route110_EventScript_Anthony_Item::

call FALSE
release
return

Route110_EventScript_Benjamin_Item::

call FALSE
release
return

Route110_EventScript_Jasmine_Item::

call FALSE
release
return

Route110_EventScript_Jacob_Item::

call FALSE
release
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle1_Item::
giveitem ITEM_RARE_CANDY

call FALSE
release
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle2_Item::
giveitem ITEM_TIMER_BALL

call FALSE
release
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle3_Item::
giveitem ITEM_HARD_STONE

call FALSE
release
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle4_Item::
giveitem ITEM_SMOKE_BALL

call FALSE
release
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle5_Item::
giveitem ITEM_TM12

call FALSE
release
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle6_Item::
giveitem ITEM_MAGNET

call FALSE
release
return

Route110_TrickHouseEnd_EventScript_CompletedPuzzle7_Item::
giveitem ITEM_PP_MAX

call FALSE
release
return

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
finditem ITEM_ORANGE_MAIL

call FALSE
release
return

Route110_TrickHousePuzzle1_EventScript_Sally_Item::

call FALSE
release
return

Route110_TrickHousePuzzle1_EventScript_Robin_Item::

call FALSE
release
return

Route110_TrickHousePuzzle1_EventScript_Eddie_Item::

call FALSE
release
return

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
finditem ITEM_WAVE_MAIL

call FALSE
release
return

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
finditem ITEM_HARBOR_MAIL

call FALSE
release
return

Route110_TrickHousePuzzle2_EventScript_Ted_Item::

call FALSE
release
return

Route110_TrickHousePuzzle2_EventScript_Paul_Item::

call FALSE
release
return

Route110_TrickHousePuzzle2_EventScript_Georgia_Item::

call FALSE
release
return

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
finditem ITEM_WOOD_MAIL

call FALSE
release
return

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
finditem ITEM_SHADOW_MAIL

call FALSE
release
return

Route110_TrickHousePuzzle3_EventScript_Justin_Item::

call FALSE
release
return

Route110_TrickHousePuzzle3_EventScript_Martha_Item::

call FALSE
release
return

Route110_TrickHousePuzzle3_EventScript_Alan_Item::

call FALSE
release
return

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
finditem ITEM_MECH_MAIL

call FALSE
release
return

Route110_TrickHousePuzzle4_EventScript_Yuji_Item::

call FALSE
release
return

Route110_TrickHousePuzzle4_EventScript_Cora_Item::

call FALSE
release
return

Route110_TrickHousePuzzle4_EventScript_Paula_Item::

call FALSE
release
return

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
finditem ITEM_GLITTER_MAIL

call FALSE
release
return

Route110_TrickHousePuzzle6_EventScript_Sophia_Item::

call FALSE
release
return

Route110_TrickHousePuzzle6_EventScript_Sebastian_Item::

call FALSE
release
return

Route110_TrickHousePuzzle6_EventScript_Benny_Item::

call FALSE
release
return

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
finditem ITEM_TROPIC_MAIL

call FALSE
release
return

Route110_TrickHousePuzzle7_EventScript_Joshua_Item::

call FALSE
release
return

Route110_TrickHousePuzzle7_EventScript_Patricia_Item::

call FALSE
release
return

Route110_TrickHousePuzzle7_EventScript_Mariela_Item::

call FALSE
release
return

Route110_TrickHousePuzzle7_EventScript_Everett_Item::

call FALSE
release
return

Route110_TrickHousePuzzle7_EventScript_Alexis_Item::

call FALSE
release
return

Route110_TrickHousePuzzle7_EventScript_Alvaro_Item::

call FALSE
release
return

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
finditem ITEM_BEAD_MAIL

call FALSE
release
return

Route110_TrickHousePuzzle8_EventScript_Keira_Item::

call FALSE
release
return

Route110_TrickHousePuzzle8_EventScript_Vincent_Item::

call FALSE
release
return

Route110_TrickHousePuzzle8_EventScript_Leroy_Item::

call FALSE
release
return

Route111_WinstrateFamilysHouse_EventScript_Victoria_Item_Brace::
giveitem ITEM_MACHO_BRACE

call FALSE
release
return

Route111_EventScript_ItemHPUp::
finditem ITEM_HP_UP

call FALSE
release
return

Route111_EventScript_ItemElixir::
finditem ITEM_ELIXIR

call FALSE
release
return

Route111_EventScript_ItemStardust::
finditem ITEM_STARDUST

call FALSE
release
return

Route111_EventScript_Girl_Item::
giveitem ITEM_RAZZ_BERRY

call FALSE
release
return

Route111_EventScript_ItemTM37::
finditem ITEM_TM37

call FALSE
release
return

Route111_EventScript_GiveSecretPower_Item::
giveitem ITEM_TM43

call FALSE
release
return

Route111_EventScript_Tyron_Item::

call FALSE
release
return

Route111_EventScript_Celina_Item::

call FALSE
release
return

Route111_EventScript_Bianca_Item::

call FALSE
release
return

Route111_EventScript_Hayden_Item::

call FALSE
release
return

Gabby_Ty_EventScript_1_Item::

call FALSE
release
return

Route111_EventScript_Irene_Item::

call FALSE
release
return

Route111_EventScript_Travis_Item::

call FALSE
release
return

Route111_EventScript_Heidi_Item::

call FALSE
release
return

Route111_EventScript_Beau_Item::

call FALSE
release
return

Route111_EventScript_Drew_Item::

call FALSE
release
return

Route111_EventScript_Becky_Item::

call FALSE
release
return

Route111_EventScript_Dusty_Item::

call FALSE
release
return

Route111_EventScript_Celia_Item::

call FALSE
release
return

Route111_EventScript_Bryan_Item::

call FALSE
release
return

Route111_EventScript_Branden_Item::

call FALSE
release
return

Route111_EventScript_Wilton_Item::

call FALSE
release
return

Route111_EventScript_Brooke_Item::

call FALSE
release
return

Route111_EventScript_Daisuke_Item::

call FALSE
release
return

Route111_EventScript_Victor_Item::

call FALSE
release
return

Route111_WinstrateFamilysHouse_EventScript_Victoria_Item::

call FALSE
release
return

Route111_WinstrateFamilysHouse_EventScript_Vivi_Item::

call FALSE
release
return

Route111_WinstrateFamilysHouse_EventScript_Vicky_Item::

call FALSE
release
return

Route112_EventScript_ItemNugget::
finditem ITEM_NUGGET

call FALSE
release
return

Route112_EventScript_Larry_Item::

call FALSE
release
return

Route112_EventScript_Carol_Item::

call FALSE
release
return

Route112_EventScript_Trent_Item::

call FALSE
release
return

Route112_EventScript_Brice_Item::

call FALSE
release
return

Route112_EventScript_Bryant_Item::

call FALSE
release
return

Route112_EventScript_Shayla_Item::

call FALSE
release
return

Route113_EventScript_ItemMaxEther::
finditem ITEM_MAX_ETHER

call FALSE
release
return

Route113_GlassWorkshop_EventScript_GlassWorker_Item::
giveitem ITEM_SOOT_SACK

call FALSE
release
return

Route113_EventScript_ItemHyperPotion::
finditem ITEM_HYPER_POTION

call FALSE
release
return

Route113_EventScript_ItemSuperRepel::
finditem ITEM_SUPER_REPEL

call FALSE
release
return

Route113_EventScript_Jaylen_Item::

call FALSE
release
return

Route113_EventScript_Lawrence_Item::

call FALSE
release
return

Route113_EventScript_Lung_Item::

call FALSE
release
return

Route113_EventScript_Wyatt_Item::

call FALSE
release
return

Route113_EventScript_Madeline_Item::

call FALSE
release
return

Route113_EventScript_Tori_Item::

call FALSE
release
return

Route113_EventScript_Lao_Item::

call FALSE
release
return

Route113_EventScript_Dillon_Item::

call FALSE
release
return

Route113_EventScript_Sophie_Item::

call FALSE
release
return

Route113_EventScript_Coby_Item::

call FALSE
release
return

Route114_FossilManiacsHouse_EventScript_FossilManiacsBrother_Item::
giveitem ITEM_TM28

call FALSE
release
return

Route114_EventScript_RoarGentleman_Item::
giveitem ITEM_TM05

call FALSE
release
return

Route114_EventScript_ItemEnergyPowder::
finditem ITEM_ENERGY_POWDER

call FALSE
release
return

Route114_EventScript_ItemProtein::
finditem ITEM_PROTEIN

call FALSE
release
return

Route114_LanettesHouse_EventScript_Lanette_Item::
giveitem DECOR_LOTAD_DOLL

call FALSE
release
return

Route114_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

call FALSE
release
return

Route114_EventScript_Nolan_Item::

call FALSE
release
return

Route114_EventScript_Charlotte_Item::

call FALSE
release
return

Route114_EventScript_Kai_Item::

call FALSE
release
return

Route114_EventScript_Claude_Item::

call FALSE
release
return

Route114_EventScript_Nancy_Item::

call FALSE
release
return

Route114_EventScript_Tyra_Item::

call FALSE
release
return

Route114_EventScript_Shane_Item::

call FALSE
release
return

Route114_EventScript_Steve_Item::

call FALSE
release
return

Route114_EventScript_Bernie_Item::

call FALSE
release
return

Route114_EventScript_Lucas_Item::

call FALSE
release
return

Route114_EventScript_Angelina_Item::

call FALSE
release
return

Route114_EventScript_Lenny_Item::

call FALSE
release
return

Route115_EventScript_ItemSuperPotion::
finditem ITEM_SUPER_POTION

call FALSE
release
return

Route115_EventScript_ItemGreatBall::
finditem ITEM_GREAT_BALL

call FALSE
release
return

Route115_EventScript_ItemPPUp::
finditem ITEM_PP_UP

call FALSE
release
return

Route115_EventScript_ItemTM01::
finditem ITEM_TM01

call FALSE
release
return

Route115_EventScript_ItemHealPowder::
finditem ITEM_HEAL_POWDER

call FALSE
release
return

Route115_EventScript_ItemIron::
finditem ITEM_IRON

call FALSE
release
return

Route115_EventScript_Nob_Item::

call FALSE
release
return

Route115_EventScript_Hector_Item::

call FALSE
release
return

Route115_EventScript_Marlene_Item::

call FALSE
release
return

Route115_EventScript_Cyndy_Item::

call FALSE
release
return

Route115_EventScript_Jaiden_Item::

call FALSE
release
return

Route115_EventScript_Timothy_Item::

call FALSE
release
return

Route115_EventScript_Kyra_Item::

call FALSE
release
return

Route115_EventScript_Koichi_Item::

call FALSE
release
return

Route115_EventScript_Helene_Item::

call FALSE
release
return

Route115_EventScript_Alix_Item::

call FALSE
release
return

Route116_EventScript_ItemRepel::
finditem ITEM_REPEL

call FALSE
release
return

Route116_EventScript_ItemXSpecial::
finditem ITEM_X_SP_ATK

call FALSE
release
return

Route116_EventScript_ItemEther::
finditem ITEM_ETHER

call FALSE
release
return

Route116_EventScript_ItemPotion::
finditem ITEM_POTION

call FALSE
release
return

Route116_EventScript_GiveRepeatBall_Item::
finditem ITEM_REPEAT_BALL

call FALSE
release
return

Route116_EventScript_ItemHPUp::
finditem ITEM_HP_UP

call FALSE
release
return

Route116_EventScript_Jose_Item::

call FALSE
release
return

Route116_EventScript_Joey_Item::

call FALSE
release
return

Route116_EventScript_Karen_Item::

call FALSE
release
return

Route116_EventScript_Clark_Item::

call FALSE
release
return

Route116_EventScript_Johnson_Item::

call FALSE
release
return

Route116_EventScript_Devan_Item::

call FALSE
release
return

Route116_EventScript_Sarah_Item::

call FALSE
release
return

Route116_EventScript_Dawson_Item::

call FALSE
release
return

Route116_EventScript_Jerry_Item::

call FALSE
release
return

Route116_EventScript_Janice_Item::

call FALSE
release
return

Route117_EventScript_ItemRevive::
finditem ITEM_REVIVE

call FALSE
release
return

Route117_EventScript_ItemGreatBall::
finditem ITEM_GREAT_BALL

call FALSE
release
return

Route117_EventScript_Dylan_Item::

call FALSE
release
return

Route117_EventScript_Anna_Item::

call FALSE
release
return

Route117_EventScript_Isaac_Item::

call FALSE
release
return

Route117_EventScript_Maria_Item::

call FALSE
release
return

Route117_EventScript_Derek_Item::

call FALSE
release
return

Route117_EventScript_Brandi_Item::

call FALSE
release
return

Route117_EventScript_Melina_Item::

call FALSE
release
return

Route117_EventScript_Aisha_Item::

call FALSE
release
return

Route117_EventScript_Lydia_Item::

call FALSE
release
return

Route118_EventScript_ReceiveGoodRod_Item::
giveitem ITEM_GOOD_ROD

call FALSE
release
return

Route118_EventScript_ItemHyperPotion::
finditem ITEM_HYPER_POTION

call FALSE
release
return

Route118_EventScript_Rose_Item::

call FALSE
release
return

Route118_EventScript_Deandre_Item::

call FALSE
release
return

Route118_EventScript_Wade_Item::

call FALSE
release
return

Route118_EventScript_Dalton_Item::

call FALSE
release
return

Gabby_Ty_EventScript_2_Item::

call FALSE
release
return

Route118_EventScript_Barny_Item::

call FALSE
release
return

Route118_EventScript_Chester_Item::

call FALSE
release
return

Route118_EventScript_Perry_Item::

call FALSE
release
return

Route119_EventScript_ItemElixir::
finditem ITEM_ELIXIR

call FALSE
release
return

Route119_EventScript_ItemElixir2::
finditem ITEM_ELIXIR

call FALSE
release
return

Route119_EventScript_ItemLeafStone::
finditem ITEM_LEAF_STONE

call FALSE
release
return

Route119_EventScript_GiveFlyHM_Item::
giveitem ITEM_HM02

call FALSE
release
return

Route119_EventScript_ItemSuperRepel::
finditem ITEM_SUPER_REPEL

call FALSE
release
return

Route119_EventScript_ItemHyperPotion::
finditem ITEM_HYPER_POTION

call FALSE
release
return

Route119_EventScript_ItemHyperPotion2::
finditem ITEM_HYPER_POTION

call FALSE
release
return

Route119_EventScript_ItemZinc::
finditem ITEM_ZINC

call FALSE
release
return

Route119_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

call FALSE
release
return

Route119_EventScript_ItemNugget::
finditem ITEM_NUGGET

call FALSE
release
return

Route119_EventScript_Kent_Item::

call FALSE
release
return

Route119_EventScript_Donald_Item::

call FALSE
release
return

Route119_EventScript_Greg_Item::

call FALSE
release
return

Route119_EventScript_Taylor_Item::

call FALSE
release
return

Route119_EventScript_Doug_Item::

call FALSE
release
return

Route119_EventScript_Brent_Item::

call FALSE
release
return

Route119_EventScript_Chris_Item::

call FALSE
release
return

Route119_EventScript_Catherine_Item::

call FALSE
release
return

Route119_EventScript_Jackson_Item::

call FALSE
release
return

Route119_EventScript_Rachel_Item::

call FALSE
release
return

Route119_EventScript_Phil_Item::

call FALSE
release
return

Route119_EventScript_Takashi_Item::

call FALSE
release
return

Route119_EventScript_Dayton_Item::

call FALSE
release
return

Route119_EventScript_Hugh_Item::

call FALSE
release
return

Route119_EventScript_Fabian_Item::

call FALSE
release
return

Route119_EventScript_Yasu_Item::

call FALSE
release
return

Route119_EventScript_Hideo_Item::

call FALSE
release
return

Route119_EventScript_RivalExitScottArrive_Item::

call FALSE
release
return

Route119_WeatherInstitute_2F_EventScript_ReceiveCastform_Item::


        setvar VAR_TEMP_1, SPECIES_ALOMOMOLA
       setvar VAR_TEMP_2, 5
       call Get_Pokemon

call FALSE
release
return

Route119_WeatherInstitute_1F_EventScript_Grunt1_Item::

call FALSE
release
return

Route119_WeatherInstitute_2F_EventScript_Grunt2_Item::

call FALSE
release
return

Route119_WeatherInstitute_2F_EventScript_Grunt3_Item::

call FALSE
release
return

Route119_WeatherInstitute_1F_EventScript_Grunt4_Item::

call FALSE
release
return

Route119_WeatherInstitute_2F_EventScript_Grunt5_Item::

call FALSE
release
return

Route119_WeatherInstitute_2F_EventScript_Shelly_Item::

call FALSE
release
return

Route120_EventScript_StevenGiveDeconScope_ITEM::
giveitem ITEM_DEVON_SCOPE

call FALSE
release
return

Route120_EventScript_ItemNestBall::
finditem ITEM_NEST_BALL

call FALSE
release
return

Route120_EventScript_ItemRevive::
finditem ITEM_REVIVE

call FALSE
release
return

Route120_EventScript_ItemNugget::
finditem ITEM_NUGGET

call FALSE
release
return

Route120_EventScript_ItemFullHeal::
finditem ITEM_FULL_HEAL

call FALSE
release
return

Route120_EventScript_ItemHyperPotion::
finditem ITEM_HYPER_POTION

call FALSE
release
return

Route120_EventScript_Clarissa_Item::

call FALSE
release
return

Gabby_Ty_EventScript_3_Item::

call FALSE
release
return

Route120_EventScript_Robert_Item::

call FALSE
release
return

Route120_EventScript_Colin_Item::

call FALSE
release
return

Route120_EventScript_Leonel_Item::

call FALSE
release
return

Route120_EventScript_Angelica_Item::

call FALSE
release
return

Route120_EventScript_Riley_Item::

call FALSE
release
return

Route120_EventScript_Callie_Item::

call FALSE
release
return

Route120_EventScript_Jennifer_Item::

call FALSE
release
return

Route120_EventScript_Jenna_Item::

call FALSE
release
return

Route120_EventScript_Lorenzo_Item::

call FALSE
release
return

Route120_EventScript_Jeffrey_Item::

call FALSE
release
return

Route120_EventScript_Keigo_Item::

call FALSE
release
return

Route120_EventScript_Chip_Item::

call FALSE
release
return

Route121_EventScript_ItemZinc::
finditem ITEM_ZINC

call FALSE
release
return

Route121_EventScript_ItemRevive::
finditem ITEM_REVIVE

call FALSE
release
return

Route121_EventScript_ItemCarbos::
finditem ITEM_CARBOS

call FALSE
release
return

Route121_EventScript_Cale_Item::

call FALSE
release
return

Route121_EventScript_Tammy_Item::

call FALSE
release
return

Route121_EventScript_Jessica_Item::

call FALSE
release
return

Route121_EventScript_Kate_Item::

call FALSE
release
return

Route121_EventScript_Pat_Item::

call FALSE
release
return

Route121_EventScript_Myles_Item::

call FALSE
release
return

Route121_EventScript_Walter_Item::

call FALSE
release
return

Route121_EventScript_Vanessa_Item::

call FALSE
release
return

Route121_EventScript_Marcel_Item::

call FALSE
release
return

Route121_EventScript_Cristin_Item::

call FALSE
release
return

SafariZone_Southwest_EventScript_ItemMaxRevive::
finditem ITEM_MAX_REVIVE

call FALSE
release
return

SafariZone_Northwest_EventScript_ItemTM22::
finditem ITEM_TM22

call FALSE
release
return

SafariZone_North_EventScript_ItemCalcium::
finditem ITEM_CALCIUM

call FALSE
release
return

SafariZone_Southeast_EventScript_ItemBigPearl::
finditem ITEM_BIG_PEARL

call FALSE
release
return

SafariZone_Northeast_EventScript_ItemNugget::
finditem ITEM_NUGGET

call FALSE
release
return

Route123_EventScript_GigaDrainGirl_Item::
giveitem ITEM_TM19

call FALSE
release
return

Route123_EventScript_ItemElixir::
finditem ITEM_ELIXIR

call FALSE
release
return

Route123_EventScript_ItemRevivalHerb::
finditem ITEM_REVIVAL_HERB

call FALSE
release
return

Route123_EventScript_ItemPPUp::
finditem ITEM_PP_UP

call FALSE
release
return

Route123_EventScript_ItemCalcium::
finditem ITEM_CALCIUM

call FALSE
release
return

Route123_EventScript_ItemUltraBall::
finditem ITEM_ULTRA_BALL

call FALSE
release
return

Route123_EventScript_Davis_Item::

call FALSE
release
return

Route123_EventScript_Jazmyn_Item::

call FALSE
release
return

Route123_EventScript_Violet_Item::

call FALSE
release
return

Route123_EventScript_Miu_Item::

call FALSE
release
return

Route123_EventScript_Kindra_Item::

call FALSE
release
return

Route123_EventScript_Ed_Item::

call FALSE
release
return

Route123_EventScript_Wendy_Item::

call FALSE
release
return

Route123_EventScript_Braxton_Item::

call FALSE
release
return

Route123_EventScript_Fernando_Item::

call FALSE
release
return

Route123_EventScript_Alberto_Item::

call FALSE
release
return

Route123_EventScript_Jacki_Item::

call FALSE
release
return

Route123_EventScript_Frederick_Item::

call FALSE
release
return

Route124_EventScript_ItemBlueShard::
finditem ITEM_BLUE_SHARD

call FALSE
release
return

Route124_EventScript_ItemYellowShard::
finditem ITEM_YELLOW_SHARD

call FALSE
release
return

Route124_EventScript_ItemRedShard::
finditem ITEM_RED_SHARD

call FALSE
release
return

Route124_EventScript_Grace_Item::

call FALSE
release
return

Route124_EventScript_Declan_Item::

call FALSE
release
return

Route124_EventScript_Lila_Item::

call FALSE
release
return

Route124_EventScript_Spencer_Item::

call FALSE
release
return

Route124_EventScript_Jenny_Item::

call FALSE
release
return

Route124_EventScript_Chad_Item::

call FALSE
release
return

Route124_EventScript_Isabella_Item::

call FALSE
release
return

Route124_EventScript_Roland_Item::

call FALSE
release
return

Route125_EventScript_ItemBigPearl::
finditem ITEM_BIG_PEARL

call FALSE
release
return

Route125_EventScript_Ernest_Item::

call FALSE
release
return

Route125_EventScript_Nolen_Item::

call FALSE
release
return

Route125_EventScript_Sharon_Item::

call FALSE
release
return

Route125_EventScript_Tanya_Item::

call FALSE
release
return

Route125_EventScript_Presley_Item::

call FALSE
release
return

Route125_EventScript_Auron_Item::

call FALSE
release
return

Route125_EventScript_Stan_Item::

call FALSE
release
return

Route125_EventScript_Kim_Item::

call FALSE
release
return

Route126_EventScript_ItemGreenShard::
finditem ITEM_GREEN_SHARD

call FALSE
release
return

Route126_EventScript_Leonardo_Item::

call FALSE
release
return

Route126_EventScript_Isobel_Item::

call FALSE
release
return

Route126_EventScript_Dean_Item::

call FALSE
release
return

Route126_EventScript_Nikki_Item::

call FALSE
release
return

Route126_EventScript_Barry_Item::

call FALSE
release
return

Route126_EventScript_Sienna_Item::

call FALSE
release
return

Route126_EventScript_Pablo_Item::

call FALSE
release
return

Route126_EventScript_Brenda_Item::

call FALSE
release
return

Route127_EventScript_ItemZinc::
finditem ITEM_ZINC

call FALSE
release
return

Route127_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

call FALSE
release
return

Route127_EventScript_ItemCarbos::
finditem ITEM_CARBOS

call FALSE
release
return

Route128_EventScript_Ruben_Item::

call FALSE
release
return

Route128_EventScript_Alexa_Item::

call FALSE
release
return

Route128_EventScript_Wayne_Item::

call FALSE
release
return

Route128_EventScript_Isaiah_Item::

call FALSE
release
return

Route128_EventScript_Katelyn_Item::

call FALSE
release
return

Route128_EventScript_Carlee_Item::

call FALSE
release
return

Route128_EventScript_Harrison_Item::

call FALSE
release
return

Route129_EventScript_Reed_Item::

call FALSE
release
return

Route129_EventScript_Chase_Item::

call FALSE
release
return

Route129_EventScript_Allison_Item::

call FALSE
release
return

Route129_EventScript_Clarence_Item::

call FALSE
release
return

Route129_EventScript_Tisha_Item::

call FALSE
release
return

Route130_EventScript_Rodney_Item::

call FALSE
release
return

Route130_EventScript_Katie_Item::

call FALSE
release
return

Route130_EventScript_Santiago_Item::

call FALSE
release
return

Route131_EventScript_Kevin_Item::

call FALSE
release
return

Route131_EventScript_Talia_Item::

call FALSE
release
return

Route131_EventScript_Richard_Item::

call FALSE
release
return

Route131_EventScript_Kara_Item::

call FALSE
release
return

Route131_EventScript_Herman_Item::

call FALSE
release
return

Route131_EventScript_Susie_Item::

call FALSE
release
return

Route131_EventScript_Reli_Item::

call FALSE
release
return

Route132_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

call FALSE
release
return

Route132_EventScript_ItemProtein::
finditem ITEM_PROTEIN

call FALSE
release
return

Route132_EventScript_Gilbert_Item::

call FALSE
release
return

Route132_EventScript_Dana_Item::

call FALSE
release
return

Route132_EventScript_Ronald_Item::

call FALSE
release
return

Route132_EventScript_Kiyo_Item::

call FALSE
release
return

Route132_EventScript_Paxton_Item::

call FALSE
release
return

Route132_EventScript_Darcy_Item::

call FALSE
release
return

Route132_EventScript_Makayla_Item::

call FALSE
release
return

Route132_EventScript_Jonathan_Item::

call FALSE
release
return

Route133_EventScript_ItemBigPearl::
finditem ITEM_BIG_PEARL

call FALSE
release
return

Route133_EventScript_ItemMaxRevive::
finditem ITEM_MAX_REVIVE

call FALSE
release
return

Route133_EventScript_ItemStarPiece::
finditem ITEM_STAR_PIECE

call FALSE
release
return

Route133_EventScript_Franklin_Item::

call FALSE
release
return

Route133_EventScript_Warren_Item::

call FALSE
release
return

Route133_EventScript_Beck_Item::

call FALSE
release
return

Route133_EventScript_Debra_Item::

call FALSE
release
return

Route133_EventScript_Linda_Item::

call FALSE
release
return

Route133_EventScript_Conor_Item::

call FALSE
release
return

Route133_EventScript_Mollie_Item::

call FALSE
release
return

Route134_EventScript_ItemCarbos::
finditem ITEM_CARBOS

call FALSE
release
return

Route134_EventScript_ItemStarPiece::
finditem ITEM_STAR_PIECE

call FALSE
release
return

Route134_EventScript_Laurel_Item::

call FALSE
release
return

Route134_EventScript_Jack_Item::

call FALSE
release
return

Route134_EventScript_Hitoshi_Item::

call FALSE
release
return

Route134_EventScript_Reyna_Item::

call FALSE
release
return

Route134_EventScript_Hudson_Item::

call FALSE
release
return

Route134_EventScript_Aaron_Item::

call FALSE
release
return

Route134_EventScript_Marley_Item::

call FALSE
release
return

Route134_EventScript_Alex_Item::

call FALSE
release
return

Route134_EventScript_Kelvin_Item::

call FALSE
release
return

RustboroCity_EventScript_ItemXDefend::
finditem ITEM_X_DEFENSE

call FALSE
release
return

RustboroCity_Flat2_2F_EventScript_NinjaBoy_Item::
giveitem ITEM_PREMIER_BALL

call FALSE
release
return

RustboroCity_CuttersHouse_EventScript_Cutter_Item::
giveitem ITEM_HM01

call FALSE
release
return

RustboroCity_EventScript_ReturnGoods_Item::
giveitem ITEM_GREAT_BALL

call FALSE
release
return

RustboroCity_DevonCorp_3F_EventScript_GiveExpShare_Item::
giveitem ITEM_EXP_SHARE

call FALSE
release
return

RustboroCity_Gym_EventScript_Josh_Item::

call FALSE
release
return

RustboroCity_Gym_EventScript_Tommy_Item::

call FALSE
release
return

RustboroCity_Gym_EventScript_Marc_Item::

call FALSE
release
return

RustboroCity_Gym_EventScript_Roxanne_Item::

call FALSE
release
return

Rustboro_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_BADGE01_GET
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT

call FALSE
release
return

RusturfTunnel_EventScript_ItemPokeBall::
finditem ITEM_POKE_BALL

call FALSE
release
return

RusturfTunnel_EventScript_Grunt_Item::
giveitem ITEM_DEVON_PARTS

call FALSE
release
return

RusturfTunnel_EventScript_ClearTunnelScene_ITEM::
giveitem ITEM_HM04

call FALSE
release
return

RusturfTunnel_EventScript_ItemMaxEther::
finditem ITEM_MAX_ETHER

call FALSE
release
return

RusturfTunnel_EventScript_Grunt_Item_Two::

call FALSE
release
return

RusturfTunnel_EventScript_Mike_Item::

call FALSE
release
return

ScorchedSlab_EventScript_ItemTM11::
finditem ITEM_TM11

call FALSE
release
return

SeafloorCavern_Room9_EventScript_ItemTM26::
finditem ITEM_TM26

call FALSE
release
return

SeafloorCavern_Room1_EventScript_Grunt1_Item::

call FALSE
release
return

SeafloorCavern_Room1_EventScript_Grunt2_Item::

call FALSE
release
return

SeafloorCavern_Room4_EventScript_Grunt3_Item::

call FALSE
release
return

SeafloorCavern_Room4_EventScript_Grunt4_Item::

call FALSE
release
return

SeafloorCavern_Room3_EventScript_Grunt5_Item::

call FALSE
release
return

SeafloorCavern_Room3_EventScript_Shelly_Item::

call FALSE
release
return

SeafloorCavern_Room9_EventScript_ArchieAwakenKyogre_Item::

call FALSE
release
return

SlateportCity_PokemonFanClub_EventScript_GiveSootheBell_Item::
giveitem ITEM_SOOTHE_BELL

call FALSE
release
return

SlateportCity_PokemonFanClub_EventScript_GiveRedScarf_Item::
giveitem ITEM_RED_SCARF

call FALSE
release
return

SlateportCity_PokemonFanClub_EventScript_GiveBlueScarf_Item::
giveitem ITEM_BLUE_SCARF

call FALSE
release
return

SlateportCity_PokemonFanClub_EventScript_GivePinkScarf_Item::
giveitem ITEM_PINK_SCARF

call FALSE
release
return

SlateportCity_PokemonFanClub_EventScript_GiveGreenScarf_Item::
giveitem ITEM_GREEN_SCARF

call FALSE
release
return

SlateportCity_PokemonFanClub_EventScript_GiveYellowScarf_Item::
giveitem ITEM_YELLOW_SCARF

call FALSE
release
return

SlateportCity_EventScript_BerryPowderClerk_Item::
giveitem ITEM_POWDER_JAR

call FALSE
release
return

SlateportCity_Harbor_EventScript_DeepSeaTooth_Item::
giveitem ITEM_DEEP_SEA_TOOTH

call FALSE
release
return

SootopolisCity_House1_EventScript_BrickBreakBlackBelt_Item::
giveitem ITEM_TM31

call FALSE
release
return

SootopolisCity_EventScript_GiveWaterfall_Item::
giveitem ITEM_HM07

call FALSE
release
return

SootopolisCity_LotadAndSeedotHouse_EventScript_BigSeedot_Item::
giveitem ITEM_ELIXIR

call FALSE
release
return

SootopolisCity_Gym_1F_EventScript_Juan_Item::

call FALSE
release
return

Sootopolis_Badge_Item::
message RustboroCity_Gym_Text_ReceivedStoneBadge
waitmessage
call Common_EventScript_PlayGymBadgeFanfare
 setflag FLAG_BADGE08_GET
msgbox SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis, MSGBOX_DEFAULT

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Connie_Item::

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Andrea_Item::

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Daphne_Item::

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Annika_Item::

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Tiffany_Item::

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Crissy_Item::

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Bethany_Item::

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Olivia_Item::

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Brianna_Item::

call FALSE
release
return

SootopolisCity_Gym_B1F_EventScript_Bridget_Item::

call FALSE
release
return

SSTidalRooms_EventScript_SnatchGiver_Item::
finditem ITEM_TM49

call FALSE
release
return

SSTidalRooms_EventScript_Jed_Item::

call FALSE
release
return

SSTidalRooms_EventScript_Garret_Item::

call FALSE
release
return

SSTidalRooms_EventScript_Micah_Item::

call FALSE
release
return

SSTidalRooms_EventScript_Colton_Item::

call FALSE
release
return

SSTidalRooms_EventScript_Naomi_Item::

call FALSE
release
return

SSTidalRooms_EventScript_Thomas_Item::

call FALSE
release
return

SSTidalLowerDeck_EventScript_Phillip_Item::

call FALSE
release
return

SSTidalLowerDeck_EventScript_Leonard_Item::

call FALSE
release
return

VerdanturfTown_BattleTentLobby_EventScript_AttractGiver_Item::
giveitem ITEM_TM45

call FALSE
release
return

VictoryRoad_1F_EventScript_ItemMaxElixir::
finditem ITEM_MAX_ELIXIR

call FALSE
release
return

VictoryRoad_1F_EventScript_ItemPPUp::
finditem ITEM_PP_UP

call FALSE
release
return

VictoryRoad_B1F_EventScript_ItemFullRestore::
finditem ITEM_FULL_RESTORE

call FALSE
release
return

VictoryRoad_B1F_EventScript_ItemTM29::
finditem ITEM_TM29

call FALSE
release
return

VictoryRoad_B2F_EventScript_ItemFullHeal::
finditem ITEM_FULL_HEAL

call FALSE
release
return

VictoryRoad_1F_EventScript_Albert_Item::

call FALSE
release
return

VictoryRoad_1F_EventScript_Hope_Item::

call FALSE
release
return

VictoryRoad_B1F_EventScript_Shannon_Item::

call FALSE
release
return

VictoryRoad_B1F_EventScript_Samuel_Item::

call FALSE
release
return

VictoryRoad_B2F_EventScript_Julie_Item::

call FALSE
release
return

VictoryRoad_B2F_EventScript_Owen_Item::

call FALSE
release
return

VictoryRoad_B2F_EventScript_Dianne_Item::

call FALSE
release
return

VictoryRoad_B2F_EventScript_Felix_Item::

call FALSE
release
return

VictoryRoad_B2F_EventScript_Caroline_Item::

call FALSE
release
return

VictoryRoad_B2F_EventScript_Vito_Item::

call FALSE
release
return

VictoryRoad_B1F_EventScript_Michelle_Item::

call FALSE
release
return

VictoryRoad_B1F_EventScript_Mitchell_Item::

call FALSE
release
return

VictoryRoad_B1F_EventScript_Halle_Item::

call FALSE
release
return

VictoryRoad_1F_EventScript_Edgar_Item::

call FALSE
release
return

VictoryRoad_1F_EventScript_Katelynn_Item::

call FALSE
release
return

VictoryRoad_1F_EventScript_Quincy_Item::

call FALSE
release
return

VictoryRoad_1F_EventScript_WallyEntranceBattle_Item::

call FALSE
release
return

MEScrCmd_givepokemon::


        setvar VAR_TEMP_1, SPECIES_EMOLGA
       setvar VAR_TEMP_2, 5
       call Get_Pokemon

call FALSE
release
return

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
finditem ITEM_BIG_PEARL

call FALSE
release
return

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
finditem ITEM_RARE_CANDY

call FALSE
release
return

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
finditem ITEM_ICE_HEAL

call FALSE
release
return

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
finditem ITEM_TM07

call FALSE
release
return

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
finditem ITEM_NEVER_MELT_ICE

call FALSE
release
return

ArtisanCave_B1F_EventScript_ItemHPUp::
finditem ITEM_HP_UP

call FALSE
release
return

ArtisanCave_1F_EventScript_ItemCarbos::
finditem ITEM_CARBOS

call FALSE
release
return


trainer_items::
    switch VAR_TRAINER_BATTLE_OPPONENT_A

  case TRAINER_THALIA_1, AbandonedShip_Rooms_1F_Eventscript_Thalia_Item
  case TRAINER_DEMETRIUS, AbandonedShip_Rooms_1F_EventScript_Demetrius_Item
  case TRAINER_DUNCAN, AbandonedShip_Corridors_B1F_EventScript_Duncan_Item
  case TRAINER_CHARLIE, AbandonedShip_Corridors_1F_EventScript_Charlie_Item
  case TRAINER_GARRISON, AbandonedShip_Rooms2_1F_EventScript_Garrison_Item
  case TRAINER_JANI, AbandonedShip_Rooms2_1F_EventScript_Jani_Item
  case TRAINER_KIRA_AND_DAN_1, AbandonedShip_Rooms2_1F_EventScript_Kira_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_1, AquaHideout_1F_EventScript_Grunt1_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_2, AquaHideout_B1F_EventScript_Grunt2_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_3, AquaHideout_B1F_EventScript_Grunt3_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_4, AquaHideout_B2F_EventScript_Grunt4_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_5, AquaHideout_B1F_EventScript_Grunt5_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_6, AquaHideout_B2F_EventScript_Grunt6_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_7, AquaHideout_B1F_EventScript_Grunt7_Item
  case TRAINER_GRUNT_AQUA_HIDEOUT_8, AquaHideout_B2F_EventScript_Grunt8_Item
  case TRAINER_MATT, AquaHideout_B2F_EventScript_Matt_Item
  case TRAINER_LAURA, DewfordTown_Gym_EventScript_Laura_Item
  case TRAINER_LILITH, DewfordTown_Gym_EventScript_Lilith_Item
  case TRAINER_BRENDEN, DewfordTown_Gym_EventScript_Brenden_Item
  case TRAINER_CRISTIAN, DewfordTown_Gym_EventScript_Cristian_Item
  case TRAINER_JOCELYN, DewfordTown_Gym_EventScript_Jocelyn_Item
  case TRAINER_BRAWLY_1, DewfordTown_Gym_EventScript_Brawly_Item
  case TRAINER_DRAKE, Drake_Item
  case TRAINER_PHOEBE, Phoebe_Item
  case TRAINER_GLACIA, Glacia_Item
  case TRAINER_SIDNEY, Sydney_Item
  case TRAINER_JARED, FortreeCity_Gym_EventScript_Jared_Item
  case TRAINER_HUMBERTO, FortreeCity_Gym_EventScript_Humberto_Item
  case TRAINER_ASHLEY, FortreeCity_Gym_EventScript_Ashley_Item
  case TRAINER_FLINT, FortreeCity_Gym_EventScript_Flint_Item
  case TRAINER_EDWARDO, FortreeCity_Gym_EventScript_Edwardo_Item
  case TRAINER_DARIUS, FortreeCity_Gym_EventScript_Darius_Item
  case TRAINER_WINONA_1, FortreeCity_Gym_EventScript_Winona_Item
  case TRAINER_ERIC, JaggedPass_EventScript_Eric_Item
  case TRAINER_GRUNT_JAGGED_PASS, JaggedPass_EventScript_MagmaHideoutGuard_Item
  case TRAINER_DIANA_1, JaggedPass_EventScript_Diana_Item
  case TRAINER_AUTUMN, JaggedPass_EventScript_Autumn_Item
  case TRAINER_JULIO, JaggedPass_EventScript_Julio_Item
  case TRAINER_ETHAN_1, JaggedPass_EventScript_Ethan_Item
  case TRAINER_JEFF, LavaridgeTown_Gym_B1F_EventScript_Jeff_Item
  case TRAINER_JACE, LavaridgeTown_Gym_B1F_EventScript_Jace_Item
  case TRAINER_ELI, LavaridgeTown_Gym_B1F_EventScript_Eli_Item
  case TRAINER_COLE, LavaridgeTown_Gym_1F_EventScript_Cole_Item
  case TRAINER_GERALD, LavaridgeTown_Gym_1F_EventScript_Gerald_Item
  case TRAINER_AXLE, LavaridgeTown_Gym_1F_EventScript_Axle_Item
  case TRAINER_KEEGAN, LavaridgeTown_Gym_B1F_EventScript_Keegan_Item
  case TRAINER_DANIELLE, LavaridgeTown_Gym_1F_EventScript_Danielle_Item
  case TRAINER_FLANNERY_1, LavaridgeTown_Gym_1F_EventScript_Flannery_Item
  case TRAINER_MAY_LILYCOVE_MUDKIP, LilycoveCity_EventScript_Rival_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_1, MagmaHideout_1F_EventScript_Grunt1_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_2, MagmaHideout_1F_EventScript_Grunt2_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_3, MagmaHideout_2F_1R_EventScript_Grunt3_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_4, MagmaHideout_2F_1R_EventScript_Grunt4_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_5, MagmaHideout_2F_1R_EventScript_Grunt5_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_6, MagmaHideout_2F_2R_EventScript_Grunt6_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_7, MagmaHideout_2F_2R_EventScript_Grunt7_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_8, MagmaHideout_2F_2R_EventScript_Grunt8_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_9, MagmaHideout_3F_1R_EventScript_Grunt9_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_10, MagmaHideout_3F_2R_EventScript_Grunt10_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_11, MagmaHideout_4F_EventScript_Grunt11_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_12, MagmaHideout_4F_EventScript_Grunt12_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_13, MagmaHideout_4F_EventScript_Grunt13_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_14, MagmaHideout_2F_1R_EventScript_Grunt14_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_15, MagmaHideout_2F_2R_EventScript_Grunt15_Item
  case TRAINER_GRUNT_MAGMA_HIDEOUT_16, MagmaHideout_3F_1R_EventScript_Grunt16_Item
  case TRAINER_TABITHA_MAGMA_HIDEOUT, MagmaHideout_4F_EventScript_Tabitha_Item
  case TRAINER_MAXIE_MAGMA_HIDEOUT, MagmaHideout_4F_EventScript_Maxie_Item
  case TRAINER_WALLY_MAUVILLE, MauvilleCity_EventScript_DefeatedWally_Item
  case TRAINER_VIVIAN, MauvilleCity_Gym_EventScript_Vivian_Item
  case TRAINER_KIRK, MauvilleCity_Gym_EventScript_Kirk_Item
  case TRAINER_BEN, MauvilleCity_Gym_EventScript_Ben_Item
  case TRAINER_ANGELO, MauvilleCity_Gym_EventScript_Angelo_Item
  case TRAINER_SHAWN, MauvilleCity_Gym_EventScript_Shawn_Item
  case TRAINER_WATTSON_1, MauvilleCity_Gym_EventScript_Wattson_Item
  case TRAINER_JOHN_AND_JAY_1, MeteorFalls_1F_2R_EventScript_John_Item
  case TRAINER_NICOLAS_1, MeteorFalls_1F_2R_EventScript_Nicolas_Item
  case TRAINER_STEVEN, MeteorFalls_StevensCave_EventScript_Steven_Item
  case TRAINER_PRESTON, MossdeepCity_Gym_EventScript_Preston_Item
  case TRAINER_MAURA, MossdeepCity_Gym_EventScript_Maura_Item
  case TRAINER_SAMANTHA, MossdeepCity_Gym_EventScript_Samantha_Item
  case TRAINER_BLAKE, MossdeepCity_Gym_EventScript_Blake_Item
  case TRAINER_MACEY, MossdeepCity_Gym_EventScript_Macey_Item
  case TRAINER_CLIFFORD, MossdeepCity_Gym_EventScript_Clifford_Item
  case TRAINER_KATHLEEN, MossdeepCity_Gym_EventScript_Kathleen_Item
  case TRAINER_NICHOLAS, MossdeepCity_Gym_EventScript_Nicholas_Item
  case TRAINER_NATE, MossdeepCity_Gym_EventScript_Nate_Item
  case TRAINER_VIRGIL, MossdeepCity_Gym_EventScript_Virgil_Item
  case TRAINER_SYLVIA, MossdeepCity_Gym_EventScript_Sylvia_Item
  case TRAINER_HANNAH, MossdeepCity_Gym_EventScript_Hannah_Item
  case TRAINER_TATE_AND_LIZA_1, MossdeepCity_Gym_EventScript_TateAndLiza_Item
  case TRAINER_MARK, MtPyre_2F_EventScript_Mark_Item
  case TRAINER_LEAH, MtPyre_2F_EventScript_Leah_Item
  case TRAINER_ZANDER, MtPyre_2F_EventScript_Zander_Item
  case TRAINER_DEZ_AND_LUKE, MtPyre_2F_EventScript_Dez_Item
  case TRAINER_KAYLA, MtPyre_3F_EventScript_Kayla_Item
  case TRAINER_GABRIELLE_1, MtPyre_3F_EventScript_Gabrielle_Item
  case TRAINER_WILLIAM, MtPyre_3F_EventScript_William_Item
  case TRAINER_TASHA, MtPyre_4F_EventScript_Tasha_Item
  case TRAINER_ATSUSHI, MtPyre_5F_EventScript_Atsushi_Item
  case TRAINER_VALERIE_1, MtPyre_6F_EventScript_Valerie_Item
  case TRAINER_CEDRIC, MtPyre_6F_EventScript_Cedric_Item
  case TRAINER_GRUNT_MT_PYRE_1, MtPyre_Summit_EventScript_Grunt1_Item
  case TRAINER_GRUNT_MT_PYRE_2, MtPyre_Summit_EventScript_Grunt2_Item
  case TRAINER_GRUNT_MT_PYRE_3, MtPyre_Summit_EventScript_Grunt3_Item
  case TRAINER_GRUNT_MT_PYRE_4, MtPyre_Summit_EventScript_Grunt4_Item
  case TRAINER_RANDALL, PetalburgCity_Gym_EventScript_Randall_Item
  case TRAINER_MARY, PetalburgCity_Gym_EventScript_Mary_Item
  case TRAINER_PARKER, PetalburgCity_Gym_EventScript_Parker_Item
  case TRAINER_ALEXIA, PetalburgCity_Gym_EventScript_Alexia_Item
  case TRAINER_GEORGE, PetalburgCity_Gym_EventScript_George_Item
  case TRAINER_JODY, PetalburgCity_Gym_EventScript_Jody_Item
  case TRAINER_BERKE, PetalburgCity_Gym_EventScript_Berke_Item
  case TRAINER_NORMAN_1, PetalburgCity_Gym_EventScript_NormanBattle_Item
  case TRAINER_LYLE, PetalburgWoods_EventScript_Lyle_Item
  case TRAINER_JAMES_1, PetalburgWoods_EventScript_James_Item
  case TRAINER_GRUNT_PETALBURG_WOODS, PetalburgWoods_EventScript_DevonResearcherLeft_Item
  case TRAINER_CALVIN_1, Route102_EventScript_Calvin_Item
  case TRAINER_RICK, Route102_EventScript_Rick_Item
  case TRAINER_ALLEN, Route102_EventScript_Allen_Item
  case TRAINER_TIANA, Route102_EventScript_Tiana_Item
  case TRAINER_MAY_ROUTE_103_MUDKIP, Route103_EventScript_Item_Rival
  case TRAINER_IMANI, Route105_EventScript_Imani_Item
  case TRAINER_DOMINIK, Route105_EventScript_Dominik_Item
  case TRAINER_FOSTER, Route105_EventScript_Foster_Item
  case TRAINER_BEVERLY, Route105_EventScript_Beverly_Item
  case TRAINER_ANDRES_1, Route105_EventScript_Andres_Item
  case TRAINER_JOSUE, Route105_EventScript_Josue_Item
  case TRAINER_LUIS, Route105_EventScript_Luis_Item
  case TRAINER_NED, Route106_EventScript_Ned_Item
  case TRAINER_ELLIOT_1, Route106_EventScript_Elliot_Item
  case TRAINER_DOUGLAS, Route106_EventScript_Douglas_Item
  case TRAINER_KYLA, Route106_EventScript_Kyla_Item
  case TRAINER_DENISE, Route107_EventScript_Denise_Item
  case TRAINER_TONY_1, Route107_EventScript_Tony_Item
  case TRAINER_LISA_AND_RAY, Route107_EventScript_Lisa_Item
  case TRAINER_DARRIN, Route107_EventScript_Darrin_Item
  case TRAINER_BETH, Route107_EventScript_Beth_Item
  case TRAINER_CAMRON, Route107_EventScript_Camron_Item
  case TRAINER_MISSY, Route108_EventScript_Missy_Item
  case TRAINER_MATTHEW, Route108_EventScript_Matthew_Item
  case TRAINER_TARA, Route108_EventScript_Tara_Item
  case TRAINER_CAROLINA, Route108_EventScript_Carolina_Item
  case TRAINER_CORY_1, Route108_EventScript_Cory_Item
  case TRAINER_JEROME, Route108_EventScript_Jerome_Item
  case TRAINER_HUEY, Route109_EventScript_Huey_Item
  case TRAINER_EDMOND, Route109_EventScript_Edmond_Item
  case TRAINER_HAILEY, Route109_EventScript_Hailey_Item
  case TRAINER_RICKY_1, Route109_EventScript_Ricky_Item
  case TRAINER_LOLA_1, Route109_EventScript_Lola_Item
  case TRAINER_CHANDLER, Route109_EventScript_Chandler_Item
  case TRAINER_SIMON, Route109_SeashoreHouse_EventScript_Simon_Item
  case TRAINER_JOHANNA, Route109_SeashoreHouse_EventScript_Johanna_Item
  case TRAINER_DWAYNE, Route109_SeashoreHouse_EventScript_Dwayne_Item
  case TRAINER_AUSTINA, Route109_EventScript_Austina_Item
  case TRAINER_GWEN, Route109_EventScript_Gwen_Item
  case TRAINER_DAVID, Route109_EventScript_David_Item
  case TRAINER_ALICE, Route109_EventScript_Alice_Item
  case TRAINER_CARTER, Route109_EventScript_Carter_Item
  case TRAINER_ELIJAH, Route109_EventScript_Elijah_Item
  case TRAINER_MEL_AND_PAUL, Route109_EventScript_Mel_Item
  case TRAINER_ISABEL_1, Route110_EventScript_Isabel_Item
  case TRAINER_KALEB, Route110_EventScript_Kaleb_Item
  case TRAINER_TIMMY, Route110_EventScript_Timmy_Item
  case TRAINER_EDWIN_1, Route110_EventScript_Edwin_Item
  case TRAINER_JOSEPH, Route110_EventScript_Joseph_Item
  case TRAINER_EDWARD, Route110_EventScript_Edward_Item
  case TRAINER_ALYSSA, Route110_EventScript_Alyssa_Item
  case TRAINER_DALE, Route110_EventScript_Dale_Item
  case TRAINER_MAY_ROUTE_110_MUDKIP, Route110_EventScript_GiveItemfinder_Item2
  case TRAINER_JACLYN, Route110_EventScript_Jaclyn_Item
  case TRAINER_ABIGAIL_1, Route110_EventScript_Abigail_Item
  case TRAINER_ANTHONY, Route110_EventScript_Anthony_Item
  case TRAINER_BENJAMIN_1, Route110_EventScript_Benjamin_Item
  case TRAINER_JASMINE, Route110_EventScript_Jasmine_Item
  case TRAINER_JACOB, Route110_EventScript_Jacob_Item
  case TRAINER_SALLY, Route110_TrickHousePuzzle1_EventScript_Sally_Item
  case TRAINER_ROBIN, Route110_TrickHousePuzzle1_EventScript_Robin_Item
  case TRAINER_EDDIE, Route110_TrickHousePuzzle1_EventScript_Eddie_Item
  case TRAINER_TED, Route110_TrickHousePuzzle2_EventScript_Ted_Item
  case TRAINER_PAUL, Route110_TrickHousePuzzle2_EventScript_Paul_Item
  case TRAINER_GEORGIA, Route110_TrickHousePuzzle2_EventScript_Georgia_Item
  case TRAINER_JUSTIN, Route110_TrickHousePuzzle3_EventScript_Justin_Item
  case TRAINER_MARTHA, Route110_TrickHousePuzzle3_EventScript_Martha_Item
  case TRAINER_ALAN, Route110_TrickHousePuzzle3_EventScript_Alan_Item
  case TRAINER_YUJI, Route110_TrickHousePuzzle4_EventScript_Yuji_Item
  case TRAINER_CORA, Route110_TrickHousePuzzle4_EventScript_Cora_Item
  case TRAINER_PAULA, Route110_TrickHousePuzzle4_EventScript_Paula_Item
  case TRAINER_SOPHIA, Route110_TrickHousePuzzle6_EventScript_Sophia_Item
  case TRAINER_SEBASTIAN, Route110_TrickHousePuzzle6_EventScript_Sebastian_Item
  case TRAINER_BENNY, Route110_TrickHousePuzzle6_EventScript_Benny_Item
  case TRAINER_JOSHUA, Route110_TrickHousePuzzle7_EventScript_Joshua_Item
  case TRAINER_PATRICIA, Route110_TrickHousePuzzle7_EventScript_Patricia_Item
  case TRAINER_MARIELA, Route110_TrickHousePuzzle7_EventScript_Mariela_Item
  case TRAINER_EVERETT, Route110_TrickHousePuzzle7_EventScript_Everett_Item
  case TRAINER_ALEXIS, Route110_TrickHousePuzzle7_EventScript_Alexis_Item
  case TRAINER_ALVARO, Route110_TrickHousePuzzle7_EventScript_Alvaro_Item
  case TRAINER_KEIRA, Route110_TrickHousePuzzle8_EventScript_Keira_Item
  case TRAINER_VINCENT, Route110_TrickHousePuzzle8_EventScript_Vincent_Item
  case TRAINER_LEROY, Route110_TrickHousePuzzle8_EventScript_Leroy_Item
  case TRAINER_TYRON, Route111_EventScript_Tyron_Item
  case TRAINER_CELINA, Route111_EventScript_Celina_Item
  case TRAINER_BIANCA, Route111_EventScript_Bianca_Item
  case TRAINER_HAYDEN, Route111_EventScript_Hayden_Item
  case TRAINER_GABBY_AND_TY_1, Gabby_Ty_EventScript_1_Item
  case TRAINER_IRENE, Route111_EventScript_Irene_Item
  case TRAINER_TRAVIS, Route111_EventScript_Travis_Item
  case TRAINER_HEIDI, Route111_EventScript_Heidi_Item
  case TRAINER_BEAU, Route111_EventScript_Beau_Item
  case TRAINER_DREW, Route111_EventScript_Drew_Item
  case TRAINER_BECKY, Route111_EventScript_Becky_Item
  case TRAINER_DUSTY_1, Route111_EventScript_Dusty_Item
  case TRAINER_CELIA, Route111_EventScript_Celia_Item
  case TRAINER_BRYAN, Route111_EventScript_Bryan_Item
  case TRAINER_BRANDEN, Route111_EventScript_Branden_Item
  case TRAINER_WILTON_1, Route111_EventScript_Wilton_Item
  case TRAINER_BROOKE_1, Route111_EventScript_Brooke_Item
  case TRAINER_DAISUKE, Route111_EventScript_Daisuke_Item
  case TRAINER_VICTOR, Route111_EventScript_Victor_Item
  case TRAINER_VICTORIA, Route111_WinstrateFamilysHouse_EventScript_Victoria_Item
  case TRAINER_VIVI, Route111_WinstrateFamilysHouse_EventScript_Vivi_Item
  case TRAINER_VICKY, Route111_WinstrateFamilysHouse_EventScript_Vicky_Item
  case TRAINER_LARRY, Route112_EventScript_Larry_Item
  case TRAINER_CAROL, Route112_EventScript_Carol_Item
  case TRAINER_TRENT_1, Route112_EventScript_Trent_Item
  case TRAINER_BRICE, Route112_EventScript_Brice_Item
  case TRAINER_BRYANT, Route112_EventScript_Bryant_Item
  case TRAINER_SHAYLA, Route112_EventScript_Shayla_Item
  case TRAINER_JAYLEN, Route113_EventScript_Jaylen_Item
  case TRAINER_LAWRENCE, Route113_EventScript_Lawrence_Item
  case TRAINER_LUNG, Route113_EventScript_Lung_Item
  case TRAINER_WYATT, Route113_EventScript_Wyatt_Item
  case TRAINER_MADELINE_1, Route113_EventScript_Madeline_Item
  case TRAINER_TORI_AND_TIA, Route113_EventScript_Tori_Item
  case TRAINER_LAO_1, Route113_EventScript_Lao_Item
  case TRAINER_DILLON, Route113_EventScript_Dillon_Item
  case TRAINER_SOPHIE, Route113_EventScript_Sophie_Item
  case TRAINER_COBY, Route113_EventScript_Coby_Item
  case TRAINER_NOLAN, Route114_EventScript_Nolan_Item
  case TRAINER_CHARLOTTE, Route114_EventScript_Charlotte_Item
  case TRAINER_KAI, Route114_EventScript_Kai_Item
  case TRAINER_CLAUDE, Route114_EventScript_Claude_Item
  case TRAINER_NANCY, Route114_EventScript_Nancy_Item
  case TRAINER_TYRA_AND_IVY, Route114_EventScript_Tyra_Item
  case TRAINER_SHANE, Route114_EventScript_Shane_Item
  case TRAINER_STEVE_1, Route114_EventScript_Steve_Item
  case TRAINER_BERNIE_1, Route114_EventScript_Bernie_Item
  case TRAINER_LUCAS_1, Route114_EventScript_Lucas_Item
  case TRAINER_ANGELINA, Route114_EventScript_Angelina_Item
  case TRAINER_LENNY, Route114_EventScript_Lenny_Item
  case TRAINER_NOB_1, Route115_EventScript_Nob_Item
  case TRAINER_HECTOR, Route115_EventScript_Hector_Item
  case TRAINER_MARLENE, Route115_EventScript_Marlene_Item
  case TRAINER_CYNDY_1, Route115_EventScript_Cyndy_Item
  case TRAINER_JAIDEN, Route115_EventScript_Jaiden_Item
  case TRAINER_TIMOTHY_1, Route115_EventScript_Timothy_Item
  case TRAINER_KYRA, Route115_EventScript_Kyra_Item
  case TRAINER_KOICHI, Route115_EventScript_Koichi_Item
  case TRAINER_HELENE, Route115_EventScript_Helene_Item
  case TRAINER_ALIX, Route115_EventScript_Alix_Item
  case TRAINER_JOSE, Route116_EventScript_Jose_Item
  case TRAINER_JOEY, Route116_EventScript_Joey_Item
  case TRAINER_KAREN_1, Route116_EventScript_Karen_Item
  case TRAINER_CLARK, Route116_EventScript_Clark_Item
  case TRAINER_JOHNSON, Route116_EventScript_Johnson_Item
  case TRAINER_DEVAN, Route116_EventScript_Devan_Item
  case TRAINER_SARAH, Route116_EventScript_Sarah_Item
  case TRAINER_DAWSON, Route116_EventScript_Dawson_Item
  case TRAINER_JERRY_1, Route116_EventScript_Jerry_Item
  case TRAINER_JANICE, Route116_EventScript_Janice_Item
  case TRAINER_DYLAN_1, Route117_EventScript_Dylan_Item
  case TRAINER_ANNA_AND_MEG_1, Route117_EventScript_Anna_Item
  case TRAINER_ISAAC_1, Route117_EventScript_Isaac_Item
  case TRAINER_MARIA_1, Route117_EventScript_Maria_Item
  case TRAINER_DEREK, Route117_EventScript_Derek_Item
  case TRAINER_BRANDI, Route117_EventScript_Brandi_Item
  case TRAINER_MELINA, Route117_EventScript_Melina_Item
  case TRAINER_AISHA, Route117_EventScript_Aisha_Item
  case TRAINER_LYDIA_1, Route117_EventScript_Lydia_Item
  case TRAINER_ROSE_1, Route118_EventScript_Rose_Item
  case TRAINER_DEANDRE, Route118_EventScript_Deandre_Item
  case TRAINER_WADE, Route118_EventScript_Wade_Item
  case TRAINER_DALTON_1, Route118_EventScript_Dalton_Item
  case TRAINER_GABBY_AND_TY_2, Gabby_Ty_EventScript_2_Item
  case TRAINER_BARNY, Route118_EventScript_Barny_Item
  case TRAINER_CHESTER, Route118_EventScript_Chester_Item
  case TRAINER_PERRY, Route118_EventScript_Perry_Item
  case TRAINER_KENT, Route119_EventScript_Kent_Item
  case TRAINER_DONALD, Route119_EventScript_Donald_Item
  case TRAINER_GREG, Route119_EventScript_Greg_Item
  case TRAINER_TAYLOR, Route119_EventScript_Taylor_Item
  case TRAINER_DOUG, Route119_EventScript_Doug_Item
  case TRAINER_BRENT, Route119_EventScript_Brent_Item
  case TRAINER_CHRIS, Route119_EventScript_Chris_Item
  case TRAINER_CATHERINE_1, Route119_EventScript_Catherine_Item
  case TRAINER_JACKSON_1, Route119_EventScript_Jackson_Item
  case TRAINER_RACHEL, Route119_EventScript_Rachel_Item
  case TRAINER_PHIL, Route119_EventScript_Phil_Item
  case TRAINER_TAKASHI, Route119_EventScript_Takashi_Item
  case TRAINER_DAYTON, Route119_EventScript_Dayton_Item
  case TRAINER_HUGH, Route119_EventScript_Hugh_Item
  case TRAINER_FABIAN, Route119_EventScript_Fabian_Item
  case TRAINER_YASU, Route119_EventScript_Yasu_Item
  case TRAINER_HIDEO, Route119_EventScript_Hideo_Item
  case TRAINER_MAY_ROUTE_119_MUDKIP, Route119_EventScript_RivalExitScottArrive_Item
  case TRAINER_GRUNT_WEATHER_INST_1, Route119_WeatherInstitute_1F_EventScript_Grunt1_Item
  case TRAINER_GRUNT_WEATHER_INST_2, Route119_WeatherInstitute_2F_EventScript_Grunt2_Item
  case TRAINER_GRUNT_WEATHER_INST_3, Route119_WeatherInstitute_2F_EventScript_Grunt3_Item
  case TRAINER_GRUNT_WEATHER_INST_4, Route119_WeatherInstitute_1F_EventScript_Grunt4_Item
  case TRAINER_GRUNT_WEATHER_INST_5, Route119_WeatherInstitute_2F_EventScript_Grunt5_Item
  case TRAINER_SHELLY_WEATHER_INSTITUTE, Route119_WeatherInstitute_2F_EventScript_Shelly_Item
  case TRAINER_CLARISSA, Route120_EventScript_Clarissa_Item
  case TRAINER_GABBY_AND_TY_3, Gabby_Ty_EventScript_3_Item
  case TRAINER_ROBERT_1, Route120_EventScript_Robert_Item
  case TRAINER_COLIN, Route120_EventScript_Colin_Item
  case TRAINER_LEONEL, Route120_EventScript_Leonel_Item
  case TRAINER_ANGELICA, Route120_EventScript_Angelica_Item
  case TRAINER_RILEY, Route120_EventScript_Riley_Item
  case TRAINER_CALLIE, Route120_EventScript_Callie_Item
  case TRAINER_JENNIFER, Route120_EventScript_Jennifer_Item
  case TRAINER_JENNA, Route120_EventScript_Jenna_Item
  case TRAINER_LORENZO, Route120_EventScript_Lorenzo_Item
  case TRAINER_JEFFREY_1, Route120_EventScript_Jeffrey_Item
  case TRAINER_KEIGO, Route120_EventScript_Keigo_Item
  case TRAINER_CHIP, Route120_EventScript_Chip_Item
  case TRAINER_CALE, Route121_EventScript_Cale_Item
  case TRAINER_TAMMY, Route121_EventScript_Tammy_Item
  case TRAINER_JESSICA_1, Route121_EventScript_Jessica_Item
  case TRAINER_KATE_AND_JOY, Route121_EventScript_Kate_Item
  case TRAINER_PAT, Route121_EventScript_Pat_Item
  case TRAINER_MYLES, Route121_EventScript_Myles_Item
  case TRAINER_WALTER_1, Route121_EventScript_Walter_Item
  case TRAINER_VANESSA, Route121_EventScript_Vanessa_Item
  case TRAINER_MARCEL, Route121_EventScript_Marcel_Item
  case TRAINER_CRISTIN_1, Route121_EventScript_Cristin_Item
  case TRAINER_DAVIS, Route123_EventScript_Davis_Item
  case TRAINER_JAZMYN, Route123_EventScript_Jazmyn_Item
  case TRAINER_VIOLET, Route123_EventScript_Violet_Item
  case TRAINER_MIU_AND_YUKI, Route123_EventScript_Miu_Item
  case TRAINER_KINDRA, Route123_EventScript_Kindra_Item
  case TRAINER_ED, Route123_EventScript_Ed_Item
  case TRAINER_WENDY, Route123_EventScript_Wendy_Item
  case TRAINER_BRAXTON, Route123_EventScript_Braxton_Item
  case TRAINER_FERNANDO_1, Route123_EventScript_Fernando_Item
  case TRAINER_ALBERTO, Route123_EventScript_Alberto_Item
  case TRAINER_JACKI_1, Route123_EventScript_Jacki_Item
  case TRAINER_FREDRICK, Route123_EventScript_Frederick_Item
  case TRAINER_GRACE, Route124_EventScript_Grace_Item
  case TRAINER_DECLAN, Route124_EventScript_Declan_Item
  case TRAINER_LILA_AND_ROY_1, Route124_EventScript_Lila_Item
  case TRAINER_SPENCER, Route124_EventScript_Spencer_Item
  case TRAINER_JENNY_1, Route124_EventScript_Jenny_Item
  case TRAINER_CHAD, Route124_EventScript_Chad_Item
  case TRAINER_ISABELLA, Route124_EventScript_Isabella_Item
  case TRAINER_ROLAND, Route124_EventScript_Roland_Item
  case TRAINER_ERNEST_1, Route125_EventScript_Ernest_Item
  case TRAINER_NOLEN, Route125_EventScript_Nolen_Item
  case TRAINER_SHARON, Route125_EventScript_Sharon_Item
  case TRAINER_TANYA, Route125_EventScript_Tanya_Item
  case TRAINER_PRESLEY, Route125_EventScript_Presley_Item
  case TRAINER_AURON, Route125_EventScript_Auron_Item
  case TRAINER_STAN, Route125_EventScript_Stan_Item
  case TRAINER_KIM_AND_IRIS, Route125_EventScript_Kim_Item
  case TRAINER_LEONARDO, Route126_EventScript_Leonardo_Item
  case TRAINER_ISOBEL, Route126_EventScript_Isobel_Item
  case TRAINER_DEAN, Route126_EventScript_Dean_Item
  case TRAINER_NIKKI, Route126_EventScript_Nikki_Item
  case TRAINER_BARRY, Route126_EventScript_Barry_Item
  case TRAINER_SIENNA, Route126_EventScript_Sienna_Item
  case TRAINER_PABLO_1, Route126_EventScript_Pablo_Item
  case TRAINER_BRENDA, Route126_EventScript_Brenda_Item
  case TRAINER_RUBEN, Route128_EventScript_Ruben_Item
  case TRAINER_ALEXA, Route128_EventScript_Alexa_Item
  case TRAINER_WAYNE, Route128_EventScript_Wayne_Item
  case TRAINER_ISAIAH_1, Route128_EventScript_Isaiah_Item
  case TRAINER_KATELYN_1, Route128_EventScript_Katelyn_Item
  case TRAINER_CARLEE, Route128_EventScript_Carlee_Item
  case TRAINER_HARRISON, Route128_EventScript_Harrison_Item
  case TRAINER_REED, Route129_EventScript_Reed_Item
  case TRAINER_CHASE, Route129_EventScript_Chase_Item
  case TRAINER_ALLISON, Route129_EventScript_Allison_Item
  case TRAINER_CLARENCE, Route129_EventScript_Clarence_Item
  case TRAINER_TISHA, Route129_EventScript_Tisha_Item
  case TRAINER_RODNEY, Route130_EventScript_Rodney_Item
  case TRAINER_KATIE, Route130_EventScript_Katie_Item
  case TRAINER_SANTIAGO, Route130_EventScript_Santiago_Item
  case TRAINER_KEVIN, Route131_EventScript_Kevin_Item
  case TRAINER_TALIA, Route131_EventScript_Talia_Item
  case TRAINER_RICHARD, Route131_EventScript_Richard_Item
  case TRAINER_KARA, Route131_EventScript_Kara_Item
  case TRAINER_HERMAN, Route131_EventScript_Herman_Item
  case TRAINER_SUSIE, Route131_EventScript_Susie_Item
  case TRAINER_RELI_AND_IAN, Route131_EventScript_Reli_Item
  case TRAINER_GILBERT, Route132_EventScript_Gilbert_Item
  case TRAINER_DANA, Route132_EventScript_Dana_Item
  case TRAINER_RONALD, Route132_EventScript_Ronald_Item
  case TRAINER_KIYO, Route132_EventScript_Kiyo_Item
  case TRAINER_PAXTON, Route132_EventScript_Paxton_Item
  case TRAINER_DARCY, Route132_EventScript_Darcy_Item
  case TRAINER_MAKAYLA, Route132_EventScript_Makayla_Item
  case TRAINER_JONATHAN, Route132_EventScript_Jonathan_Item
  case TRAINER_FRANKLIN, Route133_EventScript_Franklin_Item
  case TRAINER_WARREN, Route133_EventScript_Warren_Item
  case TRAINER_BECK, Route133_EventScript_Beck_Item
  case TRAINER_DEBRA, Route133_EventScript_Debra_Item
  case TRAINER_LINDA, Route133_EventScript_Linda_Item
  case TRAINER_CONOR, Route133_EventScript_Conor_Item
  case TRAINER_MOLLIE, Route133_EventScript_Mollie_Item
  case TRAINER_LAUREL, Route134_EventScript_Laurel_Item
  case TRAINER_JACK, Route134_EventScript_Jack_Item
  case TRAINER_HITOSHI, Route134_EventScript_Hitoshi_Item
  case TRAINER_REYNA, Route134_EventScript_Reyna_Item
  case TRAINER_HUDSON, Route134_EventScript_Hudson_Item
  case TRAINER_AARON, Route134_EventScript_Aaron_Item
  case TRAINER_MARLEY, Route134_EventScript_Marley_Item
  case TRAINER_ALEX, Route134_EventScript_Alex_Item
  case TRAINER_KELVIN, Route134_EventScript_Kelvin_Item
  case TRAINER_JOSH, RustboroCity_Gym_EventScript_Josh_Item
  case TRAINER_TOMMY, RustboroCity_Gym_EventScript_Tommy_Item
  case TRAINER_MARC, RustboroCity_Gym_EventScript_Marc_Item
  case TRAINER_ROXANNE_1, RustboroCity_Gym_EventScript_Roxanne_Item
  case TRAINER_GRUNT_RUSTURF_TUNNEL, RusturfTunnel_EventScript_Grunt_Item_Two
  case TRAINER_MIKE_1, RusturfTunnel_EventScript_Mike_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_1, SeafloorCavern_Room1_EventScript_Grunt1_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_2, SeafloorCavern_Room1_EventScript_Grunt2_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_3, SeafloorCavern_Room4_EventScript_Grunt3_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_4, SeafloorCavern_Room4_EventScript_Grunt4_Item
  case TRAINER_GRUNT_SEAFLOOR_CAVERN_5, SeafloorCavern_Room3_EventScript_Grunt5_Item
  case TRAINER_SHELLY_SEAFLOOR_CAVERN, SeafloorCavern_Room3_EventScript_Shelly_Item
  case TRAINER_ARCHIE, SeafloorCavern_Room9_EventScript_ArchieAwakenKyogre_Item
  case TRAINER_JUAN_1, SootopolisCity_Gym_1F_EventScript_Juan_Item
  case TRAINER_CONNIE, SootopolisCity_Gym_B1F_EventScript_Connie_Item
  case TRAINER_ANDREA, SootopolisCity_Gym_B1F_EventScript_Andrea_Item
  case TRAINER_DAPHNE, SootopolisCity_Gym_B1F_EventScript_Daphne_Item
  case TRAINER_ANNIKA, SootopolisCity_Gym_B1F_EventScript_Annika_Item
  case TRAINER_TIFFANY, SootopolisCity_Gym_B1F_EventScript_Tiffany_Item
  case TRAINER_CRISSY, SootopolisCity_Gym_B1F_EventScript_Crissy_Item
  case TRAINER_BETHANY, SootopolisCity_Gym_B1F_EventScript_Bethany_Item
  case TRAINER_OLIVIA, SootopolisCity_Gym_B1F_EventScript_Olivia_Item
  case TRAINER_BRIANNA, SootopolisCity_Gym_B1F_EventScript_Brianna_Item
  case TRAINER_BRIDGET, SootopolisCity_Gym_B1F_EventScript_Bridget_Item
  case TRAINER_LEA_AND_JED, SSTidalRooms_EventScript_Jed_Item
  case TRAINER_GARRET, SSTidalRooms_EventScript_Garret_Item
  case TRAINER_MICAH, SSTidalRooms_EventScript_Micah_Item
  case TRAINER_COLTON, SSTidalRooms_EventScript_Colton_Item
  case TRAINER_NAOMI, SSTidalRooms_EventScript_Naomi_Item
  case TRAINER_THOMAS, SSTidalRooms_EventScript_Thomas_Item
  case TRAINER_PHILLIP, SSTidalLowerDeck_EventScript_Phillip_Item
  case TRAINER_LEONARD, SSTidalLowerDeck_EventScript_Leonard_Item
  case TRAINER_ALBERT, VictoryRoad_1F_EventScript_Albert_Item
  case TRAINER_HOPE, VictoryRoad_1F_EventScript_Hope_Item
  case TRAINER_SHANNON, VictoryRoad_B1F_EventScript_Shannon_Item
  case TRAINER_SAMUEL, VictoryRoad_B1F_EventScript_Samuel_Item
  case TRAINER_JULIE, VictoryRoad_B2F_EventScript_Julie_Item
  case TRAINER_OWEN, VictoryRoad_B2F_EventScript_Owen_Item
  case TRAINER_DIANNE, VictoryRoad_B2F_EventScript_Dianne_Item
  case TRAINER_FELIX, VictoryRoad_B2F_EventScript_Felix_Item
  case TRAINER_CAROLINE, VictoryRoad_B2F_EventScript_Caroline_Item
  case TRAINER_VITO, VictoryRoad_B2F_EventScript_Vito_Item
  case TRAINER_MICHELLE, VictoryRoad_B1F_EventScript_Michelle_Item
  case TRAINER_MITCHELL, VictoryRoad_B1F_EventScript_Mitchell_Item
  case TRAINER_HALLE, VictoryRoad_B1F_EventScript_Halle_Item
  case TRAINER_EDGAR, VictoryRoad_1F_EventScript_Edgar_Item
  case TRAINER_KATELYNN, VictoryRoad_1F_EventScript_Katelynn_Item
  case TRAINER_QUINCY, VictoryRoad_1F_EventScript_Quincy_Item
  case TRAINER_WALLY_VR_1, VictoryRoad_1F_EventScript_WallyEntranceBattle_Item
case TRAINER_BRENDAN_ROUTE_103_MUDKIP, Route103_EventScript_Item_Rival
    case TRAINER_BRENDAN_ROUTE_110_MUDKIP, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_BRENDAN_ROUTE_119_MUDKIP, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_BRENDAN_ROUTE_103_TREECKO, Route103_EventScript_Item_Rival
    case TRAINER_BRENDAN_ROUTE_110_TREECKO, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_BRENDAN_ROUTE_119_TREECKO, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_BRENDAN_ROUTE_103_TORCHIC, Route103_EventScript_Item_Rival
    case TRAINER_BRENDAN_ROUTE_110_TORCHIC, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_BRENDAN_ROUTE_119_TORCHIC, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_BRENDAN_ROUTE_103_MUDKIP, Route103_EventScript_Item_Rival
    case TRAINER_MAY_ROUTE_103_TREECKO, Route103_EventScript_Item_Rival
    case TRAINER_MAY_ROUTE_110_TREECKO, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_MAY_ROUTE_119_TREECKO, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_MAY_ROUTE_103_TORCHIC, Route103_EventScript_Item_Rival
    case TRAINER_MAY_ROUTE_110_TORCHIC, Route110_EventScript_GiveItemfinder_Item2
    case TRAINER_MAY_ROUTE_119_TORCHIC, Route119_EventScript_RivalExitScottArrive_Item
    case TRAINER_BRENDAN_LILYCOVE_MUDKIP, LilycoveCity_EventScript_Rival_Item
    case TRAINER_BRENDAN_LILYCOVE_TREECKO, LilycoveCity_EventScript_Rival_Item
    case TRAINER_BRENDAN_LILYCOVE_TORCHIC, LilycoveCity_EventScript_Rival_Item
    case TRAINER_MAY_LILYCOVE_TREECKO, LilycoveCity_EventScript_Rival_Item
    case TRAINER_MAY_LILYCOVE_TORCHIC, LilycoveCity_EventScript_Rival_Item
    return
Recieve_Mon_Fanfare::
	playfanfare MUS_OBTAIN_ITEM
	bufferspeciesname STR_VAR_1, VAR_TEMP_1
	message Player_Recieved_Mon
	waitmessage
	waitfanfare
	return

Player_Recieved_Mon:
	.string "{PLAYER} received {STR_VAR_1}!$"

Recieve_Pokemon_Party::
	call Recieve_Mon_Fanfare
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	call Common_EventScript_GetGiftMonPartySlot
	call Common_EventScript_NameReceivedPartyMon
	return

Recieve_Pokemon_PC::
	call Recieve_Mon_Fanfare
	msgbox gText_NicknameThisPokemon, MSGBOX_YESNO
	call Common_EventScript_NameReceivedBoxMon
   call Common_EventScript_TransferredToPC
	return

Get_Pokemon::
	givemon VAR_TEMP_1, 15
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PARTY, Recieve_Pokemon_Party
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PC, Recieve_Pokemon_PC
	goto Common_EventScript_NoMoreRoomForPokemon
    return
Rustboro_Pokemon::
    setvar VAR_TEMP_1, SPECIES_PINSIR
   setvar VAR_TEMP_2, 15
   call Get_Pokemon

Dewford_Pokemon::
    setvar VAR_TEMP_1, SPECIES_CROCONAW
   setvar VAR_TEMP_2, 19
   call Get_Pokemon

Mauville_Pokemon::
    setvar VAR_TEMP_1, SPECIES_MANTINE
   setvar VAR_TEMP_2, 24
   call Get_Pokemon

Lavaridge_Pokemon::
    setvar VAR_TEMP_1, SPECIES_MARSHTOMP
   setvar VAR_TEMP_2, 29
   call Get_Pokemon

Petalburg_Pokemon::
    setvar VAR_TEMP_1, SPECIES_MAGEARNA
   setvar VAR_TEMP_2, 31
   call Get_Pokemon

Fortree_Pokemon::
    setvar VAR_TEMP_1, SPECIES_STUFFUL
   setvar VAR_TEMP_2, 33
   call Get_Pokemon

Mosdeep_Pokemon::
    setvar VAR_TEMP_1, SPECIES_YUNGOOS
   setvar VAR_TEMP_2, 42
   call Get_Pokemon

Sootopolis_Pokemon::
    setvar VAR_TEMP_1, SPECIES_POLITOED
   setvar VAR_TEMP_2, 46
   call Get_Pokemon
Startup_Stuff::
setflag FLAG_ALL_BALLS_MASTERBALL
setflag FLAG_HMS_NEED_BADGES
clearflag FLAG_RARE_CANDY_MOD
clearflag OW_FOLLOWERS_ENABLED
return
