# 1 "data/maps/VictoryRoad_B2F/scripts.pory"

# 2 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_MapScripts::
# 3 "data/maps/VictoryRoad_B2F/scripts.pory"
	.byte 0
# 4 "data/maps/VictoryRoad_B2F/scripts.pory"

# 5 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Vito::
# 6 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_VITO, VictoryRoad_B2F_Text_VitoIntro, VictoryRoad_B2F_Text_VitoDefeat
# 7 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_VitoPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/VictoryRoad_B2F/scripts.pory"
	call VictoryRoad_B2F_EventScript_Vito_Item
# 9 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 10 "data/maps/VictoryRoad_B2F/scripts.pory"

# 11 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Owen::
# 12 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_OWEN, VictoryRoad_B2F_Text_OwenIntro, VictoryRoad_B2F_Text_OwenDefeat
# 13 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_OwenPostBattle, MSGBOX_AUTOCLOSE
# 14 "data/maps/VictoryRoad_B2F/scripts.pory"
	call VictoryRoad_B2F_EventScript_Owen_Item
# 15 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 16 "data/maps/VictoryRoad_B2F/scripts.pory"

# 17 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Caroline::
# 18 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_CAROLINE, VictoryRoad_B2F_Text_CarolineIntro, VictoryRoad_B2F_Text_CarolineDefeat
# 19 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_CarolinePostBattle, MSGBOX_AUTOCLOSE
# 20 "data/maps/VictoryRoad_B2F/scripts.pory"
	call VictoryRoad_B2F_EventScript_Caroline_Item
# 21 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 22 "data/maps/VictoryRoad_B2F/scripts.pory"

# 23 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Julie::
# 24 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_JULIE, VictoryRoad_B2F_Text_JulieIntro, VictoryRoad_B2F_Text_JulieDefeat
# 25 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_JuliePostBattle, MSGBOX_AUTOCLOSE
# 26 "data/maps/VictoryRoad_B2F/scripts.pory"
	call VictoryRoad_B2F_EventScript_Julie_Item
# 27 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 28 "data/maps/VictoryRoad_B2F/scripts.pory"

# 29 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Felix::
# 30 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_FELIX, VictoryRoad_B2F_Text_FelixIntro, VictoryRoad_B2F_Text_FelixDefeat
# 31 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_FelixPostBattle, MSGBOX_AUTOCLOSE
# 32 "data/maps/VictoryRoad_B2F/scripts.pory"
	call VictoryRoad_B2F_EventScript_Felix_Item
# 33 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 34 "data/maps/VictoryRoad_B2F/scripts.pory"

# 35 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Dianne::
# 36 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_DIANNE, VictoryRoad_B2F_Text_DianneIntro, VictoryRoad_B2F_Text_DianneDefeat
# 37 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_DiannePostBattle, MSGBOX_AUTOCLOSE
# 38 "data/maps/VictoryRoad_B2F/scripts.pory"
	call VictoryRoad_B2F_EventScript_Dianne_Item
# 39 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 40 "data/maps/VictoryRoad_B2F/scripts.pory"

# 41 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_VitoIntro:
# 42 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I trained together with my whole family,\n"
# 43 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "every one of us!\l"
# 44 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I'm not losing to anyone!$"
# 45 "data/maps/VictoryRoad_B2F/scripts.pory"

# 46 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_VitoDefeat:
# 47 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Better than my family?!\n"
# 48 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Is that possible?!$"
# 49 "data/maps/VictoryRoad_B2F/scripts.pory"

# 50 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_VitoPostBattle:
# 51 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I was better than everyone in my\n"
# 52 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "family. I've never lost before…\p"
# 53 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I've lost my confidence…\n"
# 54 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Maybe I'll go home…$"
# 55 "data/maps/VictoryRoad_B2F/scripts.pory"

# 56 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_OwenIntro:
# 57 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I'd heard that there was a tough\n"
# 58 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "little kid around. Do they mean you?$"
# 59 "data/maps/VictoryRoad_B2F/scripts.pory"

# 60 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_OwenDefeat:
# 61 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The little shrimp is tough!$"
# 62 "data/maps/VictoryRoad_B2F/scripts.pory"

# 63 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_OwenPostBattle:
# 64 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The rumors I heard, that tough little\n"
# 65 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "kid is from PETALBURG CITY.$"
# 66 "data/maps/VictoryRoad_B2F/scripts.pory"

# 67 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_CarolineIntro:
# 68 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You must be getting a little tired.$"
# 69 "data/maps/VictoryRoad_B2F/scripts.pory"

# 70 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_CarolineDefeat:
# 71 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "No signs of tiring at all!$"
# 72 "data/maps/VictoryRoad_B2F/scripts.pory"

# 73 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_CarolinePostBattle:
# 74 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "VICTORY ROAD and the POKéMON LEAGUE\n"
# 75 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "are long and grueling challenges.\l"
# 76 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Beware of fatigue!$"
# 77 "data/maps/VictoryRoad_B2F/scripts.pory"

# 78 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_JulieIntro:
# 79 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You shouldn't get complacent just\n"
# 80 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "because you have a lot of GYM BADGES.\p"
# 81 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "There's always going to be someone\n"
# 82 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "who's better than you!$"
# 83 "data/maps/VictoryRoad_B2F/scripts.pory"

# 84 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_JulieDefeat:
# 85 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You're better than me!$"
# 86 "data/maps/VictoryRoad_B2F/scripts.pory"

# 87 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_JuliePostBattle:
# 88 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Gaze on your collected BADGES and\n"
# 89 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "remember the TRAINERS you've faced.$"
# 90 "data/maps/VictoryRoad_B2F/scripts.pory"

# 91 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_FelixIntro:
# 92 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I've come this far, but the tension's\n"
# 93 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "giving me awful stomach pain…$"
# 94 "data/maps/VictoryRoad_B2F/scripts.pory"

# 95 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_FelixDefeat:
# 96 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Ooh…\n"
# 97 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "It hurts…$"
# 98 "data/maps/VictoryRoad_B2F/scripts.pory"

# 99 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_FelixPostBattle:
# 100 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I can't help getting all tense knowing\n"
# 101 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "that I'm nearing the POKéMON LEAGUE.\p"
# 102 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "It's all I can do to feign calm.$"
# 103 "data/maps/VictoryRoad_B2F/scripts.pory"

# 104 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_DianneIntro:
# 105 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The elite among the elite gather in\n"
# 106 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "this cave.\p"
# 107 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "How are you finding it?$"
# 108 "data/maps/VictoryRoad_B2F/scripts.pory"

# 109 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_DianneDefeat:
# 110 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Not rattled in the least bit!$"
# 111 "data/maps/VictoryRoad_B2F/scripts.pory"

# 112 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_DiannePostBattle:
# 113 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You do have guts! I like that!\n"
# 114 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Keep it going!$"
