# 1 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 2 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_MapScripts::
# 3 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 5 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Andrea::
# 6 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
# 7 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Andrea_Item
# 9 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 10 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 11 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Crissy::
# 12 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
# 13 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
# 14 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Crissy_Item
# 15 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 16 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 17 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Brianna::
# 18 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
# 19 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
# 20 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Brianna_Item
# 21 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 22 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 23 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Connie::
# 24 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
# 25 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
# 26 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Connie_Item
# 27 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 28 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 29 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Bridget::
# 30 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
# 31 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
# 32 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Bridget_Item
# 33 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 34 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 35 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Olivia::
# 36 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
# 37 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
# 38 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Olivia_Item
# 39 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 40 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 41 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Tiffany::
# 42 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
# 43 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
# 44 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Tiffany_Item
# 45 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 46 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 47 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Bethany::
# 48 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
# 49 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
# 50 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Bethany_Item
# 51 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 52 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 53 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Annika::
# 54 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
# 55 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
# 56 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Annika_Item
# 57 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 58 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 59 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Daphne::
# 60 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
# 61 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
# 62 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	call SootopolisCity_Gym_B1F_EventScript_Daphne_Item
# 63 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 64 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 65 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaIntro:
# 66 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I'll show you the sublime techniques\n"
# 67 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I learned from our LEADER JUAN!$"
# 68 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 69 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaDefeat:
# 70 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Please forgive me, JUAN…$"
# 71 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 72 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
# 73 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Watch what happens if you crack all\n"
# 74 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "the floor tiles.$"
# 75 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 76 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_CrissyIntro:
# 77 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You came all the way here, but you won't\n"
# 78 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "get to see JUAN.\p"
# 79 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Not if you lose to me, you won't!$"
# 80 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 81 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_CrissyDefeat:
# 82 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You're strong!\n"
# 83 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I was fooled by your cute looks!$"
# 84 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 85 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
# 86 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You might be good enough to avoid\n"
# 87 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "being wiped out in one hit by JUAN.$"
# 88 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 89 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphneIntro:
# 90 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The sight of JUAN conducting\n"
# 91 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "a battle…\p"
# 92 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The very beauty of it compelled me to\n"
# 93 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "become a TRAINER.$"
# 94 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 95 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphneDefeat:
# 96 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You battled with more beauty than\n"
# 97 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I could muster…$"
# 98 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 99 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
# 100 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The grace you bring to battle is\n"
# 101 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "fabulous.\p"
# 102 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh… I'm so fortunate to have found\n"
# 103 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "POKéMON.$"
# 104 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 105 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConnieIntro:
# 106 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I should teach you how harsh battles\n"
# 107 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "can be.$"
# 108 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 109 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConnieDefeat:
# 110 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh.\n"
# 111 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You're strong.$"
# 112 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 113 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConniePostBattle:
# 114 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I'll tell you something good.\p"
# 115 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "If you want to reach JUAN, you\n"
# 116 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "need to walk on each floor tile once.$"
# 117 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 118 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetIntro:
# 119 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The POKéMON GYM of the highest level\n"
# 120 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "in the HOENN region…\p"
# 121 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "That's the SOOTOPOLIS GYM.$"
# 122 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 123 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetDefeat:
# 124 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "What a high level you are!$"
# 125 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 126 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
# 127 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Rather than being satisfied by being\n"
# 128 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "in a strong GYM, I imagine training in\l"
# 129 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "other places will make you stronger.\l"
# 130 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "But above all, it looks more fun.$"
# 131 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 132 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaIntro:
# 133 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I train my POKéMON together with\n"
# 134 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "JUAN.\p"
# 135 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Don't think I'm a pushover.$"
# 136 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 137 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaDefeat:
# 138 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I was beaten…$"
# 139 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 140 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
# 141 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I think you have potential.\n"
# 142 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Why don't you stay and train with us?$"
# 143 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 144 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyIntro:
# 145 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "A graceful glide across the ice while\n"
# 146 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "crossing no lines…\p"
# 147 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "A TRAINER putting on that performance\n"
# 148 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "would be elegantly beautiful!$"
# 149 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 150 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
# 151 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Well, excuse me?!$"
# 152 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 153 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
# 154 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "This is really obvious, but how strong\n"
# 155 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "you are as a TRAINER has nothing to do\l"
# 156 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "with how young or old you are.$"
# 157 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 158 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BethanyIntro:
# 159 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "When I'm with my POKéMON, the time\n"
# 160 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "flies by before you can say, “Oops!”$"
# 161 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 162 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BethanyDefeat:
# 163 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oops!$"
# 164 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 165 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
# 166 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I wish I could forget about lost causes\n"
# 167 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "before I can manage an “Oops!”$"
# 168 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 169 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaIntro:
# 170 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I can battle with really rare POKéMON\n"
# 171 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "if you'd like.$"
# 172 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 173 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
# 174 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh, there now! Did you have a good look\n"
# 175 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "at my POKéMON?$"
# 176 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 177 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
# 178 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I came to this GYM because JUAN\n"
# 179 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "praised me for my darling POKéMON.\p"
# 180 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh, if only I'd met JUAN years ago\n"
# 181 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "when I was younger…$"
# 182 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 183 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BriannaIntro:
# 184 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Giggle…\n"
# 185 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Your grim look is so charming.$"
# 186 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 187 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BriannaDefeat:
# 188 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh, dear.\n"
# 189 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I went much too easy on you.$"
# 190 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 191 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
# 192 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You couldn't lay a finger on JUAN,\n"
# 193 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I'm sure. Giggle…$"
